#!/usr/bin/env python3
"""Generate the JavaScript protocol constants from opendisplay_protocol.h.

The C header `src/opendisplay_protocol.h` is the single source of truth for every
value on the OpenDisplay BLE wire. Firmware repos vendor it byte-for-byte;
Python and JavaScript cannot `#include` a C header, so each GENERATES the
equivalent module and CI verifies it has not drifted. Parsing is done by the
shared `protocol_model` (same parser as gen_python_protocol.py); this file only
renders JavaScript.

CANONICAL SOURCE
    opendisplay-protocol/src/opendisplay_protocol.h   (macro-only, `u`-suffixed)

GENERATED ARTIFACTS (ESM + TypeScript declarations)
    opendisplay-protocol/src/opendisplay_protocol.js    (export const ...)
    opendisplay-protocol/src/opendisplay_protocol.d.ts   (export declare const ... : <literal>)

The .js is a plain ES module usable in browsers and Node with no build step; the
.d.ts gives TypeScript consumers exact literal types (e.g. `0x0082`). Constants are
flat `export const` (not a TS `enum`) because the wire intentionally reuses byte
values across distinct names -- keeping every name is why an enum is wrong here.

USAGE
    tools/gen_js_protocol.py --write          # (re)generate the .js and .d.ts
    tools/gen_js_protocol.py --check           # verify both match (exit 1 on drift)
    tools/gen_js_protocol.py --stdout          # print the .js (only) to stdout
    tools/gen_js_protocol.py --header FILE --out-js FILE --out-dts FILE

EXIT CODES
    0  success / in sync
    1  drift, missing file, or a value the parser cannot classify

Stdlib only; no third-party dependencies. Python 3.8+.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Optional

from protocol_model import Const, Group, clean_edges, die, parse_header, protocol_version, reconcile, source_sha

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_HEADER = REPO_ROOT / "src" / "opendisplay_protocol.h"
DEFAULT_OUT_JS = REPO_ROOT / "src" / "opendisplay_protocol.js"
DEFAULT_OUT_DTS = REPO_ROOT / "src" / "opendisplay_protocol.d.ts"
REGEN_CMD = "tools/gen_js_protocol.py --write"


def _comment_lines(doc: List[str]) -> List[str]:
    """Render cleaned doc lines as JS line comments (bare `//` for blank lines)."""
    return [("//" if line == "" else f"// {line}") for line in doc]


def _banner(text: str, groups: List[Group], header_name: str) -> List[str]:
    sha = source_sha(text)
    version = protocol_version(groups)
    return [
        "// @generated by tools/gen_js_protocol.py -- DO NOT EDIT BY HAND.",
        f"// Source: {header_name} (OD_PROTOCOL_VERSION {version})",
        f"// Source SHA-256: {sha}",
        f"// Regenerate: {REGEN_CMD}   (CI drift gate: --check)",
        "//",
        "// OpenDisplay BLE wire-protocol constants. Every value here travels on the wire.",
        "// Flat `export const` (not a TS enum) because the wire reuses byte values across",
        "// distinct names. NACK error codes are opcode-SCOPED: decode data[0] only in the",
        "// scope of the echoed opcode (see the header for the full contract).",
        "",
    ]


def _dts_type(const: Const) -> str:
    """The TypeScript literal type for a constant's declaration."""
    if const.kind == "ref":
        return f"typeof {const.value}"  # a value name is not a type; mirror its type
    return const.value  # int / string literal doubles as its own literal type


def render_js(text: str, groups: List[Group], header_name: str) -> str:
    """Render the ES module (.js)."""
    out = _banner(text, groups, header_name)
    for group in groups:
        out.append(f"// ===== {group.label} =====")
        if group.intro:
            out.extend(_comment_lines(group.intro))
        out.append("")
        for idx, const in enumerate(group.consts):
            if const.doc and idx > 0:
                out.append("")
            out.extend(_comment_lines(const.doc))
            line = f"export const {const.name} = {const.value};"
            if const.inline:
                line = f"{line}  // {const.inline}"
            out.append(line)
        if group.trailing:
            out.append("")
            out.extend(_comment_lines(clean_edges(group.trailing)))
        out.append("")
    return "\n".join(out) + "\n"


def render_dts(text: str, groups: List[Group], header_name: str) -> str:
    """Render the TypeScript declarations (.d.ts) with exact literal types."""
    out = _banner(text, groups, header_name)
    for group in groups:
        out.append(f"// ===== {group.label} =====")
        for const in group.consts:
            out.append(f"export declare const {const.name}: {_dts_type(const)};")
        out.append("")
    return "\n".join(out) + "\n"


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog="gen_js_protocol.py",
        description="Generate the JavaScript protocol constants (.js + .d.ts) from opendisplay_protocol.h.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="(re)generate and write the .js and .d.ts")
    mode.add_argument("--check", action="store_true", help="verify both files match (exit 1 on drift)")
    mode.add_argument("--stdout", action="store_true", help="print the .js module; write nothing")
    p.add_argument("--header", metavar="FILE", help=f"canonical header path (default: {DEFAULT_HEADER})")
    p.add_argument("--out-js", metavar="FILE", help=f"generated .js path (default: {DEFAULT_OUT_JS})")
    p.add_argument("--out-dts", metavar="FILE", help=f"generated .d.ts path (default: {DEFAULT_OUT_DTS})")
    args = p.parse_args(argv)

    header_path = Path(args.header) if args.header else DEFAULT_HEADER
    js_path = Path(args.out_js) if args.out_js else DEFAULT_OUT_JS
    dts_path = Path(args.out_dts) if args.out_dts else DEFAULT_OUT_DTS
    if not header_path.is_file():
        die(f"canonical header not found: {header_path}")

    text = header_path.read_text(encoding="utf-8")
    groups = parse_header(text)
    if not groups:
        die(f"no constants parsed from {header_path}")
    js = render_js(text, groups, header_path.name)
    dts = render_dts(text, groups, header_path.name)

    if args.stdout:
        sys.stdout.write(js)
        return 0

    failed = False
    for path, content in ((js_path, js), (dts_path, dts)):
        ok, message = reconcile(path, content, write=args.write, regen_cmd=REGEN_CMD)
        if args.write:
            print(message)
        else:
            print(message, file=sys.stdout if ok else sys.stderr)
        failed = failed or not ok
    if args.write:
        count = sum(len(g.consts) for g in groups)
        print(f"({count} constants -> .js + .d.ts)")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
