#!/usr/bin/env python3
"""Generate the Python protocol constants module from opendisplay_protocol.h.

The C header `src/opendisplay_protocol.h` is the single source of truth for every
value on the OpenDisplay BLE wire. Firmware repos vendor it byte-for-byte
(`sync_protocol_header.py`); Python cannot `#include` a C header, so this tool
GENERATES the equivalent Python module and CI verifies it has not drifted -- the
cross-language analog of the firmware `--check`. Parsing is done by the shared
`protocol_model` (also used by gen_js_protocol.py); this file is only the renderer.

CANONICAL SOURCE
    opendisplay-protocol/src/opendisplay_protocol.h   (macro-only, `u`-suffixed)

GENERATED ARTIFACT
    opendisplay-protocol/src/opendisplay_protocol.py  (flat `Final` constants)

WHY FLAT CONSTANTS, NOT ONE IntEnum
    The header deliberately reuses byte values across distinct names (0x73 is both
    RESP_LED_ACTIVATE_ACK and RESP_DIRECT_WRITE_REFRESH_SUCCESS; 0xFF is both
    RESP_NACK and RESP_DIRECT_WRITE_ERROR). In an IntEnum the second member with a
    duplicate value becomes a silent ALIAS of the first, erasing a name. Module-level
    `Final` constants preserve every name and value faithfully.

USAGE
    tools/gen_python_protocol.py --write         # (re)generate src/opendisplay_protocol.py
    tools/gen_python_protocol.py --check          # verify it matches (exit 1 on drift)
    tools/gen_python_protocol.py --stdout         # print generated module, write nothing
    tools/gen_python_protocol.py --header FILE --out FILE   # explicit paths

EXIT CODES
    0  success / in sync
    1  drift, missing file, or a value the parser cannot classify

Stdlib only; no third-party dependencies. Python 3.8+.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Optional

from protocol_model import Group, clean_edges, die, parse_header, protocol_version, reconcile, source_sha

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_HEADER = REPO_ROOT / "src" / "opendisplay_protocol.h"
DEFAULT_OUT = REPO_ROOT / "src" / "opendisplay_protocol.py"
REGEN_CMD = "tools/gen_python_protocol.py --write"


def _comment_lines(doc: List[str]) -> List[str]:
    """Render cleaned doc lines as Python comments (bare `#` for blank lines)."""
    return [("#" if line == "" else f"# {line}") for line in doc]


def render_module(text: str, groups: List[Group], header_name: str) -> str:
    """Render the generated Python module as a string (deterministic, no timestamp)."""
    sha = source_sha(text)
    version = protocol_version(groups)
    names = [c.name for g in groups for c in g.consts]

    out: List[str] = []
    out.append("# @generated by tools/gen_python_protocol.py -- DO NOT EDIT BY HAND.")
    out.append(f"# Source: {header_name} (OD_PROTOCOL_VERSION {version})")
    out.append(f"# Source SHA-256: {sha}")
    out.append(f"# Regenerate: {REGEN_CMD}   (CI drift gate: --check)")
    out.append('"""OpenDisplay BLE wire-protocol constants.')
    out.append("")
    out.append(f"Generated from the canonical {header_name} (protocol v{version}). Every")
    out.append("value here travels on the OpenDisplay BLE wire. Do not hand-edit; edit the")
    out.append("header and regenerate. Constants are flat (not an IntEnum) because the wire")
    out.append("intentionally reuses byte values across distinct names -- an enum would alias")
    out.append("and hide one. NACK error codes are opcode-SCOPED: decode data[0] only in the")
    out.append('scope of the echoed opcode (see the header for the full contract)."""')
    out.append("")
    out.append("from typing import Final")
    out.append("")

    for group in groups:
        out.append(f"# ===== {group.label} =====")
        if group.intro:
            out.extend(_comment_lines(group.intro))
        out.append("")
        for idx, const in enumerate(group.consts):
            if const.doc and idx > 0:
                out.append("")  # breathing room between documented constants
            out.extend(_comment_lines(const.doc))
            line = f"{const.name}: Final = {const.value}"
            if const.inline:
                line = f"{line}  # {const.inline}"
            out.append(line)
        if group.trailing:
            out.append("")
            out.extend(_comment_lines(clean_edges(group.trailing)))
        out.append("")

    out.append("__all__ = [")
    for name in names:
        out.append(f'    "{name}",')
    out.append("]")
    return "\n".join(out) + "\n"


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog="gen_python_protocol.py",
        description="Generate the Python protocol constants module from opendisplay_protocol.h.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="(re)generate and write the module")
    mode.add_argument("--check", action="store_true", help="verify the module matches (exit 1 on drift)")
    mode.add_argument("--stdout", action="store_true", help="print the generated module; write nothing")
    p.add_argument("--header", metavar="FILE", help=f"canonical header path (default: {DEFAULT_HEADER})")
    p.add_argument("--out", metavar="FILE", help=f"generated module path (default: {DEFAULT_OUT})")
    args = p.parse_args(argv)

    header_path = Path(args.header) if args.header else DEFAULT_HEADER
    out_path = Path(args.out) if args.out else DEFAULT_OUT
    if not header_path.is_file():
        die(f"canonical header not found: {header_path}")

    text = header_path.read_text(encoding="utf-8")
    groups = parse_header(text)
    if not groups:
        die(f"no constants parsed from {header_path}")
    generated = render_module(text, groups, header_path.name)

    if args.stdout:
        sys.stdout.write(generated)
        return 0

    ok, message = reconcile(out_path, generated, write=args.write, regen_cmd=REGEN_CMD)
    if args.write:
        count = sum(len(g.consts) for g in groups)
        print(f"{message} ({count} constants)")
        return 0
    print(message, file=sys.stdout if ok else sys.stderr)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
