// @generated by tools/gen_js_structs.py -- DO NOT EDIT BY HAND.
// Source: opendisplay_structs.h (OD_STRUCTS_VERSION 2.0)
// Source SHA-256: 238ada72ffc12ea242428547884d141f94e048cb6d6e01ceeb937dbdea50cfe7
// Regenerate: tools/gen_js_structs.py --write   (CI drift gate: --check)
//
// OpenDisplay BLE payload structs, enums, and bitfields. Every layout describes bytes
// that travel on the OpenDisplay BLE wire. Dependency-free ESM for browser + Node.
// Byte order is LITTLE-ENDIAN by default; the big-endian exceptions
// (WifiConfig.server_port and all of PartialWriteStartHeader) are honored per-field by
// each struct's pack()/unpack() via DataView. Value enums are frozen name->value
// objects; bitfield flags are flat `export const` (protocol.js style). Cross-header
// names (OD_NFC_IC_*, PIPE_FLAG_*) live in opendisplay_protocol.js and are referenced,
// never redefined here.

// ===== Loose wire constants =====

export const OD_STRUCTS_VERSION_MAJOR = 2;
export const OD_STRUCTS_VERSION_MINOR = 0;
export const OD_STRUCTS_VERSION_STR = "2.0";
export const OD_CONFIG_VERSION = 1;  // outer-packet major version byte
export const OD_CONFIG_MINOR_VERSION = 4;  // config-format minor; backward-compatible additions
export const OD_CONFIG_CRC_POLY = 0x1021;  // CRC16-CCITT polynomial
export const OD_CONFIG_CRC_INIT = 0xFFFF;  // CRC16-CCITT initial value
export const OD_PIN_UNUSED = 0xFF;  // pin field value meaning 'no pin'

// ===== Packed-struct runtime (generic wire (de)serialization) =====

/** Write an unsigned scalar of arbitrary byte `width` at `offset`, honoring `le`
 * (little-endian). Widths 1/2/4 use DataView; any other width (e.g. a 3-byte /
 * 24-bit field) uses a byte loop with safe-integer arithmetic (widths up to 6
 * bytes stay within Number.MAX_SAFE_INTEGER), for parity with the Python/Swift
 * mirrors which handle arbitrary widths. */
function _writeScalar(view, offset, width, value, le) {
  switch (width) {
    case 1: view.setUint8(offset, value & 0xff); return;
    case 2: view.setUint16(offset, value & 0xffff, le); return;
    case 4: view.setUint32(offset, value >>> 0, le); return;
    default: {
      let v = Math.trunc(value);
      for (let i = 0; i < width; i++) {
        view.setUint8(offset + (le ? i : width - 1 - i), v % 256);
        v = Math.floor(v / 256);
      }
      return;
    }
  }
}

/** Read an unsigned scalar of arbitrary byte `width` at `offset`, honoring `le`
 * (little-endian). Mirrors _writeScalar. */
function _readScalar(view, offset, width, le) {
  switch (width) {
    case 1: return view.getUint8(offset);
    case 2: return view.getUint16(offset, le);
    case 4: return view.getUint32(offset, le);
    default: {
      let v = 0;
      for (let i = 0; i < width; i++) {
        v = v * 256 + view.getUint8(offset + (le ? width - 1 - i : i));
      }
      return v;
    }
  }
}

/**
 * Base for every packed wire struct: pack()/unpack() driven by the subclass's static
 * SIZE + _FIELDS table. Each field is { name, offset, width, array, le }; array fields
 * round-trip raw Uint8Array bytes (zero-padded on pack), scalars round-trip integers
 * with per-field endianness.
 */
class _PackedStruct {
  /** Serialize to exactly SIZE wire bytes (arrays zero-padded; over-long arrays throw). */
  pack() {
    const ctor = this.constructor;
    const out = new Uint8Array(ctor.SIZE);
    const view = new DataView(out.buffer);
    for (const f of ctor._FIELDS) {
      const value = this[f.name];
      if (f.array) {
        const raw = value instanceof Uint8Array ? value : Uint8Array.from(value || []);
        if (raw.length > f.width) {
          throw new RangeError(`${ctor.name}.${f.name}: ${raw.length} bytes > ${f.width}`);
        }
        out.set(raw, f.offset); // remaining bytes stay zero (out is pre-zeroed)
      } else {
        _writeScalar(view, f.offset, f.width, Number(value) || 0, f.le);
      }
    }
    return out;
  }

  /** Deserialize SIZE wire bytes into an instance (extra trailing bytes ignored). */
  static unpack(data) {
    const bytes = data instanceof Uint8Array ? data : new Uint8Array(data);
    if (bytes.length < this.SIZE) {
      throw new RangeError(`${this.name}: need ${this.SIZE} bytes, got ${bytes.length}`);
    }
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    const obj = new this();
    for (const f of this._FIELDS) {
      obj[f.name] = f.array
        ? bytes.slice(f.offset, f.offset + f.width)
        : _readScalar(view, f.offset, f.width, f.le);
    }
    return obj;
  }
}

// ===== Value enums =====

/** Config TLV packet-type identifiers (SinglePacketHeader.id).  (on-wire width: 1 byte) */
export const ConfigPacketType = Object.freeze({
  /** system_config (required, singleton) */
  OD_PKT_SYSTEM: 1,
  /** manufacturer_data (required, singleton) */
  OD_PKT_MANUFACTURER: 2,
  /** power_option (required, singleton) */
  OD_PKT_POWER: 4,
  /** display (repeatable, max 4) */
  OD_PKT_DISPLAY: 32,
  /** led (repeatable, max 4) */
  OD_PKT_LED: 33,
  /** sensor_data (repeatable, max 4) */
  OD_PKT_SENSOR: 35,
  /** data_bus (repeatable, max 4) */
  OD_PKT_DATA_BUS: 36,
  /** binary_inputs (repeatable, max 4) */
  OD_PKT_BINARY_INPUT: 37,
  /** wifi_config (singleton) */
  OD_PKT_WIFI: 38,
  /** security_config (singleton) */
  OD_PKT_SECURITY: 39,
  /** touch_controller (repeatable, max 4) */
  OD_PKT_TOUCH: 40,
  /**
   * buzzer (repeatable, max 4). Canonical name is BUZZER (matches Silabs), resolving the
   * Silabs BUZZER vs NRF54/yaml PASSIVE_BUZZER split; config.yaml's packet name
   * (passive_buzzer) is regenerated to buzzer.
   */
  OD_PKT_BUZZER: 41,
  /** nfc_config (repeatable, max 2) */
  OD_PKT_NFC: 42,
  /** flash_config (repeatable, max 2) */
  OD_PKT_FLASH: 43,
  /** data_extended (singleton) */
  OD_PKT_DATA_EXTENDED: 44,
});

/**
 * GPIO active-level polarity. Bound from NfcConfig.field_detect_active,
 * NfcConfig.power_active, FlashConfig.power_active.  (on-wire width: 1 byte)
 */
export const ActiveLevel = Object.freeze({
  /** signal asserted / present when the pin is LOW */
  OD_ACTIVE_LOW: 0,
  /** signal asserted / present when the pin is HIGH */
  OD_ACTIVE_HIGH: 1,
});

/** Host MCU/IC of the device (SystemConfig.ic_type).  (on-wire width: 2 bytes) */
export const ICType = Object.freeze({
  /** nRF52840-based boards */
  OD_IC_TYPE_NRF52840: 1,
  /** ESP32-S3-based boards */
  OD_IC_TYPE_ESP32S3: 2,
  /** ESP32-C3-based boards */
  OD_IC_TYPE_ESP32C3: 3,
  /** ESP32-C6-based boards */
  OD_IC_TYPE_ESP32C6: 4,
  /** nRF52811-based boards */
  OD_IC_TYPE_NRF52811: 5,
  /** Silicon Labs EFR32BG22 boards */
  OD_IC_TYPE_EFR32BG22C222F352GM40: 6,
  /** Seeed XIAO nRF54L15 (Zephyr) */
  OD_IC_TYPE_NRF54L15: 7,
  /** Seeed XIAO nRF54LM20A (Zephyr) */
  OD_IC_TYPE_NRF54LM20: 8,
});

/**
 * Device manufacturer (ManufacturerData.manufacturer_id). Board-name tables (board_type)
 * are intentionally NOT enumerated here -- they live only in config.yaml; board_type stays
 * a raw u8 field.  (on-wire width: 2 bytes)
 */
export const ManufacturerId = Object.freeze({
  /** self-built / DIY devices */
  OD_MANUFACTURER_DIY: 0,
  /** Seeed Studio */
  OD_MANUFACTURER_SEEED: 1,
  /** Waveshare Electronics */
  OD_MANUFACTURER_WAVESHARE: 2,
  /** SOL */
  OD_MANUFACTURER_SOL: 3,
  /** OpenDisplay (free giveaways only) */
  OD_MANUFACTURER_OPENDISPLAY: 4,
});

/** Power source (PowerOption.power_mode).  (on-wire width: 1 byte) */
export const PowerMode = Object.freeze({
  /** battery powered */
  OD_POWER_MODE_BATTERY: 1,
  /** USB powered */
  OD_POWER_MODE_USB: 2,
  /** solar powered */
  OD_POWER_MODE_SOLAR: 3,
});

/**
 * Battery chemistry model for state-of-charge estimation (PowerOption.capacity_estimator).
 * (on-wire width: 1 byte)
 */
export const CapacityEstimator = Object.freeze({
  /** 1S Li-ion */
  OD_CAPACITY_EST_LI_ION: 1,
  /** 1S LiFePO4 */
  OD_CAPACITY_EST_LIFEPO4: 2,
  /** 2S supercapacitor (4.5 V max, 3.6 V cutoff) */
  OD_CAPACITY_EST_SUPERCAP: 3,
  /** lithium primary (non-rechargeable) */
  OD_CAPACITY_EST_LITHIUM_PRIMARY: 4,
  /** 1S Li-ion, Seeed reTerminal E-series discharge curve */
  OD_CAPACITY_EST_SEEED_LI_ION: 5,
});

/** Display technology (DisplayConfig.display_technology).  (on-wire width: 1 byte) */
export const DisplayTechnology = Object.freeze({
  /** undefined / unspecified */
  OD_DISPLAY_TECH_UNDEFINED: 0,
  /** e-paper / ESL */
  OD_DISPLAY_TECH_E_PAPER: 1,
  /** LCD */
  OD_DISPLAY_TECH_LCD: 2,
  /** LED-matrix display */
  OD_DISPLAY_TECH_LED_MATRIX: 3,
});

/** Physical panel rotation (DisplayConfig.rotation).  (on-wire width: 1 byte) */
export const Rotation = Object.freeze({
  /** 0 degrees */
  OD_ROTATION_0: 0,
  /** 90 degrees */
  OD_ROTATION_90: 1,
  /** 180 degrees */
  OD_ROTATION_180: 2,
  /** 270 degrees */
  OD_ROTATION_270: 3,
});

/**
 * Panel partial-update capability (DisplayConfig.partial_update_support).  (on-wire width:
 * 1 byte)
 */
export const PartialUpdateSupport = Object.freeze({
  /** only full updates supported */
  OD_PARTIAL_UPDATE_NONE: 0,
  /** partial updates supported */
  OD_PARTIAL_UPDATE_SUPPORTED: 1,
  /** partial supported but a full-frame stream is required */
  OD_PARTIAL_UPDATE_FULL_FRAME: 2,
});

/**
 * display color/plane scheme (DisplayConfig.color_scheme); drives plane count and pixel
 * packing.  (on-wire width: 1 byte)
 */
// @external mirror: epaper-dithering packages/rust/core/src/palettes.rs (integer values
// MUST match; the crate declares itself a firmware mirror). informed-by: bb_epaper. The
// value->plane/packing meaning is OpenDisplay-owned here.
export const ColorScheme = Object.freeze({
  /** 1bpp black/white */
  OD_COLOR_SCHEME_MONO: 0,
  /** black/white/red */
  OD_COLOR_SCHEME_BWR: 1,
  /** black/white/yellow */
  OD_COLOR_SCHEME_BWY: 2,
  /** black/white/red/yellow */
  OD_COLOR_SCHEME_BWRY: 3,
  /** Spectra 6-color (black/white/green/blue/red/yellow) */
  OD_COLOR_SCHEME_BWGBRY: 4,
  /** 2bpp 4-level gray */
  OD_COLOR_SCHEME_GRAY4: 5,
  /** 4bpp 16-level gray */
  OD_COLOR_SCHEME_GRAY16: 6,
  /**
   * 7-color (Spectra/ACeP 7, config.yaml '7color') (changed: 2.0: value 7 is SEVEN_COLOR;
   * the former COLOR_SCHEME_GRAY8=7 was a mistake (gray8 is not a real scheme) and is
   * removed -- not renumbered.)
   */
  OD_COLOR_SCHEME_SEVEN_COLOR: 7,
  /**
   * Spectra 6 nibbles, left-half plane then right-half plane (dual-CS panels, no device
   * framebuffer)
   */
  OD_COLOR_SCHEME_BWGBRY_SPLIT: 8,
  /** RGB565 (non-epaper) */
  OD_COLOR_SCHEME_RGB565: 100,
  /** RGB888 (non-epaper) */
  OD_COLOR_SCHEME_RGB888: 101,
  /** 16 bits per channel (non-epaper) */
  OD_COLOR_SCHEME_RGB16BPC: 102,
});

/**
 * display controller / panel type (DisplayConfig.panel_ic_type). Only representative
 * values are named here; the full list lives in config.yaml.  (on-wire width: 2 bytes)
 */
// @external bb_epaper (0-76 names track bb_epaper EP* panel identifiers); the 1000-1030
// range comes from the M3 / EPD-nRF5 driver line; 3000+ from the Seeed_GFX / OpenDisplay
// runtime. Wire values are OpenDisplay-OWNED; each firmware maps value -> its bb_epaper EP*
// constant via a repo-local opendisplay_epd_map.c (NOT part of this header; bb_epaper never
// dictates the wire values).
export const PanelIC = Object.freeze({
  /** undefined / unknown panel */
  OD_PANEL_IC_EP_PANEL_UNDEFINED: 0,
  /** WFT0420CZ15 4.2" B/W */
  OD_PANEL_IC_EP42_400X300: 1,
  /** DEPG0420BN / GDEY042T81 4.2" B/W */
  OD_PANEL_IC_EP42B_400X300: 2,
  /** Waveshare 2.13" */
  OD_PANEL_IC_EP213_122X250: 3,
  /** GDEY0213B74 (Inky pHAT 2.13" B/W newer) */
  OD_PANEL_IC_EP213B_122X250: 4,
  /** 128x296 panel */
  OD_PANEL_IC_EP293_128X296: 5,
  /** Waveshare newer 2.9" 1-bit 128x296 */
  OD_PANEL_IC_EP294_128X296: 6,
  /** harvested Solum 2.9" BW ESLs */
  OD_PANEL_IC_EP295_128X296: 7,
  /** 4-gray variant of EP295 */
  OD_PANEL_IC_EP295_128X296_4GRAY: 8,
  /** GDEY0266T90 */
  OD_PANEL_IC_EP266_152X296: 9,
  /** GDEW0102T4 */
  OD_PANEL_IC_EP102_80X128: 10,
  /** GDEY027T91 */
  OD_PANEL_IC_EP27B_176X264: 11,
  /** tricolor 2.9 panel */
  OD_PANEL_IC_EP29R_128X296: 12,
  /** GDEM0122T61 */
  OD_PANEL_IC_EP122_192X176: 13,
  /** 1.54" B/W/R */
  OD_PANEL_IC_EP154R_152X152: 14,
  /** 400x300 tricolor */
  OD_PANEL_IC_EP42R_400X300: 15,
  /** GDEQ042Z21 */
  OD_PANEL_IC_EP42R2_400X300: 16,
  /** GDEY037T03 */
  OD_PANEL_IC_EP37_240X416: 17,
  /** CROWPANEL 3.7" */
  OD_PANEL_IC_EP37B_240X416: 18,
  /** InkyPHAT 2.13 B/W */
  OD_PANEL_IC_EP213_104X212: 19,
  /** GDEY075T7 (older version) */
  OD_PANEL_IC_EP75_800X480: 20,
  /** GDEW075T7 (older) 4-gray mode */
  OD_PANEL_IC_EP75_800X480_4GRAY: 21,
  /** GDEY075T7 older panel, darker grays */
  OD_PANEL_IC_EP75_800X480_4GRAY_V2: 22,
  /** Pimoroni Badger2040 */
  OD_PANEL_IC_EP29_128X296: 23,
  /** Pimoroni Badger2040 4-gray */
  OD_PANEL_IC_EP29_128X296_4GRAY: 24,
  /** Inky pHAT 2.13 B/W/R */
  OD_PANEL_IC_EP213R_122X250: 25,
  /** Waveshare 2.0" B/W */
  OD_PANEL_IC_EP154_200X200: 26,
  /** DEPG01540BN */
  OD_PANEL_IC_EP154B_200X200: 27,
  /** GDEY0266F51 */
  OD_PANEL_IC_EP266YR_184X360: 28,
  /** GDEY029F51 */
  OD_PANEL_IC_EP29YR_128X296: 29,
  /** GDEY029F51H */
  OD_PANEL_IC_EP29YR_168X384: 30,
  /** DEPG0583BN */
  OD_PANEL_IC_EP583_648X480: 31,
  /** Waveshare 2.9" 128x296 B/W V2 */
  OD_PANEL_IC_EP296_128X296: 32,
  /** Solum 2.6" B/W/R */
  OD_PANEL_IC_EP26R_152X296: 33,
  /** GEDY073D46 (slower, EOL 7-color) */
  OD_PANEL_IC_EP73_800X480: 34,
  /** Spectra 6/7-color 800x480 */
  OD_PANEL_IC_EP73_SPECTRA_800X480: 35,
  /** 640x384 panel */
  OD_PANEL_IC_EP74R_640X384: 36,
  /** 4-bits-per-pixel 5.83" panel */
  OD_PANEL_IC_EP583R_600X448: 37,
  /** Waveshare 800x480 3-color */
  OD_PANEL_IC_EP75R_800X480: 38,
  /** Waveshare 4.26" B/W 800x480 */
  OD_PANEL_IC_EP426_800X480: 39,
  /** 4.26" 2-bit grayscale mode */
  OD_PANEL_IC_EP426_800X480_4GRAY: 40,
  /** Adafruit 2.9" Tricolor FeatherWing */
  OD_PANEL_IC_EP29R2_128X296: 41,
  /** EInk ED040TC1 SPI UC81xx */
  OD_PANEL_IC_EP41_640X400: 42,
  /** Spectra 8.1" 1024x576 6-color */
  OD_PANEL_IC_EP81_SPECTRA_1024X576: 43,
  /** ED070EC1 */
  OD_PANEL_IC_EP7_960X640: 44,
  /** UC8151 3-color 2.13" */
  OD_PANEL_IC_EP213R2_122X250: 45,
  /** SSD1680 (CrowPanel 2.9") */
  OD_PANEL_IC_EP29Z_128X296: 46,
  /** SSD1680 4-gray */
  OD_PANEL_IC_EP29Z_128X296_4GRAY: 47,
  /** SSD1680 CrowPanel 2.13" */
  OD_PANEL_IC_EP213Z_122X250: 48,
  /** CrowPanel 2.13" 4-gray mode */
  OD_PANEL_IC_EP213Z_122X250_4GRAY: 49,
  /** CrowPanel 1.54" */
  OD_PANEL_IC_EP154Z_152X152: 50,
  /** CrowPanel 5.79" */
  OD_PANEL_IC_EP579_792X272: 51,
  /** GDEY0213F52 */
  OD_PANEL_IC_EP213YR_122X250: 52,
  /** GDEM037F51 */
  OD_PANEL_IC_EP37YR_240X416: 53,
  /** GDEM035F51 */
  OD_PANEL_IC_EP35YR_184X384: 54,
  /** GDEM0397F81 */
  OD_PANEL_IC_EP397YR_800X480: 55,
  /** GDEM0154F51H */
  OD_PANEL_IC_EP154YR_200X200: 56,
  /** GDEY0266F52H */
  OD_PANEL_IC_EP266YR2_184X360: 57,
  /** GDEM042F52 */
  OD_PANEL_IC_EP42YR_400X300: 58,
  /** GEDY075-D2 (Waveshare/Xiao V2 panels) */
  OD_PANEL_IC_EP75_800X480_GEN2: 59,
  /** GDEY075T7-D2 (newer) 4-gray mode */
  OD_PANEL_IC_EP75_800X480_4GRAY_GEN2: 60,
  /** Waveshare 2.15" 4-color */
  OD_PANEL_IC_EP215YR_160X296: 61,
  /** GDEM1085T51 */
  OD_PANEL_IC_EP1085_1360X480: 62,
  /** GDEQ031T10 LilyGo T-Deck Pro */
  OD_PANEL_IC_EP31_240X320: 63,
  /** EP75YR 800x480 7-color */
  OD_PANEL_IC_EP75YR_800X480: 64,
  /**
   * T133A01 Spectra 6 13.3" dual-controller (Seeed reTerminal E1004). config.yaml catches
   * up (it skips 65-66 today); value 65 stays reserved.
   */
  OD_PANEL_IC_EP133A_SPECTRA_1200X1600: 66,
  /** Waveshare 1.54" 4-gray */
  OD_PANEL_IC_EP154_200X200_4GRAY: 67,
  /** DEPG0420BN / GDEY042T81 4-gray */
  OD_PANEL_IC_EP42B_400X300_4GRAY: 68,
  /** GDEM0397T81P */
  OD_PANEL_IC_EP397_800X480: 69,
  /** GDEM0397T81P 4-gray */
  OD_PANEL_IC_EP397_800X480_4GRAY: 70,
  /** xteink X3 3.68" B/W */
  OD_PANEL_IC_EP368_792X528: 71,
  /** xteink X3 3.68" 4-gray */
  OD_PANEL_IC_EP368_792X528_4GRAY: 72,
  /** LilyGo T3S3 2.13" */
  OD_PANEL_IC_EP213ZZ_122X250: 73,
  /** GDEP040E01 Spectra 6 4" 400x600 */
  OD_PANEL_IC_EP40_SPECTRA_400X600: 74,
  /** Badger2350 B/W 2.7" */
  OD_PANEL_IC_EP27_176X264: 75,
  /** Badger2350 4-gray 2.7" */
  OD_PANEL_IC_EP27_176X264_4GRAY: 76,
  /** UC8176 4.2" B/W (M3 / EPD-nRF5 driver line, values 1000-1030) */
  OD_PANEL_IC_UC8176_420_BW: 1000,
  /** SSD1619 4.2" B/W/R */
  OD_PANEL_IC_SSD1619_420_BWR: 1001,
  /** UC8176 4.2" B/W/R */
  OD_PANEL_IC_UC8176_420_BWR: 1002,
  /** SSD1619 4.2" B/W */
  OD_PANEL_IC_SSD1619_420_BW: 1003,
  /** JD79668 4.2" B/W/R/Y */
  OD_PANEL_IC_JD79668_420_BWRY: 1004,
  /** UC8179 7.5" B/W */
  OD_PANEL_IC_UC8179_750_BW: 1005,
  /** UC8179 7.5" B/W/R */
  OD_PANEL_IC_UC8179_750_BWR: 1006,
  /** UC8159 7.5" Low Power B/W */
  OD_PANEL_IC_UC8159_750_LOW_BW: 1007,
  /** UC8159 7.5" Low Power B/W/R */
  OD_PANEL_IC_UC8159_750_LOW_BWR: 1008,
  /** SSD1677 7.5" HD B/W */
  OD_PANEL_IC_SSD1677_750_HD_BW: 1009,
  /** SSD1677 7.5" HD B/W/R */
  OD_PANEL_IC_SSD1677_750_HD_BWR: 1010,
  /** JD79665 7.5" B/W/R/Y */
  OD_PANEL_IC_JD79665_750_BWRY: 1011,
  /** JD79665 5.83" B/W/R/Y */
  OD_PANEL_IC_JD79665_583_BWRY: 1012,
  /** UC8151 2.9" 168x384 B/W */
  OD_PANEL_IC_UC8151_029_BW: 1013,
  /** UC8151 2.9" 168x384 B/W/R */
  OD_PANEL_IC_UC8151_029_BWR: 1014,
  /** SSD1619 2.9" 168x384 B/W */
  OD_PANEL_IC_SSD1619_029_BW: 1015,
  /** SSD1619 2.9" 168x384 B/W/R */
  OD_PANEL_IC_SSD1619_029_BWR: 1016,
  /** SSD1619 1.6" 200x200 B/W */
  OD_PANEL_IC_SSD1619_016_BW: 1017,
  /** SSD1619 1.6" 200x200 B/W/R */
  OD_PANEL_IC_SSD1619_016_BWR: 1018,
  /** SSD1619 2.2" 240x320 B/W */
  OD_PANEL_IC_SSD1619_022_BW: 1019,
  /** SSD1619 2.2" 240x320 B/W/R */
  OD_PANEL_IC_SSD1619_022_BWR: 1020,
  /** SSD1619 2.6" 296x152 B/W */
  OD_PANEL_IC_SSD1619_026_BW: 1021,
  /** SSD1619 2.6" 296x152 B/W/R */
  OD_PANEL_IC_SSD1619_026_BWR: 1022,
  /** UC8151 2.7" 200x300 B/W */
  OD_PANEL_IC_UC8151_027_BW: 1023,
  /** UC8151 2.7" 200x300 B/W/R */
  OD_PANEL_IC_UC8151_027_BWR: 1024,
  /** UC variant 4.3" 152x522 B/W */
  OD_PANEL_IC_UC43_430_BW: 1025,
  /** UC variant 4.3" 152x522 B/W/R */
  OD_PANEL_IC_UC43_430_BWR: 1026,
  /** SSD1619 1.3" 144x200 B/W */
  OD_PANEL_IC_SSD1619_013_BW: 1027,
  /** SSD1619 1.3" 144x200 B/W/R */
  OD_PANEL_IC_SSD1619_013_BWR: 1028,
  /** SSD1619 M3 Lite 2.2" 250x128 B/W */
  OD_PANEL_IC_SSD1619_022_LITE_BW: 1029,
  /** SSD1619 M3 Lite 2.2" 250x128 B/W/R */
  OD_PANEL_IC_SSD1619_022_LITE_BWR: 1030,
  /**
   * E Ink ED103TC2 + IT8951 (Seeed 10.3", 1872x1404, 1bpp; Seeed_GFX/OpenDisplay runtime,
   * values 3000+)
   */
  OD_PANEL_IC_ED103TC2_1872X1404: 3000,
  /** same panel as 3000; 4bpp (16-level) */
  OD_PANEL_IC_ED103TC2_1872X1404_4GRAY: 3001,
});

/** LED wiring type (LedConfig.led_type).  (on-wire width: 1 byte) */
export const LedType = Object.freeze({
  /** RGB LED (3 channels) */
  OD_LED_TYPE_RGB: 0,
  /** single LED */
  OD_LED_TYPE_SINGLE: 1,
  /** red/yellow pair */
  OD_LED_TYPE_RY: 2,
  /** four separate LEDs */
  OD_LED_TYPE_FOUR_SEPARATE: 3,
});

/** Sensor / PMIC type (SensorData.sensor_type).  (on-wire width: 2 bytes) */
export const SensorType = Object.freeze({
  /** generic temperature sensor */
  OD_SENSOR_TYPE_TEMPERATURE: 1,
  /** generic humidity sensor */
  OD_SENSOR_TYPE_HUMIDITY: 2,
  /** AXP2101 power-management IC */
  OD_SENSOR_TYPE_AXP2101: 3,
  /**
   * Sensirion SHT40 (I2C); writes 3 LE bytes into MSD dynamic data (21 bits: 0.1C, 0.1%
   * RH)
   */
  OD_SENSOR_TYPE_SHT40: 4,
  /**
   * TI BQ27220 fuel gauge (I2C 0x55); voltage in MSD bytes 14-15, one packed dynamic byte
   * (bits 0-6 SOC%, bit7 charging)
   */
  OD_SENSOR_TYPE_BQ27220: 5,
});

/**
 * Bus protocol (DataBus.bus_type). Canonical replacement for the per-repo OD_BUS_TYPE_I2C
 * macro.  (on-wire width: 1 byte)
 */
export const BusType = Object.freeze({
  /** I2C bus */
  OD_BUS_TYPE_I2C: 1,
  /** SPI bus */
  OD_BUS_TYPE_SPI: 2,
});

/** Binary input hardware type (BinaryInputs.input_type).  (on-wire width: 1 byte) */
export const InputType = Object.freeze({
  /** momentary button */
  OD_INPUT_TYPE_BUTTON: 1,
  /** toggle switch */
  OD_INPUT_TYPE_SWITCH: 2,
});

/** How a UI should render the input (BinaryInputs.display_as).  (on-wire width: 1 byte) */
export const InputDisplayAs = Object.freeze({
  /** present as a button */
  OD_INPUT_DISPLAY_AS_BUTTON: 1,
  /** present as a switch */
  OD_INPUT_DISPLAY_AS_SWITCH: 2,
});

/** WiFi security (WifiConfig.encryption_type).  (on-wire width: 1 byte) */
export const WifiEncryptionType = Object.freeze({
  /** open network (no encryption) */
  OD_WIFI_ENC_NONE: 0,
  /** WEP */
  OD_WIFI_ENC_WEP: 1,
  /** WPA */
  OD_WIFI_ENC_WPA: 2,
  /** WPA2 */
  OD_WIFI_ENC_WPA2: 3,
  /** WPA3 */
  OD_WIFI_ENC_WPA3: 4,
});

/**
 * Touch controller IC (TouchController.touch_ic_type). Canonical replacement for the per-
 * repo TOUCH_IC_* macros.  (on-wire width: 2 bytes)
 */
export const TouchIcType = Object.freeze({
  /** disabled / no touch */
  OD_TOUCH_IC_NONE: 0,
  /** Goodix GT911 (I2C) */
  OD_TOUCH_IC_GT911: 1,
});

/** How NFC field presence is sensed (NfcConfig.field_detect_mode).  (on-wire width: 1 byte) */
export const NfcFieldDetectMode = Object.freeze({
  /** field-detect logic disabled */
  OD_NFC_FIELD_DETECT_DISABLED: 0,
  /** GPIO level sampled / polled */
  OD_NFC_FIELD_DETECT_GPIO_LEVEL: 1,
  /** interrupt-latched (reserved for future use) */
  OD_NFC_FIELD_DETECT_IRQ_LATCHED: 2,
});

/** External-flash IC type (FlashConfig.flash_ic_type).  (on-wire width: 1 byte) */
export const FlashIcType = Object.freeze({
  /** generic SPI-flash deep-sleep command flow */
  OD_FLASH_IC_AUTO: 0,
});

// ===== Bitfield groups =====
// Bit flags are flat `export const` (protocol.js style); reserved bits kept.

// SystemConfig.communication_modes @bits CommunicationModes (bits 3-7 reserved).
export const OD_COMM_MODE_BLE = 1 << 0;  // BLE transfer supported
export const OD_COMM_MODE_OEPL = 1 << 1;  // OEPL (OpenEPaperLink) transfer supported
export const OD_COMM_MODE_WIFI = 1 << 2;  // WiFi transfer supported

// SystemConfig.device_flags @bits DeviceFlags (bits 5-7 reserved).
export const OD_DEVICE_FLAG_PWR_PIN = 1 << 0;  // device has external power management for the display etc.
export const OD_DEVICE_FLAG_XIAO_INIT = 1 << 1;  // apply Seeed XIAO low-power init
export const OD_DEVICE_FLAG_WS_PP_INIT = 1 << 2;  // apply Waveshare PhotoPainter low-power init
export const OD_DEVICE_FLAG_PWR_LATCH = 1 << 3;  // self-holding MOSFET latch on pwr_pin_2; optional long-press shutdown button on pwr_pin_3
export const OD_DEVICE_FLAG_PWR_LATCH_DFF = 1 << 4;  // 74AHC1G79 D-FF latch: pwr_pin_2=D (hold), pwr_pin_3=CP (clock); command 0x0052 releases latch

// PowerOption.sleep_flags @bits SleepFlags (bits 1-7 reserved). Firmware ships bit0;
// config.yaml still lists it reserved_0 (yaml is behind).
export const OD_SLEEP_FLAG_BUTTON_WAKE_DISABLE = 1 << 0;  // opt out of button wake from timer deep sleep (buttons sharing wake-hostile pads)

// PowerOption.battery_sense_flags @bits BatterySenseFlags (bits 1-7 reserved). Firmware
// ships bit0; config.yaml still lists it reserved_0 (yaml is behind).
export const OD_BATTERY_SENSE_FLAG_ENABLE_INVERTED = 1 << 0;  // battery-sense enable is active-low (e.g. XIAO ~READ_BAT on P0.14)

// PowerOption.charger_flags @bits ChargerFlags (bits 2-7 reserved).
export const OD_CHARGER_FLAG_ENABLE_ACTIVE_LOW = 1 << 0;  // charge-enable (/CE) is active-low
export const OD_CHARGER_FLAG_STATE_ACTIVE_LOW = 1 << 1;  // charge-state (BQ25616 STAT) is active-low: charging when LOW

// DisplayConfig.transmission_modes @bits TransmissionModes (bits 5-6 reserved -- named as
// placeholders below; bit7 is defined above the gap).
export const OD_TRANSMISSION_MODE_STREAMING_DECOMPRESSION = 1 << 0;  // streaming zlib inflate, 512-byte DEFLATE window (requires zip). Canonical name resolves the Firmware/Silabs ZIPXL vs NRF54/yaml streaming_decompression split.
export const OD_TRANSMISSION_MODE_ZIP = 1 << 1;  // zip-compressed transfer (full window)
export const OD_TRANSMISSION_MODE_G5 = 1 << 2;  // Group 5 compression (not yet implemented)
export const OD_TRANSMISSION_MODE_DIRECT_WRITE = 1 << 3;  // direct-write mode (bufferless)
export const OD_TRANSMISSION_MODE_PIPE_WRITE = 1 << 4;  // PIPE-write mode: faster transfer via sliding-window pipeline
export const OD_TRANSMISSION_MODE_RESERVED_5 = 1 << 5;  // reserved; must be 0 (placeholder name for a future transmission mode)
export const OD_TRANSMISSION_MODE_RESERVED_6 = 1 << 6;  // reserved; must be 0 (placeholder name for a future transmission mode)
export const OD_TRANSMISSION_MODE_CLEAR_ON_BOOT = 1 << 7;  // Clear screen on boot. Synonymous with config.yaml's no_boot_text / NO_BOOT_TEXT -- same bit, same behavior (clearing on boot is why no boot text shows).

// LedConfig.led_flags @bits LedFlags (bits 4-7 reserved).
export const OD_LED_FLAG_LED1_INVERT = 1 << 0;  // invert LED channel 1 polarity
export const OD_LED_FLAG_LED2_INVERT = 1 << 1;  // invert LED channel 2 polarity
export const OD_LED_FLAG_LED3_INVERT = 1 << 2;  // invert LED channel 3 polarity
export const OD_LED_FLAG_LED4_INVERT = 1 << 3;  // invert LED channel 4 polarity

// Bitfield group BusFlags: DataBus.bus_flags @bits BusFlags -- all bits reserved today
// (must be 0).

// Bitfield group PinBitmap: DataBus.pullups / .pulldowns @bits PinBitmap: bit N-1 = pin N
// (pin_1..pin_7); bit 7 reserved. See the PinBitmap convention note above BinaryInputs.

// SecurityConfig.flags @bits SecurityFlags (bits 6-7 reserved).
export const OD_SECURITY_FLAG_REWRITE_ALLOWED = 1 << 0;  // allow unauthenticated config writes while encryption is enabled
export const OD_SECURITY_FLAG_SHOW_KEY_ON_SCREEN = 1 << 1;  // show the encryption key on screen (future feature)
export const OD_SECURITY_FLAG_RESET_PIN_ENABLED = 1 << 2;  // reset pin enabled (must be set for the reset pin to work)
export const OD_SECURITY_FLAG_RESET_PIN_POLARITY = 1 << 3;  // reset-pin polarity: 0 = LOW triggers, 1 = HIGH triggers
export const OD_SECURITY_FLAG_RESET_PIN_PULLUP = 1 << 4;  // enable pull-up on the reset pin
export const OD_SECURITY_FLAG_RESET_PIN_PULLDOWN = 1 << 5;  // enable pull-down on the reset pin

// TouchController.flags @bits TouchFlags (bits 3-7 reserved).
export const OD_TOUCH_FLAG_INVERT_X = 1 << 0;  // invert X using panel width
export const OD_TOUCH_FLAG_INVERT_Y = 1 << 1;  // invert Y using panel height
export const OD_TOUCH_FLAG_SWAP_XY = 1 << 2;  // swap X and Y before invert/clip

// BuzzerConfig.flags @bits BuzzerFlags (bits 1-7 reserved).
export const OD_BUZZER_FLAG_ENABLE_ACTIVE_HIGH = 1 << 0;  // enable pin is active-high when set; otherwise active-low

// NfcConfig.flags @bits NfcFlags (bits 1-7 reserved).
export const OD_NFC_FLAG_ENABLED = 1 << 0;  // must be set to enable NFC init (no fallback init if clear)

// FlashConfig.flags @bits FlashFlags (bits 1-7 reserved).
export const OD_FLASH_FLAG_ENABLED = 1 << 0;  // must be set to enable flash pin config / deep-sleep sequencing

// MsdAdvertisement.status @bits MsdStatusBits. bit0 is the 9th (MSB) bit of the 10-bit
// battery voltage; bits 4-7 are a free-running main-loop nibble counter.
export const OD_MSD_STATUS_BATTERY_VOLTAGE_BIT8 = 1 << 0;  // high bit of the 10-bit battery voltage (units of 10 mV); combine with battery_voltage_low
export const OD_MSD_STATUS_REBOOT_FLAG = 1 << 1;  // device rebooted since last read
export const OD_MSD_STATUS_CONNECTION_REQUESTED = 1 << 2;  // device is requesting a connection
export const OD_MSD_STATUS_RESERVED_3 = 1 << 3;  // reserved; must be 0 (placeholder name for a future status flag; sits between the flags and the bits 4-7 counter)
export const OD_MSD_STATUS_MAIN_LOOP_COUNTER_SHIFT = 4;  // bits 4-7: free-running main-loop nibble counter (liveness)
export const OD_MSD_STATUS_MAIN_LOOP_COUNTER_MASK = 0xF0;  // mask for the bits 4-7 main-loop counter nibble

// ===== Cross-header bindings (defined in opendisplay_protocol.js) =====
// @enum OD_NFC_IC_*: OD_NFC_IC_AUTO=0, OD_NFC_IC_TNB132M=1
// @bits PIPE_FLAG_*: PIPE_FLAG_COMPRESSED=1, PIPE_FLAG_PARTIAL=2

// ===== Packed structs =====

/**
 * Wraps the whole transfer: a length+version header, then a sequence of single_packet
 * entries, then a trailing CRC (NOT part of this struct -- it is the last 2 bytes of the
 * outer packet). FOLLOWUP: `length` is populated inconsistently (the website toolbox
 * patches it to the real total incl. CRC; some encoders leave it a zero pad -> [00
 * 00][version]...). The CRC is always computed as if `length` were 0x0000. Verify whether
 * any receiver relies on `length` before firmware depends on it.  [config packet outer]
 * (3 wire bytes.)
 */
export class OuterPacketHeader extends _PackedStruct {
  /**
   * total outer-packet length INCLUDING the trailing CRC. Inconsistently populated -- may
   * be a real total or a zero pad; the CRC is computed as if this were 0x0000 either way.
   */
  length = 0;
  /**
   * config-format MAJOR version = OD_CONFIG_VERSION (1). The minor is not carried in the
   * header.  [enum OD_CONFIG_VERSION]
   */
  version = 0;

  static SIZE = 3;
  static _FIELDS = [
    { name: "length", offset: 0, width: 2, array: false, le: true },
    { name: "version", offset: 2, width: 1, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Header preceding each config payload inside the outer packet. The payload that follows
 * is a fixed-size struct whose size and layout are determined entirely by `id` (see
 * ConfigPacketType); there is no per-packet length field -- sizeof the selected struct IS
 * the payload length.  [config packet single]  (2 wire bytes.)
 */
export class SinglePacketHeader extends _PackedStruct {
  /** 0-based sequential packet index within the outer packet. */
  number = 0;
  /** packet-type id selecting the payload struct.  [enum ConfigPacketType] */
  id = 0;

  static SIZE = 2;
  static _FIELDS = [
    { name: "number", offset: 0, width: 1, array: false, le: true },
    { name: "id", offset: 1, width: 1, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Host IC identity, communication capabilities, and power-management pins. Required
 * singleton. 22 bytes.  [config packet 0x01; required]  (22 wire bytes.)
 */
export class SystemConfig extends _PackedStruct {
  /** host MCU/IC of this device.  [enum ICType] */
  ic_type = 0;
  /** supported transfer modes (bitfield).  [bits CommunicationModes] */
  communication_modes = 0;
  /** misc device / power-latch flags (bitfield).  [bits DeviceFlags] */
  device_flags = 0;
  /** primary power-management pin; 0xFF = not present.  [default 0xFF] */
  pwr_pin = 0;
  /** future use; must be 0.  [reserved] */
  reserved = new Uint8Array();
  /** aux enable / battery-latch hold / pwr_latch_dff D input; 0 or 0xFF = firmware default. */
  pwr_pin_2 = 0;
  /**
   * aux enable / battery-latch shutdown button / pwr_latch_dff CP clock; 0 or 0xFF =
   * none/default.
   */
  pwr_pin_3 = 0;

  static SIZE = 22;
  static PACKET_ID = 0x01;
  static _FIELDS = [
    { name: "ic_type", offset: 0, width: 2, array: false, le: true },
    { name: "communication_modes", offset: 2, width: 1, array: false, le: true },
    { name: "device_flags", offset: 3, width: 1, array: false, le: true },
    { name: "pwr_pin", offset: 4, width: 1, array: false, le: true },
    { name: "reserved", offset: 5, width: 15, array: true, le: true },
    { name: "pwr_pin_2", offset: 20, width: 1, array: false, le: true },
    { name: "pwr_pin_3", offset: 21, width: 1, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Manufacturer id, board identity, and the 'simple config' preset indices the website UI
 * applied. Required singleton. 22 bytes.  [config packet 0x02; required]  (22 wire bytes.)
 */
export class ManufacturerData extends _PackedStruct {
  /** device manufacturer.  [enum ManufacturerId] */
  manufacturer_id = 0;
  /**
   * board identifier; meaning depends on manufacturer_id. Value table lives in config.yaml
   * only (NOT enumerated here) -- raw u8.
   */
  board_type = 0;
  /** board revision number. */
  board_revision = 0;
  /** simple-config driver preset index (1-based; 0 = not set). */
  simple_config_driver_index = 0;
  /** simple-config display preset index (1-based; 0 = not set). */
  simple_config_display_index = 0;
  /** simple-config power preset index (1-based; 0 = not set). */
  simple_config_power_index = 0;
  /**
   * 48-bit little-endian Unix time (seconds) when simple config was last applied.  [unit
   * s]
   */
  simple_config_configured_at = new Uint8Array();
  /** future use; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 22;
  static PACKET_ID = 0x02;
  static _FIELDS = [
    { name: "manufacturer_id", offset: 0, width: 2, array: false, le: true },
    { name: "board_type", offset: 2, width: 1, array: false, le: true },
    { name: "board_revision", offset: 3, width: 1, array: false, le: true },
    { name: "simple_config_driver_index", offset: 4, width: 2, array: false, le: true },
    { name: "simple_config_display_index", offset: 6, width: 2, array: false, le: true },
    { name: "simple_config_power_index", offset: 8, width: 2, array: false, le: true },
    { name: "simple_config_configured_at", offset: 10, width: 6, array: true, le: true },
    { name: "reserved", offset: 16, width: 6, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Power source, battery model, sleep/advertising timing, battery-sense and charger pins,
 * and EPD keep-alive. Required singleton. 30 bytes.  [config packet 0x04; required]  (30
 * wire bytes.)
 */
export class PowerOption extends _PackedStruct {
  /** power source type.  [enum PowerMode] */
  power_mode = 0;
  /** battery capacity, 24-bit LE; 0 = unknown.  [unit mAh] */
  battery_capacity_mah = new Uint8Array();
  /** nominal awake/advertising time before sleep (actual may be shorter).  [unit ms] */
  sleep_timeout_ms = 0;
  /** BLE transmit-power setting (platform-specific units). */
  tx_power = 0;
  /** sleep-related flags (bitfield).  [bits SleepFlags] */
  sleep_flags = 0;
  /** ADC pin measuring battery voltage; 0xFF = none.  [default 0xFF] */
  battery_sense_pin = 0;
  /** pin enabling the battery-sense divider; 0xFF = none.  [default 0xFF] */
  battery_sense_enable_pin = 0;
  /** battery-sense flags (bitfield).  [bits BatterySenseFlags] */
  battery_sense_flags = 0;
  /** battery chemistry model.  [enum CapacityEstimator] */
  capacity_estimator = 0;
  /** ADC voltage scaling / divider factor (implementation-specific). */
  voltage_scaling_factor = 0;
  /** board deep-sleep current excl. MCU; 0 = unknown.  [unit uA] */
  deep_sleep_current_ua = 0;
  /** timer deep-sleep duration (ESP32 on battery); 0 = disabled.  [unit s] */
  deep_sleep_time_seconds = 0;
  /** BQ25616 charge-enable GPIO; 0 or 0xFF = unused.  [default 0xFF] */
  charge_enable_pin = 0;
  /** BQ25616 charge-state input GPIO; 0 or 0xFF = unused.  [default 0xFF] */
  charge_state_pin = 0;
  /** charger polarity flags (bitfield).  [bits ChargerFlags] */
  charger_flags = 0;
  /** min awake window after first boot / button wake; 0 = default 120 s.  [unit s] */
  min_wake_time_seconds = 0;
  /**
   * EPD keep-alive: seconds the panel stays powered after a refresh before shutdown
   * (values >30 clamped; 0 = power off immediately; forced 0 when an AXP2101 PMIC is
   * present).  [unit s, min 0, max 30]
   */
  screen_timeout_seconds = 0;
  /** future use; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 30;
  static PACKET_ID = 0x04;
  static _FIELDS = [
    { name: "power_mode", offset: 0, width: 1, array: false, le: true },
    { name: "battery_capacity_mah", offset: 1, width: 3, array: true, le: true },
    { name: "sleep_timeout_ms", offset: 4, width: 2, array: false, le: true },
    { name: "tx_power", offset: 6, width: 1, array: false, le: true },
    { name: "sleep_flags", offset: 7, width: 1, array: false, le: true },
    { name: "battery_sense_pin", offset: 8, width: 1, array: false, le: true },
    { name: "battery_sense_enable_pin", offset: 9, width: 1, array: false, le: true },
    { name: "battery_sense_flags", offset: 10, width: 1, array: false, le: true },
    { name: "capacity_estimator", offset: 11, width: 1, array: false, le: true },
    { name: "voltage_scaling_factor", offset: 12, width: 2, array: false, le: true },
    { name: "deep_sleep_current_ua", offset: 14, width: 4, array: false, le: true },
    { name: "deep_sleep_time_seconds", offset: 18, width: 2, array: false, le: true },
    { name: "charge_enable_pin", offset: 20, width: 1, array: false, le: true },
    { name: "charge_state_pin", offset: 21, width: 1, array: false, le: true },
    { name: "charger_flags", offset: 22, width: 1, array: false, le: true },
    { name: "min_wake_time_seconds", offset: 23, width: 2, array: false, le: true },
    { name: "screen_timeout_seconds", offset: 25, width: 1, array: false, le: true },
    { name: "reserved", offset: 26, width: 4, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Per-panel configuration: geometry, controller, SPI pins, color scheme, and supported
 * transmission modes. Up to 4 instances. 46 bytes.  [config packet 0x20; repeatable (max
 * 4)]  (46 wire bytes.)
 */
export class DisplayConfig extends _PackedStruct {
  /** 0-based display index (unique per display block). */
  instance_number = 0;
  /** panel technology.  [enum DisplayTechnology] */
  display_technology = 0;
  /** display controller / panel type.  [enum PanelIC] */
  panel_ic_type = 0;
  /** panel pixel width.  [unit px] */
  pixel_width = 0;
  /** panel pixel height.  [unit px] */
  pixel_height = 0;
  /** active area width.  [unit mm] */
  active_width_mm = 0;
  /** active area height.  [unit mm] */
  active_height_mm = 0;
  /**
   * OEPL legacy tag type (optional; 0 if unused). Canonical snake_case of config.yaml
   * legacy_tagtype / firmware tag_type.
   */
  legacy_tag_type = 0;
  /** physical rotation.  [enum Rotation] */
  rotation = 0;
  /** panel reset GPIO; 0xFF = none.  [default 0xFF] */
  reset_pin = 0;
  /** panel busy-status GPIO; 0xFF = none.  [default 0xFF] */
  busy_pin = 0;
  /**
   * data/command select; doubles as SPI MISO on OpenDisplay-runtime IT8951 / Seeed ED103
   * panels.
   */
  dc_pin = 0;
  /** SPI chip-select; 0xFF = none.  [default 0xFF] */
  cs_pin = 0;
  /** data-out pin (SPI MOSI / data line). */
  data_pin = 0;
  /** partial-update capability.  [enum PartialUpdateSupport] */
  partial_update_support = 0;
  /** color/plane scheme.  [enum ColorScheme] */
  color_scheme = 0;
  /** supported image/data transmission modes (bitfield).  [bits TransmissionModes] */
  transmission_modes = 0;
  /** SPI SCLK pin. */
  clk_pin = 0;
  /**
   * second CS for panels split over 2 drivers (dual-controller Spectra); 0xFF = none.
   * Canonical name (firmware called it reserved_pin_2).  [default 0xFF, since 1.4]
   */
  cs_pin_2 = 0;
  /** spare pin; must be 0.  [reserved] */
  reserved_pin_3 = 0;
  /** spare pin; must be 0.  [reserved] */
  reserved_pin_4 = 0;
  /** spare pin; must be 0.  [reserved] */
  reserved_pin_5 = 0;
  /** spare pin; must be 0.  [reserved] */
  reserved_pin_6 = 0;
  /** spare pin; must be 0.  [reserved] */
  reserved_pin_7 = 0;
  /** spare pin; must be 0.  [reserved] */
  reserved_pin_8 = 0;
  /** energy consumed by a full refresh; 0 = unknown.  [unit mC] */
  full_update_mC = 0;
  /** future use; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 46;
  static PACKET_ID = 0x20;
  static _FIELDS = [
    { name: "instance_number", offset: 0, width: 1, array: false, le: true },
    { name: "display_technology", offset: 1, width: 1, array: false, le: true },
    { name: "panel_ic_type", offset: 2, width: 2, array: false, le: true },
    { name: "pixel_width", offset: 4, width: 2, array: false, le: true },
    { name: "pixel_height", offset: 6, width: 2, array: false, le: true },
    { name: "active_width_mm", offset: 8, width: 2, array: false, le: true },
    { name: "active_height_mm", offset: 10, width: 2, array: false, le: true },
    { name: "legacy_tag_type", offset: 12, width: 2, array: false, le: true },
    { name: "rotation", offset: 14, width: 1, array: false, le: true },
    { name: "reset_pin", offset: 15, width: 1, array: false, le: true },
    { name: "busy_pin", offset: 16, width: 1, array: false, le: true },
    { name: "dc_pin", offset: 17, width: 1, array: false, le: true },
    { name: "cs_pin", offset: 18, width: 1, array: false, le: true },
    { name: "data_pin", offset: 19, width: 1, array: false, le: true },
    { name: "partial_update_support", offset: 20, width: 1, array: false, le: true },
    { name: "color_scheme", offset: 21, width: 1, array: false, le: true },
    { name: "transmission_modes", offset: 22, width: 1, array: false, le: true },
    { name: "clk_pin", offset: 23, width: 1, array: false, le: true },
    { name: "cs_pin_2", offset: 24, width: 1, array: false, le: true },
    { name: "reserved_pin_3", offset: 25, width: 1, array: false, le: true },
    { name: "reserved_pin_4", offset: 26, width: 1, array: false, le: true },
    { name: "reserved_pin_5", offset: 27, width: 1, array: false, le: true },
    { name: "reserved_pin_6", offset: 28, width: 1, array: false, le: true },
    { name: "reserved_pin_7", offset: 29, width: 1, array: false, le: true },
    { name: "reserved_pin_8", offset: 30, width: 1, array: false, le: true },
    { name: "full_update_mC", offset: 31, width: 2, array: false, le: true },
    { name: "reserved", offset: 33, width: 13, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * LED channel pins + invert flags. Up to 4 instances. 22 bytes. NOTE: the 15-byte
 * reserved[] tail also carries the runtime LED flash pattern (bytes 0..11) written by
 * CMD_LED_ACTIVATE 0x0073 -- see struct LedFlashPattern.  [config packet 0x21; repeatable
 * (max 4)]  (22 wire bytes.)
 */
export class LedConfig extends _PackedStruct {
  /** 0-based LED-block index. */
  instance_number = 0;
  /** LED wiring type.  [enum LedType] */
  led_type = 0;
  /** channel 1 (red) pin; 0xFF = unused. */
  led_1_r = 0;
  /** channel 2 (green) pin; 0xFF = unused. */
  led_2_g = 0;
  /** channel 3 (blue) pin; 0xFF = unused. */
  led_3_b = 0;
  /** channel 4 pin (if present); 0xFF = unused. */
  led_4 = 0;
  /** per-channel invert flags (bitfield).  [bits LedFlags] */
  led_flags = 0;
  /**
   * future use; bytes 0..11 hold the runtime LedFlashPattern (see 0x0073). Must be 0 in a
   * fresh config.  [reserved]
   */
  reserved = new Uint8Array();

  static SIZE = 22;
  static PACKET_ID = 0x21;
  static _FIELDS = [
    { name: "instance_number", offset: 0, width: 1, array: false, le: true },
    { name: "led_type", offset: 1, width: 1, array: false, le: true },
    { name: "led_1_r", offset: 2, width: 1, array: false, le: true },
    { name: "led_2_g", offset: 3, width: 1, array: false, le: true },
    { name: "led_3_b", offset: 4, width: 1, array: false, le: true },
    { name: "led_4", offset: 5, width: 1, array: false, le: true },
    { name: "led_flags", offset: 6, width: 1, array: false, le: true },
    { name: "reserved", offset: 7, width: 15, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * A sensor bound to a data bus, with its MSD publish slot. Up to 4 instances. 30 bytes.
 * [config packet 0x23; repeatable (max 4)]  (30 wire bytes.)
 */
export class SensorData extends _PackedStruct {
  /** 0-based sensor-block index. */
  instance_number = 0;
  /** sensor type.  [enum SensorType] */
  sensor_type = 0;
  /** data_bus instance this sensor lives on. */
  bus_id = 0;
  /**
   * I2C 7-bit address; 0 or 0xFF = per-sensor default (SHT40 0x44, BQ27220 0x55).
   * [default 0xFF]
   */
  i2c_addr_7bit = 0;
  /**
   * first dynamicreturndata index this sensor publishes into. SHT40 uses 3 bytes (0/0xFF =
   * default 7); BQ27220 uses 1 packed byte (0xFF = do not publish).  [default 0xFF]
   */
  msd_data_start_byte = 0;
  /** future use; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 30;
  static PACKET_ID = 0x23;
  static _FIELDS = [
    { name: "instance_number", offset: 0, width: 1, array: false, le: true },
    { name: "sensor_type", offset: 1, width: 2, array: false, le: true },
    { name: "bus_id", offset: 3, width: 1, array: false, le: true },
    { name: "i2c_addr_7bit", offset: 4, width: 1, array: false, le: true },
    { name: "msd_data_start_byte", offset: 5, width: 1, array: false, le: true },
    { name: "reserved", offset: 6, width: 24, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * A shared I2C/SPI bus definition (pins, speed, pull config) other packets reference by
 * instance. Up to 4 instances. 30 bytes.  [config packet 0x24; repeatable (max 4)]  (30
 * wire bytes.)
 */
export class DataBus extends _PackedStruct {
  /** 0-based bus-block index; referenced by SensorData.bus_id, TouchController.bus_id, etc. */
  instance_number = 0;
  /** bus protocol.  [enum BusType] */
  bus_type = 0;
  /** pin 1 (SCL for I2C). */
  pin_1 = 0;
  /** pin 2 (SDA for I2C). */
  pin_2 = 0;
  /** pin 3 (aux / SPI). */
  pin_3 = 0;
  /** pin 4 (aux). */
  pin_4 = 0;
  /** pin 5 (aux). */
  pin_5 = 0;
  /** pin 6 (aux). */
  pin_6 = 0;
  /** pin 7 (aux). */
  pin_7 = 0;
  /** bus clock speed.  [unit Hz] */
  bus_speed_hz = 0;
  /** bus flags (all reserved today; must be 0).  [bits BusFlags] */
  bus_flags = 0;
  /** internal pull-ups, bit N-1 = pin N (pin_1..pin_7); bit 7 reserved.  [bits PinBitmap] */
  pullups = 0;
  /** internal pull-downs, bit N-1 = pin N (pin_1..pin_7); bit 7 reserved.  [bits PinBitmap] */
  pulldowns = 0;
  /** future use; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 30;
  static PACKET_ID = 0x24;
  static _FIELDS = [
    { name: "instance_number", offset: 0, width: 1, array: false, le: true },
    { name: "bus_type", offset: 1, width: 1, array: false, le: true },
    { name: "pin_1", offset: 2, width: 1, array: false, le: true },
    { name: "pin_2", offset: 3, width: 1, array: false, le: true },
    { name: "pin_3", offset: 4, width: 1, array: false, le: true },
    { name: "pin_4", offset: 5, width: 1, array: false, le: true },
    { name: "pin_5", offset: 6, width: 1, array: false, le: true },
    { name: "pin_6", offset: 7, width: 1, array: false, le: true },
    { name: "pin_7", offset: 8, width: 1, array: false, le: true },
    { name: "bus_speed_hz", offset: 9, width: 4, array: false, le: true },
    { name: "bus_flags", offset: 13, width: 1, array: false, le: true },
    { name: "pullups", offset: 14, width: 1, array: false, le: true },
    { name: "pulldowns", offset: 15, width: 1, array: false, le: true },
    { name: "reserved", offset: 16, width: 14, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Up to 8 button/switch pins per block, with per-pin used/invert/pull and long-press
 * power-off config. Up to 4 instances. 30 bytes. Field names are the canonical snake_case
 * (config.yaml inputpinN -> input_pin_N, isused -> pins_used; firmware called pins
 * reserved_pin_N).  [config packet 0x25; repeatable (max 4)]  (30 wire bytes.)
 */
export class BinaryInputs extends _PackedStruct {
  /** 0-based input-block index. */
  instance_number = 0;
  /** input hardware type.  [enum InputType] */
  input_type = 0;
  /** how to render the input.  [enum InputDisplayAs] */
  display_as = 0;
  /** input pin 1 GPIO; 0xFF = not configured.  [default 0xFF] */
  input_pin_1 = 0;
  /** input pin 2 GPIO; 0xFF = not configured.  [default 0xFF] */
  input_pin_2 = 0;
  /** input pin 3 GPIO; 0xFF = not configured.  [default 0xFF] */
  input_pin_3 = 0;
  /** input pin 4 GPIO; 0xFF = not configured.  [default 0xFF] */
  input_pin_4 = 0;
  /** input pin 5 GPIO; 0xFF = not configured.  [default 0xFF] */
  input_pin_5 = 0;
  /** input pin 6 GPIO; 0xFF = not configured.  [default 0xFF] */
  input_pin_6 = 0;
  /** input pin 7 GPIO; 0xFF = not configured.  [default 0xFF] */
  input_pin_7 = 0;
  /** input pin 8 GPIO; 0xFF = not configured.  [default 0xFF] */
  input_pin_8 = 0;
  /** which pins are active (bit N-1 = input_pin_N).  [bits PinBitmap] */
  pins_used = 0;
  /** per-pin logic invert (bit N-1 = input_pin_N).  [bits PinBitmap] */
  invert = 0;
  /** per-pin internal pull-up (bit N-1 = input_pin_N).  [bits PinBitmap] */
  pullups = 0;
  /** per-pin internal pull-down (bit N-1 = input_pin_N).  [bits PinBitmap] */
  pulldowns = 0;
  /**
   * dynamicreturndata index this block reports button state into (bounded integer, not an
   * enum). 0xFF = not published.  [min 0, max 10, default 0xFF]
   */
  button_data_byte_index = 0;
  /**
   * bit N-1 = input_pin_N triggers long-press power-off (latched devices only; ignored
   * otherwise).  [bits PinBitmap]
   */
  power_off_flags = 0;
  /** hold time before power-off; 0 = default 3 s (latched devices only).  [unit s] */
  power_off_hold_sec = 0;
  /** future use; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 30;
  static PACKET_ID = 0x25;
  static _FIELDS = [
    { name: "instance_number", offset: 0, width: 1, array: false, le: true },
    { name: "input_type", offset: 1, width: 1, array: false, le: true },
    { name: "display_as", offset: 2, width: 1, array: false, le: true },
    { name: "input_pin_1", offset: 3, width: 1, array: false, le: true },
    { name: "input_pin_2", offset: 4, width: 1, array: false, le: true },
    { name: "input_pin_3", offset: 5, width: 1, array: false, le: true },
    { name: "input_pin_4", offset: 6, width: 1, array: false, le: true },
    { name: "input_pin_5", offset: 7, width: 1, array: false, le: true },
    { name: "input_pin_6", offset: 8, width: 1, array: false, le: true },
    { name: "input_pin_7", offset: 9, width: 1, array: false, le: true },
    { name: "input_pin_8", offset: 10, width: 1, array: false, le: true },
    { name: "pins_used", offset: 11, width: 1, array: false, le: true },
    { name: "invert", offset: 12, width: 1, array: false, le: true },
    { name: "pullups", offset: 13, width: 1, array: false, le: true },
    { name: "pulldowns", offset: 14, width: 1, array: false, le: true },
    { name: "button_data_byte_index", offset: 15, width: 1, array: false, le: true },
    { name: "power_off_flags", offset: 16, width: 1, array: false, le: true },
    { name: "power_off_hold_sec", offset: 17, width: 1, array: false, le: true },
    { name: "reserved", offset: 18, width: 12, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * WiFi credentials plus optional upload server host/port. Singleton. 160 bytes. This
 * header is AHEAD of current firmware: server_host + server_port are promoted out of the
 * former reserved[95] (a backward-compatible carve -- the bytes were must-be-zero, so old
 * peers still interop; only a peer that writes a real port must honor the big-endian
 * server_port). NOTE server_port is the ONE big-endian field in this otherwise little-
 * endian struct.  [config packet 0x26]  (160 wire bytes.)
 */
export class WifiConfig extends _PackedStruct {
  /** WiFi SSID, null-terminated and zero-padded to 32 bytes. */
  ssid = new Uint8Array();
  /** WiFi password, null-terminated and zero-padded (empty for open networks). */
  password = new Uint8Array();
  /** network security type.  [enum WifiEncryptionType] */
  encryption_type = 0;
  /**
   * upload server URL/hostname, null-terminated and zero-padded to 64 bytes; empty = none.
   * Promoted out of reserved[].  [since 1.4]
   */
  server_host = new Uint8Array();
  /**
   * upload server TCP port, BIG-ENDIAN (the single BE field here). 0 = default/none.
   * Promoted out of reserved[] at former indices 64-65.  [BIG-ENDIAN, since 1.4]
   */
  server_port = 0;
  /** future use; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 160;
  static PACKET_ID = 0x26;
  static _FIELDS = [
    { name: "ssid", offset: 0, width: 32, array: true, le: true },
    { name: "password", offset: 32, width: 32, array: true, le: true },
    { name: "encryption_type", offset: 64, width: 1, array: false, le: true },
    { name: "server_host", offset: 65, width: 64, array: true, le: true },
    { name: "server_port", offset: 129, width: 2, array: false, le: false },
    { name: "reserved", offset: 131, width: 29, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Application-layer encryption master key and reset-pin config. Singleton. 64 bytes. The
 * AEAD envelope and auth handshake are specified in opendisplay_protocol.h; this packet
 * only stores the pre-shared key + policy.  [config packet 0x27]  (64 wire bytes.)
 */
export class SecurityConfig extends _PackedStruct {
  /**
   * 0 = disabled (all commands work unauthenticated); 1 = enabled (sensitive commands
   * require a session). If encryption_key is all-zero, encryption is off regardless.
   */
  encryption_enabled = 0;
  /** AES-128 master key (16 bytes). */
  encryption_key = new Uint8Array();
  /** session timeout; 0 = no timeout (persists until disconnect).  [unit s] */
  session_timeout_seconds = 0;
  /** security policy flags (bitfield).  [bits SecurityFlags] */
  flags = 0;
  /**
   * reset GPIO; when enabled and triggered, securely erases config and reboots.  [default
   * 0xFF]
   */
  reset_pin = 0;
  /** future use; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 64;
  static PACKET_ID = 0x27;
  static _FIELDS = [
    { name: "encryption_enabled", offset: 0, width: 1, array: false, le: true },
    { name: "encryption_key", offset: 1, width: 16, array: true, le: true },
    { name: "session_timeout_seconds", offset: 17, width: 2, array: false, le: true },
    { name: "flags", offset: 19, width: 1, array: false, le: true },
    { name: "reset_pin", offset: 20, width: 1, array: false, le: true },
    { name: "reserved", offset: 21, width: 43, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Capacitive touch controller on I2C (e.g. GT911). Publishes the first contact (5 bytes)
 * into MSD dynamic data. Up to 4 instances. 32 bytes.  [config packet 0x28; repeatable
 * (max 4)]  (32 wire bytes.)
 */
export class TouchController extends _PackedStruct {
  /** 0-based touch-block index. */
  instance_number = 0;
  /** touch controller IC.  [enum TouchIcType] */
  touch_ic_type = 0;
  /** data_bus instance for I2C; 0xFF means bus 0. */
  bus_id = 0;
  /** I2C 7-bit address (GT911 0x5D or 0x14); 0 or 0xFF = auto-detect.  [default 0xFF] */
  i2c_addr_7bit = 0;
  /** interrupt GPIO (active low); 0xFF = poll only.  [default 0xFF] */
  int_pin = 0;
  /** reset GPIO; 0xFF = skip hardware reset (probe only).  [default 0xFF] */
  rst_pin = 0;
  /** DisplayConfig index used for coordinate clip / invert reference. */
  display_instance = 0;
  /** coordinate mapping flags (bitfield).  [bits TouchFlags] */
  flags = 0;
  /** minimum time between polls; 0 = default 25 ms.  [unit ms] */
  poll_interval_ms = 0;
  /**
   * start index in dynamicreturndata for the 5-byte touch block (avoid overlap with
   * binary_inputs).  [min 0, max 6]
   */
  touch_data_start_byte = 0;
  /**
   * optional touch-panel power-enable GPIO (active high); 0 or 0xFF = unused.  [default
   * 0xFF]
   */
  enable_pin = 0;
  /** future use (e.g. GT911 register profile); must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 32;
  static PACKET_ID = 0x28;
  static _FIELDS = [
    { name: "instance_number", offset: 0, width: 1, array: false, le: true },
    { name: "touch_ic_type", offset: 1, width: 2, array: false, le: true },
    { name: "bus_id", offset: 3, width: 1, array: false, le: true },
    { name: "i2c_addr_7bit", offset: 4, width: 1, array: false, le: true },
    { name: "int_pin", offset: 5, width: 1, array: false, le: true },
    { name: "rst_pin", offset: 6, width: 1, array: false, le: true },
    { name: "display_instance", offset: 7, width: 1, array: false, le: true },
    { name: "flags", offset: 8, width: 1, array: false, le: true },
    { name: "poll_interval_ms", offset: 9, width: 1, array: false, le: true },
    { name: "touch_data_start_byte", offset: 10, width: 1, array: false, le: true },
    { name: "enable_pin", offset: 11, width: 1, array: false, le: true },
    { name: "reserved", offset: 12, width: 20, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Buzzer (passive piezo, PWM-driven). Up to 4 instances. 32 bytes. The tone PATTERN is not
 * stored here -- it is carried variable-length by CMD_BUZZER 0x0077
 * ([instance][outer_repeats][n_patterns] then per-pattern n_steps x (freq:u8,
 * duration:u8)); that payload stays prose-documented in opendisplay_protocol.h (it is
 * variable-length, so not modeled as a struct).  [config packet 0x29; repeatable (max 4)]
 * (32 wire bytes.)
 */
export class BuzzerConfig extends _PackedStruct {
  /** 0-based buzzer-block index. */
  instance_number = 0;
  /**
   * GPIO driving the PWM / square wave into the buzzer (via transistor). Pin encoding is
   * target-defined (e.g. nRF54 (port<<4)|pin).
   */
  drive_pin = 0;
  /** optional enable (e.g. FET); 0xFF = unused.  [default 0xFF] */
  enable_pin = 0;
  /** buzzer flags (bitfield).  [bits BuzzerFlags] */
  flags = 0;
  /** PWM duty cycle; 0 = default 50.  [min 1, max 100] */
  duty_percent = 0;
  /** future use (incl. internal frequency/time scaling); must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 32;
  static PACKET_ID = 0x29;
  static _FIELDS = [
    { name: "instance_number", offset: 0, width: 1, array: false, le: true },
    { name: "drive_pin", offset: 1, width: 1, array: false, le: true },
    { name: "enable_pin", offset: 2, width: 1, array: false, le: true },
    { name: "flags", offset: 3, width: 1, array: false, le: true },
    { name: "duty_percent", offset: 4, width: 1, array: false, le: true },
    { name: "reserved", offset: 5, width: 27, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * NFC IC selection, data bus, and optional field-detect GPIO that maps a button-like state
 * into the BLE advertisement. Up to 2 instances. 32 bytes.  [config packet 0x2A;
 * repeatable (max 2)]  (32 wire bytes.)
 */
export class NfcConfig extends _PackedStruct {
  /** 0-based NFC-block index. */
  instance_number = 0;
  /** NFC IC / flow selector.  [enum OD_NFC_IC] */
  nfc_ic_type = 0;
  /** data_bus instance (I2C) to use. */
  bus_instance = 0;
  /** NFC flags (bitfield); bit0 must be set to enable.  [bits NfcFlags] */
  flags = 0;
  /** field-detect input GPIO; 0xFF = disabled.  [default 0xFF] */
  field_detect_pin = 0;
  /** field-detect sensing mode.  [enum NfcFieldDetectMode] */
  field_detect_mode = 0;
  /** active level of field_detect_pin.  [enum ActiveLevel] */
  field_detect_active = 0;
  /** debounce time; 0 = no debounce.  [unit ms] */
  field_detect_debounce_ms = 0;
  /** NFC rail enable pin; 0xFF = use data_bus pin_3 if present, else none.  [default 0xFF] */
  power_pin = 0;
  /** power-pin polarity (reserved in current firmware).  [enum ActiveLevel] */
  power_active = 0;
  /** delay after enabling power before NFC access.  [unit ms] */
  power_on_delay_ms = 0;
  /** delay before power-off/park (reserved in current firmware).  [unit ms] */
  power_off_delay_ms = 0;
  /** dynamicreturndata index for the field-detect button-like state.  [min 0, max 10] */
  adv_button_byte_index = 0;
  /** 3-bit button id (stored in the lower bits) for the advertised state. */
  adv_button_button_id = 0;
  /** spare pin; must be 0.  [reserved] */
  reserved_pin_1 = 0;
  /** spare pin; must be 0.  [reserved] */
  reserved_pin_2 = 0;
  /** future NFC IC-specific extensions; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 32;
  static PACKET_ID = 0x2A;
  static _FIELDS = [
    { name: "instance_number", offset: 0, width: 1, array: false, le: true },
    { name: "nfc_ic_type", offset: 1, width: 1, array: false, le: true },
    { name: "bus_instance", offset: 2, width: 1, array: false, le: true },
    { name: "flags", offset: 3, width: 1, array: false, le: true },
    { name: "field_detect_pin", offset: 4, width: 1, array: false, le: true },
    { name: "field_detect_mode", offset: 5, width: 1, array: false, le: true },
    { name: "field_detect_active", offset: 6, width: 1, array: false, le: true },
    { name: "field_detect_debounce_ms", offset: 7, width: 1, array: false, le: true },
    { name: "power_pin", offset: 8, width: 1, array: false, le: true },
    { name: "power_active", offset: 9, width: 1, array: false, le: true },
    { name: "power_on_delay_ms", offset: 10, width: 1, array: false, le: true },
    { name: "power_off_delay_ms", offset: 11, width: 1, array: false, le: true },
    { name: "adv_button_byte_index", offset: 12, width: 1, array: false, le: true },
    { name: "adv_button_button_id", offset: 13, width: 1, array: false, le: true },
    { name: "reserved_pin_1", offset: 14, width: 1, array: false, le: true },
    { name: "reserved_pin_2", offset: 15, width: 1, array: false, le: true },
    { name: "reserved", offset: 16, width: 16, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * External SPI flash deep-sleep pin sequencing. Up to 2 instances. 32 bytes. Ignored when
 * the enabled flag is clear.  [config packet 0x2B; repeatable (max 2)]  (32 wire bytes.)
 */
export class FlashConfig extends _PackedStruct {
  /** 0-based flash-block index. */
  instance_number = 0;
  /** flash IC type (reserved for future).  [enum FlashIcType] */
  flash_ic_type = 0;
  /** reserved for future bus binding. */
  bus_instance = 0;
  /** flash flags (bitfield); bit0 must be set to enable.  [bits FlashFlags] */
  flags = 0;
  /** SPI MOSI pin (encoding target-defined, e.g. 0xPN). */
  mosi_pin = 0;
  /** SPI SCK pin. */
  sck_pin = 0;
  /** SPI CS pin. */
  cs_pin = 0;
  /** optional power-enable pin (reserved in current firmware).  [default 0xFF] */
  power_pin = 0;
  /** power-pin polarity (reserved in current firmware).  [enum ActiveLevel] */
  power_active = 0;
  /** power-on delay before first command (reserved).  [unit ms] */
  power_on_delay_ms = 0;
  /** power-off delay after command (reserved).  [unit ms] */
  power_off_delay_ms = 0;
  /** flash mode selector (reserved for future). */
  mode = 0;
  /** future flash extensions; must be 0.  [reserved] */
  reserved = new Uint8Array();

  static SIZE = 32;
  static PACKET_ID = 0x2B;
  static _FIELDS = [
    { name: "instance_number", offset: 0, width: 1, array: false, le: true },
    { name: "flash_ic_type", offset: 1, width: 1, array: false, le: true },
    { name: "bus_instance", offset: 2, width: 1, array: false, le: true },
    { name: "flags", offset: 3, width: 1, array: false, le: true },
    { name: "mosi_pin", offset: 4, width: 1, array: false, le: true },
    { name: "sck_pin", offset: 5, width: 1, array: false, le: true },
    { name: "cs_pin", offset: 6, width: 1, array: false, le: true },
    { name: "power_pin", offset: 7, width: 1, array: false, le: true },
    { name: "power_active", offset: 8, width: 1, array: false, le: true },
    { name: "power_on_delay_ms", offset: 9, width: 1, array: false, le: true },
    { name: "power_off_delay_ms", offset: 10, width: 1, array: false, le: true },
    { name: "mode", offset: 11, width: 1, array: false, le: true },
    { name: "reserved", offset: 12, width: 20, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * Extended device-identity strings. Singleton. 288 bytes = 9 fixed 32-byte fields. Each
 * field is a null-terminated, zero-padded UTF-8 string; default is the empty string (all
 * zeros).  [config packet 0x2C]  (288 wire bytes.)
 */
export class DataExtended extends _PackedStruct {
  /** manufacturer name (32-byte UTF-8, null-terminated, zero-padded). */
  manufacturer_name = new Uint8Array();
  /** model name. */
  model_name = new Uint8Array();
  /** serial number. */
  serial_number = new Uint8Array();
  /** human-friendly device name. */
  friendly_name = new Uint8Array();
  /** physical / logical location. */
  device_location = new Uint8Array();
  /** unique device identifier string. */
  device_id = new Uint8Array();
  /** user-defined string 1. */
  custom_string_1 = new Uint8Array();
  /** user-defined string 2. */
  custom_string_2 = new Uint8Array();
  /** user-defined string 3. */
  custom_string_3 = new Uint8Array();

  static SIZE = 288;
  static PACKET_ID = 0x2C;
  static _FIELDS = [
    { name: "manufacturer_name", offset: 0, width: 32, array: true, le: true },
    { name: "model_name", offset: 32, width: 32, array: true, le: true },
    { name: "serial_number", offset: 64, width: 32, array: true, le: true },
    { name: "friendly_name", offset: 96, width: 32, array: true, le: true },
    { name: "device_location", offset: 128, width: 32, array: true, le: true },
    { name: "device_id", offset: 160, width: 32, array: true, le: true },
    { name: "custom_string_1", offset: 192, width: 32, array: true, le: true },
    { name: "custom_string_2", offset: 224, width: 32, array: true, le: true },
    { name: "custom_string_3", offset: 256, width: 32, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * 12-byte LED flash program carried in CMD_LED_ACTIVATE 0x0073 after the led_instance
 * byte; firmware persists it into LedConfig.reserved[0..11]. Odd nibble packing is OEPL-
 * compatible -- do not 'fix' it. Three color/loop stages (1,2,3) each contribute a color
 * byte, a packed loop-delay/count byte, and an inter-loop delay byte.  [payload of
 * CMD_LED_ACTIVATE]  (12 wire bytes.)
 */
export class LedFlashPattern extends _PackedStruct {
  /**
   * low nibble = mode (1 = flash, 0 = off); high nibble = brightness minus 1 (0..15 ->
   * brightness 1..16).  [bitfield]
   */
  mode_brightness = 0;
  /** stage-1 color/channel byte. */
  color1 = 0;
  /**
   * high nibble = stage-1 loop delay (x100 ms); low nibble = stage-1 loop count.
   * [bitfield]
   */
  loop1_delay_count = 0;
  /** stage-1 inter-loop delay (x100 ms); 0 = none.  [unit ms] */
  inter_loop_delay1 = 0;
  /** stage-2 color/channel byte. */
  color2 = 0;
  /**
   * high nibble = stage-2 loop delay (x100 ms); low nibble = stage-2 loop count.
   * [bitfield]
   */
  loop2_delay_count = 0;
  /** stage-2 inter-loop delay (x100 ms); 0 = none.  [unit ms] */
  inter_loop_delay2 = 0;
  /** stage-3 color/channel byte. */
  color3 = 0;
  /**
   * high nibble = stage-3 loop delay (x100 ms); low nibble = stage-3 loop count.
   * [bitfield]
   */
  loop3_delay_count = 0;
  /** stage-3 inter-loop delay (x100 ms); 0 = none.  [unit ms] */
  inter_loop_delay3 = 0;
  /** group repeat count minus 1 (value 255 = repeat forever). */
  group_repeats = 0;
  /** must be 0.  [reserved] */
  reserved = 0;

  static SIZE = 12;
  static MESSAGE = "CMD_LED_ACTIVATE";
  static _FIELDS = [
    { name: "mode_brightness", offset: 0, width: 1, array: false, le: true },
    { name: "color1", offset: 1, width: 1, array: false, le: true },
    { name: "loop1_delay_count", offset: 2, width: 1, array: false, le: true },
    { name: "inter_loop_delay1", offset: 3, width: 1, array: false, le: true },
    { name: "color2", offset: 4, width: 1, array: false, le: true },
    { name: "loop2_delay_count", offset: 5, width: 1, array: false, le: true },
    { name: "inter_loop_delay2", offset: 6, width: 1, array: false, le: true },
    { name: "color3", offset: 7, width: 1, array: false, le: true },
    { name: "loop3_delay_count", offset: 8, width: 1, array: false, le: true },
    { name: "inter_loop_delay3", offset: 9, width: 1, array: false, le: true },
    { name: "group_repeats", offset: 10, width: 1, array: false, le: true },
    { name: "reserved", offset: 11, width: 1, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * 10-byte PIPE (0x0080) START header that follows the 2 opcode bytes (host->device). If
 * flags bit1 (PIPE_FLAG_PARTIAL) is set, a 12-byte PipePartialExt is appended (22 bytes
 * total after the opcode). NOTE: the plan inventory listed this as 8 bytes, but the field
 * list and protocol.h's '10-byte header (22 when partial)' both give 10 -- 10 is correct.
 * [payload of CMD_PIPE_WRITE_START]  (10 wire bytes.)
 */
export class PipeStartRequest extends _PackedStruct {
  /** PIPE protocol version = PIPE_VERSION (1). */
  version = 0;
  /** [bits PIPE_FLAG] */
  flags = 0;
  /** requested sliding-window size (frames).  [min 1, max 32] */
  req_window = 0;
  /** requested ACK cadence (frames per SACK).  [min 1, max 32] */
  req_ack_every = 0;
  /** largest on-wire frame the client will send. */
  client_max_frame = 0;
  /** decompressed byte total to transfer (partial: plane_size x 2). */
  total_size = 0;

  static SIZE = 10;
  static MESSAGE = "CMD_PIPE_WRITE_START";
  static _FIELDS = [
    { name: "version", offset: 0, width: 1, array: false, le: true },
    { name: "flags", offset: 1, width: 1, array: false, le: true },
    { name: "req_window", offset: 2, width: 1, array: false, le: true },
    { name: "req_ack_every", offset: 3, width: 1, array: false, le: true },
    { name: "client_max_frame", offset: 4, width: 2, array: false, le: true },
    { name: "total_size", offset: 6, width: 4, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * 12-byte partial-region extension appended to PipeStartRequest when PIPE_FLAG_PARTIAL is
 * set. LITTLE-endian twin of the 0x76 PartialWriteStartHeader geometry (which is big-
 * endian).  [payload of CMD_PIPE_WRITE_START]  (12 wire bytes.)
 */
export class PipePartialExt extends _PackedStruct {
  /** etag currently displayed; must match or the START is NACKed. */
  old_etag = 0;
  /** region left edge.  [unit px] */
  x = 0;
  /** region top edge.  [unit px] */
  y = 0;
  /** region width.  [unit px] */
  w = 0;
  /** region height.  [unit px] */
  h = 0;

  static SIZE = 12;
  static MESSAGE = "CMD_PIPE_WRITE_START";
  static _FIELDS = [
    { name: "old_etag", offset: 0, width: 4, array: false, le: true },
    { name: "x", offset: 4, width: 2, array: false, le: true },
    { name: "y", offset: 6, width: 2, array: false, le: true },
    { name: "w", offset: 8, width: 2, array: false, le: true },
    { name: "h", offset: 10, width: 2, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * 6-byte PIPE START ACK data (device->host): the device echoes its negotiated maxima (min-
 * rule applies against the client's request).  [payload of CMD_PIPE_WRITE_START]  (6 wire
 * bytes.)
 */
export class PipeStartResponse extends _PackedStruct {
  /** PIPE protocol version = PIPE_VERSION (1). */
  version = 0;
  /** device-granted maximum window size. */
  max_window = 0;
  /** device-granted maximum ACK cadence. */
  max_ack_every = 0;
  /** device-granted maximum frame size. */
  max_frame = 0;
  /** bit0 = selective-repeat supported; bit1 = partial accepted.  [bitfield] */
  resp_flags = 0;

  static SIZE = 6;
  static MESSAGE = "CMD_PIPE_WRITE_START";
  static _FIELDS = [
    { name: "version", offset: 0, width: 1, array: false, le: true },
    { name: "max_window", offset: 1, width: 1, array: false, le: true },
    { name: "max_ack_every", offset: 2, width: 1, array: false, le: true },
    { name: "max_frame", offset: 3, width: 2, array: false, le: true },
    { name: "resp_flags", offset: 5, width: 1, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * 5-byte selective-ACK data in the PIPE 0x0081 ACK frame (device->host). highest_seen is
 * implicitly acked; ack_mask bit i (LSB first) acks chunk (highest_seen - 1 - i).
 * [payload of CMD_PIPE_WRITE_DATA]  (5 wire bytes.)
 */
export class PipeSack extends _PackedStruct {
  /** highest received seq (mod 256), implicitly acked. */
  highest_seen = 0;
  /** selective-ACK bitmask below highest_seen (bit i = seq highest_seen-1-i). */
  ack_mask = 0;

  static SIZE = 5;
  static MESSAGE = "CMD_PIPE_WRITE_DATA";
  static _FIELDS = [
    { name: "highest_seen", offset: 0, width: 1, array: false, le: true },
    { name: "ack_mask", offset: 1, width: 4, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * 17-byte header for CMD_PARTIAL_WRITE_START 0x0076, following the 2 opcode bytes
 * (host->device). ENTIRELY BIG-ENDIAN -- the showcase for the per-message endianness
 * split: the PIPE 0x80 path carries the same geometry LITTLE-endian (see PipePartialExt).
 * x and width must be multiples of 8; old_etag must equal the currently displayed etag.
 * [payload of CMD_PARTIAL_WRITE_START]  (17 wire bytes.)
 */
export class PartialWriteStartHeader extends _PackedStruct {
  /** partial-write flags (see protocol.h 0x76 @request). */
  flags = 0;
  /** etag currently displayed; must match.  [BIG-ENDIAN] */
  old_etag = 0;
  /** etag to store after this write.  [BIG-ENDIAN] */
  new_etag = 0;
  /** region left edge (multiple of 8).  [unit px, BIG-ENDIAN] */
  x = 0;
  /** region top edge.  [unit px, BIG-ENDIAN] */
  y = 0;
  /** region width (multiple of 8).  [unit px, BIG-ENDIAN] */
  width = 0;
  /** region height.  [unit px, BIG-ENDIAN] */
  height = 0;

  static SIZE = 17;
  static MESSAGE = "CMD_PARTIAL_WRITE_START";
  static _FIELDS = [
    { name: "flags", offset: 0, width: 1, array: false, le: false },
    { name: "old_etag", offset: 1, width: 4, array: false, le: false },
    { name: "new_etag", offset: 5, width: 4, array: false, le: false },
    { name: "x", offset: 9, width: 2, array: false, le: false },
    { name: "y", offset: 11, width: 2, array: false, le: false },
    { name: "width", offset: 13, width: 2, array: false, le: false },
    { name: "height", offset: 15, width: 2, array: false, le: false },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * 21-byte CMD_AUTHENTICATE 0x0050 step-1 response DATA (device->host), after the
 * [status][echo] framing: the device's nonce + id the client signs. This handshake is
 * ALWAYS plaintext (bootstraps the session).  [payload of CMD_AUTHENTICATE]  (21 wire
 * bytes.)
 */
export class AuthChallenge extends _PackedStruct {
  /** auth status = AUTH_STATUS_CHALLENGE (0x00) on success (see protocol.h). */
  status = 0;
  /** device nonce; part of the CMAC input. */
  server_nonce = new Uint8Array();
  /** device id; part of the CMAC input. */
  device_id = 0;

  static SIZE = 21;
  static MESSAGE = "CMD_AUTHENTICATE";
  static _FIELDS = [
    { name: "status", offset: 0, width: 1, array: false, le: true },
    { name: "server_nonce", offset: 1, width: 16, array: true, le: true },
    { name: "device_id", offset: 17, width: 4, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * 32-byte CMD_AUTHENTICATE 0x0050 step-2 request payload (host->device): the client nonce
 * and the AES-CMAC over (server_nonce || client_nonce || device_id).  [payload of
 * CMD_AUTHENTICATE]  (32 wire bytes.)
 */
export class AuthProof extends _PackedStruct {
  /** client nonce; part of the CMAC input. */
  client_nonce = new Uint8Array();
  /** AES-CMAC(master_key, server_nonce || client_nonce || device_id). */
  mac = new Uint8Array();

  static SIZE = 32;
  static MESSAGE = "CMD_AUTHENTICATE";
  static _FIELDS = [
    { name: "client_nonce", offset: 0, width: 16, array: true, le: true },
    { name: "mac", offset: 16, width: 16, array: true, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}

/**
 * 16-byte OpenDisplay manufacturer-specific data. Broadcast in BLE advertisements and
 * returned by CMD_READ_MSD 0x0044 (device->host). Battery voltage is 10 bits (10 mV
 * units): the low 8 bits are battery_voltage_low, the 9th bit is status bit0; the 10th is
 * implied 0 / reserved by firmware.  [payload of CMD_READ_MSD]  (16 wire bytes.)
 */
export class MsdAdvertisement extends _PackedStruct {
  /** BLE company identifier. */
  company_id = 0;
  /**
   * config-driven dynamic area: button/touch/SHT40/BQ27220 slots at indices set by the
   * relevant config packets.
   */
  dynamic = new Uint8Array();
  /** MCU chip temperature (signed degrees C, firmware-defined offset).  [unit C] */
  chip_temperature = 0;
  /**
   * low 8 bits of the 10-bit battery voltage (10 mV units); high bit in status bit0.
   * [unit 10mV]
   */
  battery_voltage_low = 0;
  /** status flags + battery voltage MSB + main-loop counter nibble.  [bits MsdStatusBits] */
  status = 0;

  static SIZE = 16;
  static MESSAGE = "CMD_READ_MSD";
  static _FIELDS = [
    { name: "company_id", offset: 0, width: 2, array: false, le: true },
    { name: "dynamic", offset: 2, width: 11, array: true, le: true },
    { name: "chip_temperature", offset: 13, width: 1, array: false, le: true },
    { name: "battery_voltage_low", offset: 14, width: 1, array: false, le: true },
    { name: "status", offset: 15, width: 1, array: false, le: true },
  ];

  constructor(fields) {
    super();
    if (fields) Object.assign(this, fields);
  }
}
