// @generated by tools/gen_js_protocol.py -- DO NOT EDIT BY HAND.
// Source: opendisplay_protocol.h (OD_PROTOCOL_VERSION 2.0)
// Source SHA-256: 4af010db429244da834917f82ab7f161826a55d20f3b77a9f61bca35e38413ac
// Regenerate: tools/gen_js_protocol.py --write   (CI drift gate: --check)
//
// OpenDisplay BLE wire-protocol constants. Every value here travels on the wire.
// Flat `export const` (not a TS enum) because the wire reuses byte values across
// distinct names. NACK error codes are opcode-SCOPED: decode data[0] only in the
// scope of the echoed opcode (see the header for the full contract).

// ===== Protocol version =====

// Wire-protocol revision, MAJOR.MINOR. See VERSIONING POLICY in the banner for
// when to bump which number. This marker describes the spec and is NOT sent on
// the wire (the negotiated 0x0080 PIPE_VERSION is a separate field).
export const OD_PROTOCOL_VERSION_MAJOR = 2;
export const OD_PROTOCOL_VERSION_MINOR = 0;
export const OD_PROTOCOL_VERSION_STR = "2.0";

// ===== Section 1: COMMAND OPCODES (16-bit, big-endian on the wire) =====
// Config-packet-type bytes (the payload's first byte for CONFIG_WRITE TLVs)
// are NOT defined here -- they live in each repo's opendisplay_structs.h /
// opendisplay_constants.h and diverge per target. Comment-only reference:
//     0x01 system        0x02 manufacturer   0x04 power
//     0x20 display       0x21 led            0x23 sensor
//     0x24 data_bus      0x25 binary_inputs  0x26 wifi
//     0x27 security      0x28 touch          0x29 passive_buzzer
//     0x2A nfc           0x2B flash          0x2C data_extended

// @opcode: 0x000F   @name: CMD_REBOOT   @dir: host->device
// @request:  [0x00][0x0F]  (no payload)
// @response: none on most targets (immediate reset, BLE link drops). Silabs
//            may ACK before resetting; treat a dropped connection as success.
// @errors:   none
// @state:    if security enabled, session required (except on the no-ACK path).
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_REBOOT = 0x000F;

// @opcode: 0x0040   @name: CMD_CONFIG_READ   @dir: host->device
// @request:  [0x00][0x40]  (no payload)
// @response: one OR MORE notifications (chunked), each:
//              [0x00][0x40][chunk_number:2 LE][total_len:2 LE on chunk 0 only][data...]
//            chunk_number counts from 0; total_len (uint16 LE) is present ONLY
//            on chunk 0 and gives the full config byte length. Empty config
//            yields a single [0x00][0x40][0x00 0x00][0x00 0x00].
// @errors:   [0xFF][0x40][0x00][0x00] on storage-init failure.
// @state:    session required when security enabled.
// @limits:   each frame's data <= MAX_RESPONSE_DATA_SIZE (100) minus its header.
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_CONFIG_READ = 0x0040;

// @opcode: 0x0041   @name: CMD_CONFIG_WRITE   @dir: host->device
// @request:  single-frame (payload <= 200):  [0x00][0x41][config_data...]
//            chunked (payload  > 200):        [0x00][0x41][total:2 LE][first 200 data bytes]
//              -> the first frame MUST carry a FULL 200 data bytes (payload =
//                 2 + 200 = 202); a short first chunk makes firmware take the
//                 single-frame path and NACK the following 0x42 chunks.
//              -> remaining bytes follow as CMD_CONFIG_CHUNK (0x0042) frames.
// @response: [0x00][0x41] on accept (or after last chunk); [0xFF][0x41] on error.
// @errors:   NACK on malformed TLV, size overflow, or bad chunk sequencing.
// @state:    session required when security enabled. Device computes
//            expectedChunks = ceil(total / 200).
// @limits:   CONFIG_CHUNK_SIZE 200; first chunk payload CONFIG_CHUNK_SIZE_WITH_PREFIX 202.
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_CONFIG_WRITE = 0x0041;

// @opcode: 0x0042   @name: CMD_CONFIG_CHUNK   @dir: host->device
// @request:  [0x00][0x42][chunk_data...]  (up to 200 bytes; continuation of a
//            chunked CONFIG_WRITE started at 0x0041).
// @response: [0x00][0x42] per accepted chunk; final chunk commits + reloads
//            config. [0xFF][0x42] on overflow / no active write / bad total.
// @errors:   NACK if no active chunked write, or received > declared total.
// @state:    must follow a chunked 0x0041 START; count bounded by MAX_CONFIG_CHUNKS.
// @limits:   <= CONFIG_CHUNK_SIZE (200) data bytes.
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_CONFIG_CHUNK = 0x0042;

// @opcode: 0x0043   @name: CMD_FIRMWARE_VERSION   @dir: host->device
// @request:  [0x00][0x43]  (no payload)
// @response: [0x00][0x43][major:1][minor:1][... optional git/SHA string]
// @errors:   none
// @state:    ALWAYS PLAINTEXT (never encrypted) so version is readable pre-auth.
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_FIRMWARE_VERSION = 0x0043;

// @opcode: 0x0044   @name: CMD_READ_MSD   @dir: host->device
// @request:  [0x00][0x44]  (no payload)
// @response: [0x00][0x44][msd_bytes:16]  (manufacturer-specific data record).
// @errors:   none
// @state:    on Silabs this response is PLAINTEXT even with security enabled.
// @limits:   16 data bytes.
// @targets:  NRF54 | Silabs | NRF52811   (Firmware handles it but see repo)
export const CMD_READ_MSD = 0x0044;

// @opcode: 0x0045   @name: CMD_CONFIG_CLEAR   @dir: host->device
// @request:  [0x00][0x45]  (no payload)
// @response: [0x00][0x45] on success; [0xFF][0x45] on failure.
// @errors:   NACK if config storage erase fails.
// @state:    session required when security enabled.
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs      (NOT NRF52811)
export const CMD_CONFIG_CLEAR = 0x0045;

// @opcode: 0x0050   @name: CMD_AUTHENTICATE   @dir: host->device
// @request:  STEP 1 (request challenge):  [0x00][0x50][0x00]
//            STEP 2 (prove key):          [0x00][0x50][client_nonce:16][mac:16]
//              mac = AES-CMAC(master_key, server_nonce || client_nonce || device_id)
// @response: STEP 1 challenge (23 bytes): [0x00][0x50][status:1][server_nonce:16][device_id:4]
//              status = AUTH_STATUS_CHALLENGE (0x00) on success.
//            STEP 2:  [0x00][0x50][AUTH_STATUS_SUCCESS] on match (session opens);
//                     [0x00][0x50][AUTH_STATUS_FAILED]  on wrong key;
//                     [0x00][0x50][AUTH_STATUS_*]       for the other states.
// @errors:   AUTH_STATUS_NOT_CONFIG (no key set), AUTH_STATUS_RATE_LIMIT,
//            AUTH_STATUS_ALREADY, AUTH_STATUS_ERROR.
// @state:    STEP 2 must arrive within 30 s of the challenge or it is rejected.
//            Rate limit: >=10 attempts within any 60 s window -> RATE_LIMIT.
//            ALWAYS PLAINTEXT (this is how a session is bootstrapped).
// @limits:   step-2 command is 34 bytes total (2 opcode + 16 + 16).
// @targets:  Firmware | NRF54 | Silabs | NRF52811  (where security is enabled)
export const CMD_AUTHENTICATE = 0x0050;

// @opcode: 0x0051   @name: CMD_ENTER_DFU   @dir: host->device
// @request:  [0x00][0x51]  (no payload)
// @response: none on nRF (sets Nordic GPREGRET magic, jumps to bootloader,
//            BLE drops). Silabs may ACK [0x00][0x51] before entering DFU.
// @errors:   none
// @state:    session required when security enabled.
// @limits:   -
// @targets:  NRF54 | Silabs | NRF52811   (nRF/Silabs bootloaders)
export const CMD_ENTER_DFU = 0x0051;

// @opcode: 0x0052   @name: CMD_DEEP_SLEEP   @dir: host->device
// @request:  [0x00][0x52]  OR  [0x00][0x52][seconds:2 BE]  (optional wake timer)
// @response: best-effort / target-specific; tolerate the link dropping:
//              ESP32 w/ power latch : [0x00][0x52] then powers off (~100 ms).
//              ESP32 w/o latch      : sleeps immediately, no ACK, link drops.
//              Silabs Flex          : [0x00][0x52] then closes link, enters EM4.
//              nRF                  : logs only (deep sleep unsupported).
// @errors:   none
// @state:    session required when security enabled.
// @limits:   optional [seconds:2 BE] wake interval.
// @targets:  Firmware (ESP32) | Silabs   (nRF targets: no-op)
export const CMD_DEEP_SLEEP = 0x0052;

// @opcode: 0x0070   @name: CMD_DIRECT_WRITE_START   @dir: host->device
// @request:  UNCOMPRESSED: [0x00][0x70]  (no size, no data; all bytes via 0x71).
//            COMPRESSED:   [0x00][0x70][uncompressed_size:4 LE][first zlib bytes...]
//              -> remaining zlib bytes stream via CMD_DIRECT_WRITE_DATA (0x71).
// @response: [0x00][0x70] (RESP_DIRECT_WRITE_START_ACK) on accept.
// @errors:   [0xFF][0x70] (RESP_DIRECT_WRITE_ERROR path) on setup failure.
// @state:    begins a full-frame image session; a new START aborts any prior one.
// @limits:   START plaintext <= 200 bytes (encrypted: fit within 154 budget).
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_DIRECT_WRITE_START = 0x0070;

// @opcode: 0x0071   @name: CMD_DIRECT_WRITE_DATA   @dir: host->device
// @request:  [0x00][0x71][image_data...]  (chunk of the image / zlib stream)
// @response: [0x00][0x71] (RESP_DIRECT_WRITE_DATA_ACK) per chunk.
// @errors:   [0xFF][0x71] on write/decompress/overflow; for a partial (0x76)
//            session the NACK data byte is an OD_ERR_PARTIAL_* code.
// @state:    must follow a 0x70 or 0x76 START; also carries partial-stream data.
// @limits:   <= 230 bytes (unencrypted) / <= 154 (encrypted).
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_DIRECT_WRITE_DATA = 0x0071;

// @opcode: 0x0072   @name: CMD_DIRECT_WRITE_END   @dir: host->device
// @request:  [0x00][0x72][refresh:1]  (+ optional [new_etag:4 BE]; presence by
//            length). refresh: 0=FULL, 1=FAST/PARTIAL.
// @response: [0x00][0x72] (RESP_DIRECT_WRITE_END_ACK, data complete) THEN an
//            unsolicited refresh notification:
//              [0x00][0x73] RESP_DIRECT_WRITE_REFRESH_SUCCESS (panel updated), or
//              [0x00][0x74] RESP_DIRECT_WRITE_REFRESH_TIMEOUT (refresh timed out).
//            [0xFF][0x72] if the transfer was incomplete (missing bytes / zlib flush).
// @errors:   NACK on incompleteness; refresh reported via 0x73/0x74.
// @state:    finalizes the 0x70 session and triggers the panel refresh.
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_DIRECT_WRITE_END = 0x0072;

// @opcode: 0x0073   @name: CMD_LED_ACTIVATE   @dir: host->device
// @request:  [0x00][0x73][led_instance:1][flash_config:12]
// @response: [0x00][0x73] (RESP_LED_ACTIVATE_ACK).
// @errors:   [0xFF][0x73] on bad instance / config.
// @state:    session required when security enabled.
// @limits:   flash_config is a fixed 12-byte typed payload.
// @targets:  Firmware | NRF54 | Silabs | NRF52811
// @collision: the RESPONSE byte 0x73 is reused -- see RESP_LED_ACTIVATE_ACK vs
//            RESP_DIRECT_WRITE_REFRESH_SUCCESS below (disambiguate by direction).
export const CMD_LED_ACTIVATE = 0x0073;

// @opcode: 0x0075   @name: CMD_LED_STOP   @dir: host->device
// @request:  [0x00][0x75][led_instance:1]  (stop the LED pattern)
// @response: [0x00][0x75] (RESP_LED_STOP_ACK).
// @errors:   [0xFF][0x75] on bad instance.
// @state:    session required when security enabled.
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs      (NOT NRF52811)
export const CMD_LED_STOP = 0x0075;

// @opcode: 0x0076   @name: CMD_PARTIAL_WRITE_START   @dir: host->device
// @request:  [0x00][0x76][flags:1][old_etag:4 BE][new_etag:4 BE]
//                       [x:2 BE][y:2 BE][width:2 BE][height:2 BE][initial stream...]
//            17-byte fixed header, ALL BIG-ENDIAN (note: PIPE 0x80's partial
//            extension packs the same geometry LITTLE-endian instead). Remaining
//            stream bytes follow via 0x71 DATA; the transfer ends with 0x72.
// @response: [0x00][0x76] on accept (then 0x71 ACKs, then 0x72 END + 0x73/0x74).
// @errors:   [0xFF][0x76][OD_ERR_PARTIAL_*][0x00]  (namespace scoped to 0x76):
//              0x01 OD_ERR_PARTIAL_ETAG_MISMATCH, 0x03 OD_ERR_PARTIAL_RECT_OOB,
//              0x04 OD_ERR_PARTIAL_RECT_ALIGN,     0x05 OD_ERR_PARTIAL_FLAGS,
//              0x06 OD_ERR_PARTIAL_STREAM,         0x07 OD_ERR_PARTIAL_UNSUPPORTED.
//            (0x02 unused.) Any geometry/etag NACK clears the device's
//            displayed_etag. See SECTION 4; do NOT emit OD_ERR_PIPE_START_* here.
// @state:    requires 1bpp panel; x and width must be multiples of 8; old_etag
//            must equal the currently displayed etag.
// @limits:   START plaintext <= 200 bytes.
// @targets:  Firmware | NRF54      (NOT Silabs, NOT NRF52811)
export const CMD_PARTIAL_WRITE_START = 0x0076;

// @opcode: 0x0077   @name: CMD_BUZZER   @dir: host->device
// @request:  [0x00][0x77][buzzer_instance:1][outer_repeats:1][n_patterns:1][patterns...]
// @response: [0x00][0x77] (RESP_BUZZER_ACK).
// @errors:   [0xFF][0x77] on bad instance / config.
// @state:    session required when security enabled.
// @limits:   -
// @targets:  Firmware | NRF54      (NOT Silabs, NOT NRF52811)
export const CMD_BUZZER = 0x0077;

// @opcode: 0x0080   @name: CMD_PIPE_WRITE_START   @dir: host->device
// @request:  10-byte header (22 when partial):
//              [0x00][0x80][ver:1][flags:1][req_window:1][req_ack_every:1]
//                          [client_max_frame:2 LE][total_size:4 LE]
//              --- appended iff flags bit1 (PIPE_FLAG_PARTIAL) ---
//                          [old_etag:4 LE][x:2 LE][y:2 LE][w:2 LE][h:2 LE]
//              ver = PIPE_VERSION (1); flags bit0 = PIPE_FLAG_COMPRESSED (zlib),
//              bit1 = PIPE_FLAG_PARTIAL. total_size = decompressed byte total
//              (partial: plane_size * 2). All pipe fields are LITTLE-endian.
// @response: [0x00][0x80][ver:1][max_window:1][max_ack_every:1]
//                        [max_frame:2 LE][resp_flags:1]
//              resp_flags bit0 = selective-repeat supported, bit1 = partial
//              accepted. Device echoes its negotiated maxima (min-rule applies).
// @errors:   [0xFF][0x80][OD_ERR_PIPE_START_*][0x00]  (namespace scoped to the
//            0x80 START, DISTINCT from the 0x76 OD_ERR_PARTIAL_* set):
//              0x01 OD_ERR_PIPE_START_BAD_HEADER   (bad length or version),
//              0x02 OD_ERR_PIPE_START_UNKNOWN_FLAG,
//              0x03 OD_ERR_PIPE_START_SIZE_MISMATCH,
//              0x05 OD_ERR_PIPE_START_ETAG_MISMATCH        (partial),
//              0x06 OD_ERR_PIPE_START_PARTIAL_UNSUPPORTED,
//              0x07 OD_ERR_PIPE_START_RECT_INVALID          (partial).
//            (0x04 unused.) See SECTION 4; do NOT emit OD_ERR_PARTIAL_* here --
//            0x03/0x05/0x06/0x07 mean different things in the two namespaces.
// @state:    a new START aborts any in-flight transfer; seq resets to 0.
// @limits:   window/ack_every 1..32; frame <= PIPE_MAX_FRAME (244).
// @targets:  Firmware      (NOT NRF54, NOT Silabs, NOT NRF52811)
export const CMD_PIPE_WRITE_START = 0x0080;

// @opcode: 0x0081   @name: CMD_PIPE_WRITE_DATA   @dir: host->device (and the
//          device->host ACK/NACK opcode)
// @request:  [0x00][0x81][seq:1][data...]
//              seq = chunk index mod 256 (reset to 0 by each 0x80 START).
//              When encrypted, [seq][data] is the inner plaintext payload.
// @response: SACK ACK (7 bytes): [0x00][0x81][highest_seen:1][ack_mask:4 LE]
//              mask bit i (LSB first) = chunk (highest_seen-1-i) received;
//              highest_seen is implicitly acked. ACK cadence = negotiated N.
//            NACK (8 bytes, FATAL): [0xFF][0x81][err:1][highest_seen:1][ack_mask:4 LE]
//              err: 0x02 decompress error, 0x03 write/size error, 0x04 protocol.
// @errors:   see NACK above; after a NACK, further 0x81 frames are discarded
//            until the next 0x80 START or disconnect.
// @state:    out-of-order frames buffered in a 33-slot reorder queue; window W.
// @limits:   data <= frame_eff - PIPE_FRAME_OVERHEAD (3); frame_eff <= 244.
// @targets:  Firmware      (NOT NRF54, NOT Silabs, NOT NRF52811)
export const CMD_PIPE_WRITE_DATA = 0x0081;

// @opcode: 0x0082   @name: CMD_PIPE_WRITE_END   @dir: host->device
// @request:  [0x00][0x82][refresh:1]  (+ optional [new_etag:4 BE]; presence by
//            length). Full-frame: refresh 0=FULL,1=FAST. Partial-negotiated:
//            0=FULL,1=FAST,2/absent=PARTIAL.
// @response: a tail-flush SACK [0x00][0x81]... first, then
//              [0x00][0x82] end-ACK, then the refresh notification
//              [0x00][0x73] success or [0x00][0x74] timeout.
//            [0xFF][0x82] if incomplete (a hole remains / byte count short).
// @errors:   NACK [0xFF][0x82] on incompleteness; refresh via 0x73/0x74.
// @state:    client must not send END until every chunk is acked.
// @limits:   -
// @targets:  Firmware      (NOT NRF54, NOT Silabs, NOT NRF52811)
// @collision: 0x0082 is PIPE_WRITE_END here. NFC moved OFF 0x0082 to 0x0083 in
//            protocol v2 precisely to end the historical opcode clash.
export const CMD_PIPE_WRITE_END = 0x0082;

// @opcode: 0x0083   @name: CMD_NFC_ENDPOINT   @dir: host->device
// @request:  [0x00][0x83][sub:1][sub-specific payload...]  where sub =
//              NFC_SUB_READ        0x00 : (no more payload) read the tag.
//              NFC_SUB_WRITE       0x01 : [rec_type:1][len:2 BE][payload:len]
//                                          single-shot write (<= ~120 B app data).
//              NFC_SUB_WRITE_START 0x10 : [rec_type:1][total_len:2 BE]
//                                          begin a chunked write (buffer <= 512 B).
//              NFC_SUB_WRITE_DATA  0x11 : [chunk...]  (append; needs active START)
//              NFC_SUB_WRITE_END   0x12 : (no payload) commit; received==total.
//            rec_type is one of OD_NFC_REC_* (below).
// @response: NOTE the 3rd byte is an NFC SUB-STATUS, a DIFFERENT field from the
//            opcode echo -- it happens to reuse values 0x80/0x81/0x82:
//              READ ok : [0x00][0x83][NFC_STATUS_READ_DATA 0x80][rec_type:1][len:2 BE][data:len]
//              WRITE ok (single / chunk END): [0x00][0x83][NFC_STATUS_WRITE_COMMITTED 0x81]
//              WRITE_START / WRITE_DATA ok  : [0x00][0x83][NFC_STATUS_CHUNK_ACCEPTED 0x82]
// @errors:   [0xFF][0x83][0xFF][NFC_ERR_*] (4-byte NACK; 4th byte is the code):
//              0x01 malformed/short, 0x02 read failed, 0x03 tag write failed,
//              0x04 unknown sub-command, 0x05 invalid rec_type,
//              0x06 bad total_len (0 or >512), 0x07 chunk without active START
//              (or wrong connection), 0x08 chunk overflow past total_len,
//              0x09 END with received != total_len.
// @state:    chunked write is per-connection: START binds the connection; DATA
//            from another connection -> 0x07. Buffer size 512 bytes.
// @limits:   single-write app data threshold ~120 B; chunk buffer 512 B.
// @targets:  NRF54 | Silabs      (NOT Firmware, NOT NRF52811)
// @since:    v2
// @changed:  moved 0x0082 -> 0x0083 in protocol v2 to resolve the collision
//            with CMD_PIPE_WRITE_END. Old 0x0082 NFC frames are now rejected
//            (clean cutover, no alias). The NFC sub-status value 0x82
//            ("chunk accepted") is UNRELATED to the retired 0x0082 opcode --
//            do not confuse the two.
export const CMD_NFC_ENDPOINT = 0x0083;

// ===== Section 2: RESPONSE / STATUS BYTES (8-bit) =====
// A response frame is [status][cmd_echo][data]. The status byte is one of the
// three shared values; cmd_echo is the low byte of the command, and the RESP_*
// echo constants below mirror that low byte.

// Shared status byte (frame position 0).
export const RESP_ACK = 0x00;  // success
export const RESP_NACK = 0xFF;  // failure; data[0] often an error code
export const RESP_AUTH_REQUIRED = 0xFE;  // gated command sent without a live session

// Command-echo bytes (frame position 1) = low byte of the matching CMD_*.
export const RESP_CONFIG_READ = 0x40;
export const RESP_CONFIG_WRITE = 0x41;
export const RESP_CONFIG_CHUNK = 0x42;
export const RESP_FIRMWARE_VERSION = 0x43;
export const RESP_MSD_READ = 0x44;
export const RESP_CONFIG_CLEAR = 0x45;
export const RESP_AUTHENTICATE = 0x50;
export const RESP_ENTER_DFU = 0x51;
export const RESP_DEEP_SLEEP = 0x52;

// Direct-write family (Firmware / NRF52811 + shared).
export const RESP_DIRECT_WRITE_START_ACK = 0x70;
export const RESP_DIRECT_WRITE_DATA_ACK = 0x71;
export const RESP_DIRECT_WRITE_END_ACK = 0x72;
export const RESP_DIRECT_WRITE_REFRESH_SUCCESS = 0x73;  // unsolicited device->host: panel refreshed OK
export const RESP_DIRECT_WRITE_REFRESH_TIMEOUT = 0x74;  // unsolicited device->host: refresh timed out
export const RESP_DIRECT_WRITE_ERROR = 0xFF;  // direct-write NACK status (== RESP_NACK)

// LED / buzzer acks.
export const RESP_LED_ACTIVATE_ACK = 0x73;
export const RESP_LED_STOP_ACK = 0x75;
export const RESP_BUZZER_ACK = 0x77;

// NFC endpoint echo byte (was 0x82u in protocol v1; see CMD_NFC_ENDPOINT).
export const RESP_NFC_ENDPOINT = 0x83;

// @collision: RESPONSE byte 0x73 has two meanings, disambiguated by direction
//   and context:
//     RESP_LED_ACTIVATE_ACK             -- a REPLY to CMD_LED_ACTIVATE, framed
//                                          [status][0x73][...]; solicited.
//     RESP_DIRECT_WRITE_REFRESH_SUCCESS -- an UNSOLICITED device->host refresh
//                                          notification following a 0x72/0x82 END.
//   Same byte value, distinct semantics; a client keys off which command it
//   just issued (LED activate vs image END) to interpret the 0x73.

// ===== Section 3: AUTHENTICATE STATUS (3rd byte of a 0x50 response) =====

export const AUTH_STATUS_CHALLENGE = 0x00;
export const AUTH_STATUS_SUCCESS = AUTH_STATUS_CHALLENGE;  // alias: step-2 success == challenge value
export const AUTH_STATUS_FAILED = 0x01;  // wrong key
export const AUTH_STATUS_ALREADY = 0x02;  // already authenticated
export const AUTH_STATUS_NOT_CONFIG = 0x03;  // encryption not configured
export const AUTH_STATUS_RATE_LIMIT = 0x04;  // >=10 attempts / 60 s
export const AUTH_STATUS_ERROR = 0xFF;  // generic error

// ===== Section 4: OPCODE-SCOPED NACK ERROR NAMESPACES =====
// NACK error bytes are opcode-SCOPED, never global: data[0] of a NACK is only
// meaningful once you know the echoed opcode (byte 1). This section holds the
// distinct, PREFIXED error namespaces -- one per handler -- so a byte value can
// be reused with different meanings and stay unambiguous on the wire. The NFC
// namespace lives in SECTION 5 (NFC_ERR_*, the 4th byte of
// [0xFF][0x83][0xFF][err]); it is cross-referenced but NOT redefined here.
//
// SCOPING RULE
//   The 0x76 (OD_ERR_PARTIAL_*) and 0x80-START (OD_ERR_PIPE_START_*) sets below
//   DELIBERATELY REUSE byte values 0x03, 0x05, 0x06 and 0x07 with DIFFERENT
//   meanings. They must NEVER be cross-applied: the echoed opcode is the only
//   thing that disambiguates them. E.g. byte 0x03 == OD_ERR_PARTIAL_RECT_OOB
//   under a 0x76 NACK but OD_ERR_PIPE_START_SIZE_MISMATCH under a 0x80 NACK.
//
// IMPLEMENTATION GUIDANCE (for firmware handlers adopting these constants)
//   - A handler for CMD_PARTIAL_WRITE_START (0x76), and the 0x71/0x72 frames of
//     that partial session, MUST emit ONLY OD_ERR_PARTIAL_* codes.
//   - A handler for CMD_PIPE_WRITE_START (0x80) MUST emit ONLY
//     OD_ERR_PIPE_START_* codes.
//   - The NFC handler (CMD_NFC_ENDPOINT 0x83) MUST emit ONLY NFC_ERR_* codes
//     (SECTION 5).
//   A code from one namespace must NEVER appear in another handler's NACK. The
//   overlapping raw byte values are intentional and safe ONLY because the echoed
//   opcode scopes them -- pick the constant by which opcode you are answering.
// 4a. PARTIAL-WRITE errors -- scope: CMD_PARTIAL_WRITE_START (0x76) and its
//     0x71 DATA / 0x72 END frames.  NACK frame: [0xFF][0x76][err][0x00].
//     (0x02 is intentionally unused in this set.)

export const OD_ERR_PARTIAL_ETAG_MISMATCH = 0x01;  // old_etag != displayed etag
export const OD_ERR_PARTIAL_RECT_OOB = 0x03;  // rectangle out of panel bounds
export const OD_ERR_PARTIAL_RECT_ALIGN = 0x04;  // x / width not a multiple of 8
export const OD_ERR_PARTIAL_FLAGS = 0x05;  // bad / unsupported flags
export const OD_ERR_PARTIAL_STREAM = 0x06;  // stream / length error
export const OD_ERR_PARTIAL_UNSUPPORTED = 0x07;  // partial write unsupported (e.g. not 1bpp)

// 4b. PIPE-START errors -- scope: CMD_PIPE_WRITE_START (0x80) ONLY.
//     NACK frame: [0xFF][0x80][err][0x00].  DISTINCT namespace from 4a: the
//     shared byte values (0x03/0x05/0x06/0x07) mean different things here.
//     (0x04 is unused in this set.)  Note: the in-flight 0x81 PIPE_WRITE_DATA
//     NACK carries its OWN handler-local err byte (see CMD_PIPE_WRITE_DATA
//     @response) and is not part of this START namespace.
export const OD_ERR_PIPE_START_BAD_HEADER = 0x01;  // bad length or version
export const OD_ERR_PIPE_START_UNKNOWN_FLAG = 0x02;  // unknown flags bit set
export const OD_ERR_PIPE_START_SIZE_MISMATCH = 0x03;  // total_size inconsistent
export const OD_ERR_PIPE_START_ETAG_MISMATCH = 0x05;  // partial: old_etag mismatch
export const OD_ERR_PIPE_START_PARTIAL_UNSUPPORTED = 0x06;  // partial mode not supported
export const OD_ERR_PIPE_START_RECT_INVALID = 0x07;  // partial: invalid rectangle

// ===== Section 5: NFC SUB-PROTOCOL (rides CMD_NFC_ENDPOINT 0x0083) =====

// NFC sub-command (request payload byte 0).
export const NFC_SUB_READ = 0x00;
export const NFC_SUB_WRITE = 0x01;  // single-shot write
export const NFC_SUB_WRITE_START = 0x10;  // begin chunked write
export const NFC_SUB_WRITE_DATA = 0x11;  // append chunk
export const NFC_SUB_WRITE_END = 0x12;  // commit chunked write

// NFC record types (rec_type field). Wire bytes an agent must ground on --
// kept here (not in per-repo constants) for that reason.
export const OD_NFC_REC_TEXT = 0;
export const OD_NFC_REC_URI = 1;
export const OD_NFC_REC_WELL_KNOWN_RAW = 2;
export const OD_NFC_REC_MIME = 3;
export const OD_NFC_REC_RAW_NDEF = 4;

// NFC IC (tag chip) selector.
export const OD_NFC_IC_AUTO = 0;
export const OD_NFC_IC_TNB132M = 1;

// NFC response SUB-STATUS (3rd byte of a 0x83 response, AFTER the
// [status][echo] pair). This is a DIFFERENT field from the opcode echo; the
// value 0x82 here means "chunk accepted" and is UNRELATED to the retired
// 0x0082 NFC opcode.
export const NFC_STATUS_READ_DATA = 0x80;  // [.. 0x80][rec_type][len:2 BE][data]
export const NFC_STATUS_WRITE_COMMITTED = 0x81;  // single write / chunk END committed
export const NFC_STATUS_CHUNK_ACCEPTED = 0x82;  // WRITE_START or WRITE_DATA accepted

// NFC NACK error codes (4th byte of [0xFF][0x83][0xFF][err]).
export const NFC_ERR_MALFORMED = 0x01;  // malformed / short frame
export const NFC_ERR_READ_FAILED = 0x02;  // tag read failed
export const NFC_ERR_TAG_WRITE_FAILED = 0x03;  // tag write failed
export const NFC_ERR_UNKNOWN_SUBCMD = 0x04;  // unknown sub-command byte
export const NFC_ERR_INVALID_REC_TYPE = 0x05;  // rec_type not in OD_NFC_REC_*
export const NFC_ERR_BAD_TOTAL_LEN = 0x06;  // total_len == 0 or > 512
export const NFC_ERR_CHUNK_NO_START = 0x07;  // DATA/END without active START (or wrong connection)
export const NFC_ERR_CHUNK_OVERFLOW = 0x08;  // chunk would exceed total_len
export const NFC_ERR_END_LEN_MISMATCH = 0x09;  // END with received != total_len

// ===== Section 6: PIPE SLIDING-WINDOW WIRE CONSTANTS (0x0080..0x0082) =====

export const PIPE_VERSION = 0x01;  // carried in 0x80 request/response ver field
export const PIPE_FLAG_COMPRESSED = 0x01;  // flags bit0: streamed bytes are zlib-compressed
export const PIPE_FLAG_PARTIAL = 0x02;  // flags bit1: partial-region refresh
export const PIPE_MAX_FRAME = 244;  // max on-wire frame size (GATT write ceiling)
export const PIPE_FRAME_OVERHEAD = 3;  // plaintext 0x81 header: cmd(2) + seq(1)
export const PIPE_ACK_MASK_BITS = 32;  // SACK ack_mask width in bits
export const OD_PIPE_MAX_PAYLOAD = 244;  // max payload buffer used by pipe/NFC responses

// ===== Section 7: CHUNK / SIZE BUDGETS =====

export const CONFIG_CHUNK_SIZE = 200;  // max config data bytes per chunk
export const CONFIG_CHUNK_SIZE_WITH_PREFIX = 202;  // first chunked CONFIG_WRITE payload: total(2) + 200
export const MAX_CONFIG_CHUNKS = 20;  // upper bound on config chunks in a write
export const MAX_RESPONSE_DATA_SIZE = 100;  // max bytes in a single notification frame

// ===== Section 8: ENCRYPTION ENVELOPE (wire-visible sizes) =====
// Envelope: [cmd:2 BE][nonce:16][ciphertext][tag:12]; inner plaintext is
// [len:1][payload]; AAD = the 2 opcode bytes; AEAD = AES-128-CCM.

export const BLE_CMD_HEADER_SIZE = 2;  // opcode bytes (also the AAD length)
export const ENCRYPTION_NONCE_SIZE = 16;  // envelope nonce (CCM nonce = bytes 3..15)
export const ENCRYPTION_TAG_SIZE = 12;  // CCM authentication tag length

