// @generated by tools/gen_js_protocol.py -- DO NOT EDIT BY HAND.
// Source: opendisplay_protocol.h (OD_PROTOCOL_VERSION 2.2)
// Source SHA-256: 0114537bcb02b7c7aacc11286a6ec89abfdf7e3776160b3356036c43c6fa8b13
// Regenerate: tools/gen_js_protocol.py --write   (CI drift gate: --check)
//
// OpenDisplay BLE wire-protocol constants. Every value here travels on the wire.
// Flat `export const` (not a TS enum) because the wire reuses byte values across
// distinct names. NACK error codes are opcode-SCOPED: decode data[0] only in the
// scope of the echoed opcode (see the header for the full contract).

// ===== Protocol version =====

// Wire-protocol revision, MAJOR.MINOR. See VERSIONING POLICY in the banner for
// when to bump which number. This marker describes the spec and is NOT sent on
// the wire (the negotiated 0x0080 PIPE_VERSION is a separate field).
export const OD_PROTOCOL_VERSION_MAJOR = 2;
export const OD_PROTOCOL_VERSION_MINOR = 2;
export const OD_PROTOCOL_VERSION_STR = "2.2";

// ===== Section 1: COMMAND OPCODES (16-bit, big-endian on the wire) =====
// Config-packet-type bytes (the payload's first byte for CONFIG_WRITE TLVs)
// are NOT defined here -- they live in each repo's opendisplay_structs.h /
// opendisplay_constants.h and diverge per target. Comment-only reference:
//     0x01 system        0x02 manufacturer   0x04 power
//     0x20 display       0x21 led            0x23 sensor
//     0x24 data_bus      0x25 binary_inputs  0x26 wifi
//     0x27 security      0x28 touch          0x29 passive_buzzer
//     0x2A nfc           0x2B flash          0x2C data_extended

// @opcode: 0x000F   @name: CMD_REBOOT   @dir: host->device
// @request:  [0x00][0x0F]  (no payload)
// @response: none on most targets (immediate reset, BLE link drops). Silabs
//            may ACK before resetting; treat a dropped connection as success.
// @errors:   none
// @state:    if security enabled, session required (except on the no-ACK path).
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_REBOOT = 0x000F;

// @opcode: 0x0040   @name: CMD_CONFIG_READ   @dir: host->device
// @request:  [0x00][0x40]  (no payload)
// @response: one OR MORE notifications (chunked), each:
//              [0x00][0x40][chunk_number:2 LE][total_len:2 LE on chunk 0 only][data...]
//            chunk_number counts from 0; total_len (uint16 LE) is present ONLY
//            on chunk 0 and gives the full config byte length. Empty config
//            yields a single [0x00][0x40][0x00 0x00][0x00 0x00].
// @errors:   [0xFF][0x40][0x00][0x00] on storage-init failure.
// @state:    session required when security enabled.
// @limits:   each frame's data <= MAX_RESPONSE_DATA_SIZE (100) minus its header.
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_CONFIG_READ = 0x0040;

// @opcode: 0x0041   @name: CMD_CONFIG_WRITE   @dir: host->device
// @request:  single-frame (payload <= 200):  [0x00][0x41][config_data...]
//            chunked (payload  > 200):        [0x00][0x41][total:2 LE][first 200 data bytes]
//              -> the first frame MUST carry a FULL 200 data bytes (payload =
//                 2 + 200 = 202); a short first chunk makes firmware take the
//                 single-frame path and NACK the following 0x42 chunks.
//              -> remaining bytes follow as CMD_CONFIG_CHUNK (0x0042) frames.
// @response: [0x00][0x41] on accept (or after last chunk); [0xFF][0x41] on error.
// @errors:   NACK on malformed TLV, size overflow, or bad chunk sequencing.
// @state:    session required when security enabled. Device computes
//            expectedChunks = ceil(total / 200).
// @limits:   CONFIG_CHUNK_SIZE 200; first chunk payload CONFIG_CHUNK_SIZE_WITH_PREFIX 202.
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_CONFIG_WRITE = 0x0041;

// @opcode: 0x0042   @name: CMD_CONFIG_CHUNK   @dir: host->device
// @request:  [0x00][0x42][chunk_data...]  (up to 200 bytes; continuation of a
//            chunked CONFIG_WRITE started at 0x0041).
// @response: [0x00][0x42] per accepted chunk; final chunk commits + reloads
//            config. [0xFF][0x42] on overflow / no active write / bad total.
// @errors:   NACK if no active chunked write, or received > declared total.
// @state:    must follow a chunked 0x0041 START; count bounded by MAX_CONFIG_CHUNKS.
// @limits:   <= CONFIG_CHUNK_SIZE (200) data bytes.
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_CONFIG_CHUNK = 0x0042;

// @opcode: 0x0043   @name: CMD_FIRMWARE_VERSION   @dir: host->device
// @request:  [0x00][0x43]  (no payload)
// @response: [0x00][0x43][major:1][minor:1][... optional git/SHA string]
// @errors:   none
// @state:    ALWAYS PLAINTEXT (never encrypted) so version is readable pre-auth.
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_FIRMWARE_VERSION = 0x0043;

// @opcode: 0x0044   @name: CMD_READ_MSD   @dir: host->device
// @request:  [0x00][0x44]  (no payload)
// @response: [0x00][0x44][msd_bytes:16]  (manufacturer-specific data record).
// @errors:   none
// @state:    on Silabs this response is PLAINTEXT even with security enabled.
// @limits:   16 data bytes.
// @targets:  NRF54 | Silabs | NRF52811   (Firmware handles it but see repo)
export const CMD_READ_MSD = 0x0044;

// @opcode: 0x0045   @name: CMD_CONFIG_CLEAR   @dir: host->device
// @request:  [0x00][0x45]  (no payload)
// @response: [0x00][0x45] on success; [0xFF][0x45] on failure.
// @errors:   NACK if config storage erase fails.
// @state:    session required when security enabled.
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs      (NOT NRF52811)
export const CMD_CONFIG_CLEAR = 0x0045;

// @opcode: 0x0050   @name: CMD_AUTHENTICATE   @dir: host->device
// @request:  STEP 1 (request challenge):  [0x00][0x50][0x00]
//            STEP 2 (prove key):          [0x00][0x50][client_nonce:16][mac:16]
//              mac = AES-CMAC(master_key, server_nonce || client_nonce || device_id)
// @response: STEP 1 challenge (23 bytes): [0x00][0x50][status:1][server_nonce:16][device_id:4]
//              status = AUTH_STATUS_CHALLENGE (0x00) on success.
//            STEP 2:  [0x00][0x50][AUTH_STATUS_SUCCESS] on match (session opens);
//                     [0x00][0x50][AUTH_STATUS_FAILED]  on wrong key;
//                     [0x00][0x50][AUTH_STATUS_*]       for the other states.
// @errors:   AUTH_STATUS_NOT_CONFIG (no key set), AUTH_STATUS_RATE_LIMIT,
//            AUTH_STATUS_ALREADY, AUTH_STATUS_ERROR.
// @state:    STEP 2 must arrive within 30 s of the challenge or it is rejected.
//            Rate limit: >=10 attempts within any 60 s window -> RATE_LIMIT.
//            ALWAYS PLAINTEXT (this is how a session is bootstrapped).
// @limits:   step-2 command is 34 bytes total (2 opcode + 16 + 16).
// @targets:  Firmware | NRF54 | Silabs | NRF52811  (where security is enabled)
export const CMD_AUTHENTICATE = 0x0050;

// @opcode: 0x0051   @name: CMD_ENTER_DFU   @dir: host->device
// @request:  [0x00][0x51]  (no payload)
// @response: none on nRF (sets Nordic GPREGRET magic, jumps to bootloader,
//            BLE drops). Silabs may ACK [0x00][0x51] before entering DFU.
// @errors:   none
// @state:    session required when security enabled.
// @limits:   -
// @targets:  NRF54 | Silabs | NRF52811   (nRF/Silabs bootloaders)
export const CMD_ENTER_DFU = 0x0051;

// @opcode: 0x0052   @name: CMD_POWER_OFF   @dir: host->device
// @request:  [0x00][0x52]  (bare). Any trailing payload is RESERVED and
//            ignored today; senders SHOULD send none.
// @response: FIRE-AND-FORGET (same acknowledgement model as CMD_DEEP_SLEEP
//            0x0053):
//              [0x00][0x52]              ACK is QUEUED on latch HW but usually
//                                        dies in the TX buffer before the rail
//                                        is cut (~100 ms later). Expected, NOT
//                                        a bug; senders MUST NOT wait for it --
//                                        treat transmit as "delivered".
//              [0xFF][0x52][0x00][0x00]  no power latch on this target.
//              [0xFE][0x52]              auth required (no live session).
// @errors:   NACK data[0] scoped to opcode 0x52 (OD_ERR_POWER_OFF_*, see
//            SECTION 4d): 0x00 UNSUPPORTED (no D-FF latch). A target that
//            refuses 0x52 may still accept 0x53 deep sleep -- do not conflate
//            "power-off unsupported" with "cannot sleep".
// @state:    session required when security enabled. Cuts the power rail via
//            the D-FF latch; the device wakes ONLY on a physical button press
//            (fresh cold boot). No timer, no wake interval -- power-off is
//            absolute.
// @limits:   trailing payload reserved/ignored.
// @targets:  Firmware (ESP32, D-FF power-latch HW ONLY). All other targets
//            (non-latch/mains ESP32, Silabs, nRF) NACK [0xFF][0x52][0x00].
// @since:    new in 2.1 -- splits the hard rail-cut out of CMD_DEEP_SLEEP so
//            latch HW gets timed-wake sleep via 0x0053 and an explicit,
//            capability-gated hard-off via 0x0052.
// @changed:  opcode is 0x0052 -- swapped with CMD_DEEP_SLEEP within the
//            (unreleased) 2.1 line so power-off takes the lower number. NOTE:
//            0x0052 was CMD_DEEP_SLEEP in shipped firmware (PR #97); a peer
//            still on the old mapping will hit deep-sleep here.
export const CMD_POWER_OFF = 0x0052;

// @opcode: 0x0053   @name: CMD_DEEP_SLEEP   @dir: host->device
// @request:  [0x00][0x53]                 -> sleep now, configured cadence.
//            [0x00][0x53][seconds:2 BE]   -> sleep now; wake timer = seconds
//                                            for THIS cycle only (one-shot,
//                                            never persisted).
//              - seconds is a BIG-ENDIAN uint16 (deliberate, documented
//                exception to the LE payload default). Range 1..65535 s
//                (~18.2 h; the wire width is the ceiling).
//              - seconds == 0x0000 or empty payload = "no override" (use
//                configured deep_sleep_time_seconds); NOT an error.
//              - len == 1 is malformed -> logged, treated as no override
//                (not rejected). Bytes beyond the 2 seconds bytes are ignored
//                (forward compatibility).
// @response: FIRE-AND-FORGET. ACK/NACK are OPTIONAL / best-effort; a sender
//            MUST NOT expect, block on, or infer success/failure from any
//            frame. The SUCCESS path emits NO frame: the device enters deep
//            sleep and BLE drops -- treat disconnect/silence as "delivered".
//              [0xFF][0x53][0x01][0x00]  deep sleep disabled in config.
//              [0xFF][0x53][0x02][0x00]  mains-powered; refuses to sleep.
//              [0xFF][0x53][0x00][0x00]  unsupported target (nRF; may instead
//                                        stay silent and log).
//              [0xFE][0x53]              auth required (no live session).
// @errors:   NACK data[0] scoped to opcode 0x53 (OD_ERR_DEEP_SLEEP_*, see
//            SECTION 4c): 0x00 UNSUPPORTED, 0x01 DISABLED
//            (deep_sleep_time_seconds == 0), 0x02 NOT_BATTERY (power_mode
//            != 1). CRITICAL client rule: 0x01/0x02 mean "rejected -- device
//            still AWAKE and reachable"; ONLY 0x00 means the target lacks deep
//            sleep. Never conflate them.
// @state:    session required when security enabled. The override is consumed
//            at sleep entry; the next wake (and every later one) reverts to the
//            configured cadence. An aborted sleep discards the override.
// @limits:   optional [seconds:2 BE]; ceiling 65535 s (wire width). Recommended
//            client-side floor >= 10 s (wake-storm guard).
// @targets:  Firmware (ESP32: honors duration, incl. D-FF-latch HW -- target
//            design, see @changed; reTerminal E1001/2/3 have no latch and
//            already plain timer-sleep) | Silabs (ACKs, IGNORES payload, enters
//            EM4) | nRF targets: unsupported.
// @changed:  BREAKING vs shipped firmware -- opcode moved 0x0052 -> 0x0053
//            (swapped with CMD_POWER_OFF within the unreleased 2.1 line). The
//            [seconds:2 BE] payload shipped on 0x0052 (Firmware PR #97), so a
//            peer still on 0x0052 will now hit CMD_POWER_OFF. Also target
//            design: D-FF-latch ESP32 timer-sleeps (latch HELD) instead of
//            powering off; the hard rail-cut is CMD_POWER_OFF (0x0052). The
//            request/response byte layout is otherwise UNCHANGED.
// @since:    [seconds:2 BE] one-shot payload shipped in-2.x on 0x0052 (Firmware
//            PR #97); documented, moved to 0x0053, and error namespace added
//            in 2.1.
export const CMD_DEEP_SLEEP = 0x0053;

// @opcode: 0x0070   @name: CMD_DIRECT_WRITE_START   @dir: host->device
// @request:  UNCOMPRESSED: [0x00][0x70]  (no size, no data; all bytes via 0x71).
//            COMPRESSED:   [0x00][0x70][uncompressed_size:4 LE][first zlib bytes...]
//              -> remaining zlib bytes stream via CMD_DIRECT_WRITE_DATA (0x71).
// @response: [0x00][0x70] (RESP_DIRECT_WRITE_START_ACK) on accept.
// @errors:   [0xFF][0x70] (RESP_DIRECT_WRITE_ERROR path) on setup failure.
// @state:    begins a full-frame image session; a new START aborts any prior one.
// @limits:   START plaintext <= 200 bytes (encrypted: fit within 154 budget).
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_DIRECT_WRITE_START = 0x0070;

// @opcode: 0x0071   @name: CMD_DIRECT_WRITE_DATA   @dir: host->device
// @request:  [0x00][0x71][image_data...]  (chunk of the image / zlib stream)
// @response: [0x00][0x71] (RESP_DIRECT_WRITE_DATA_ACK) per chunk.
// @errors:   [0xFF][0x71] on write/decompress/overflow; for a partial (0x76)
//            session the NACK data byte is an OD_ERR_PARTIAL_* code.
// @state:    must follow a 0x70 or 0x76 START; also carries partial-stream data.
// @limits:   <= 230 bytes (unencrypted) / <= 154 (encrypted).
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_DIRECT_WRITE_DATA = 0x0071;

// @opcode: 0x0072   @name: CMD_DIRECT_WRITE_END   @dir: host->device
// @request:  [0x00][0x72][refresh:1]  (+ optional [new_etag:4 BE]; presence by
//            length). refresh: 0=FULL, 1=FAST/PARTIAL.
// @response: [0x00][0x72] (RESP_DIRECT_WRITE_END_ACK, data complete) THEN an
//            unsolicited refresh notification:
//              [0x00][0x73] RESP_DIRECT_WRITE_REFRESH_SUCCESS (panel updated), or
//              [0x00][0x74] RESP_DIRECT_WRITE_REFRESH_TIMEOUT (refresh timed out).
//            [0xFF][0x72] if the transfer was incomplete (missing bytes / zlib flush).
// @errors:   NACK on incompleteness; refresh reported via 0x73/0x74.
// @state:    finalizes the 0x70 session and triggers the panel refresh.
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs | NRF52811
export const CMD_DIRECT_WRITE_END = 0x0072;

// @opcode: 0x0073   @name: CMD_LED_ACTIVATE   @dir: host->device
// @request:  [0x00][0x73][led_instance:1][flash_config:12]
// @response: [0x00][0x73] (RESP_LED_ACTIVATE_ACK).
// @errors:   [0xFF][0x73] on bad instance / config.
// @state:    session required when security enabled.
// @limits:   flash_config is a fixed 12-byte typed payload.
// @targets:  Firmware | NRF54 | Silabs | NRF52811
// @collision: the RESPONSE byte 0x73 is reused -- see RESP_LED_ACTIVATE_ACK vs
//            RESP_DIRECT_WRITE_REFRESH_SUCCESS below (disambiguate by direction).
export const CMD_LED_ACTIVATE = 0x0073;

// @opcode: 0x0075   @name: CMD_LED_STOP   @dir: host->device
// @request:  [0x00][0x75][led_instance:1]  (stop the LED pattern)
// @response: [0x00][0x75] (RESP_LED_STOP_ACK).
// @errors:   [0xFF][0x75] on bad instance.
// @state:    session required when security enabled.
// @limits:   -
// @targets:  Firmware | NRF54 | Silabs      (NOT NRF52811)
export const CMD_LED_STOP = 0x0075;

// @opcode: 0x0076   @name: CMD_PARTIAL_WRITE_START   @dir: host->device
// @request:  [0x00][0x76][flags:1][old_etag:4 BE][new_etag:4 BE]
//                       [x:2 BE][y:2 BE][width:2 BE][height:2 BE][initial stream...]
//            17-byte fixed header, ALL BIG-ENDIAN (note: PIPE 0x80's partial
//            extension packs the same geometry LITTLE-endian instead). Remaining
//            stream bytes follow via 0x71 DATA; the transfer ends with 0x72.
// @response: [0x00][0x76] on accept (then 0x71 ACKs, then 0x72 END + 0x73/0x74).
// @errors:   [0xFF][0x76][OD_ERR_PARTIAL_*][0x00]  (namespace scoped to 0x76):
//              0x01 OD_ERR_PARTIAL_ETAG_MISMATCH, 0x03 OD_ERR_PARTIAL_RECT_OOB,
//              0x04 OD_ERR_PARTIAL_RECT_ALIGN,     0x05 OD_ERR_PARTIAL_FLAGS,
//              0x06 OD_ERR_PARTIAL_STREAM,         0x07 OD_ERR_PARTIAL_UNSUPPORTED.
//            (0x02 unused.) Any geometry/etag NACK clears the device's
//            displayed_etag. See SECTION 4; do NOT emit OD_ERR_PIPE_START_* here.
// @state:    requires 1bpp panel; x and width must be multiples of 8; old_etag
//            must equal the currently displayed etag.
// @limits:   START plaintext <= 200 bytes.
// @targets:  Firmware | NRF54      (NOT Silabs, NOT NRF52811)
export const CMD_PARTIAL_WRITE_START = 0x0076;

// @opcode: 0x0077   @name: CMD_BUZZER   @dir: host->device
// @request:  [0x00][0x77][buzzer_instance:1][outer_repeats:1][n_patterns:1][patterns...]
// @response: [0x00][0x77] (RESP_BUZZER_ACK).
// @errors:   [0xFF][0x77] on bad instance / config.
// @state:    session required when security enabled.
// @limits:   -
// @targets:  Firmware | NRF54      (NOT Silabs, NOT NRF52811)
export const CMD_BUZZER = 0x0077;

// @opcode: 0x0080   @name: CMD_PIPE_WRITE_START   @dir: host->device
// @request:  10-byte header (22 when partial):
//              [0x00][0x80][ver:1][flags:1][req_window:1][req_ack_every:1]
//                          [client_max_frame:2 LE][total_size:4 LE]
//              --- appended iff flags bit1 (PIPE_FLAG_PARTIAL) ---
//                          [old_etag:4 LE][x:2 LE][y:2 LE][w:2 LE][h:2 LE]
//              ver = PIPE_VERSION (1); flags bit0 = PIPE_FLAG_COMPRESSED (zlib),
//              bit1 = PIPE_FLAG_PARTIAL. total_size = decompressed byte total
//              (partial: plane_size * 2). All pipe fields are LITTLE-endian.
// @response: [0x00][0x80][ver:1][max_window:1][max_ack_every:1]
//                        [max_frame:2 LE][resp_flags:1]
//              resp_flags bit0 = selective-repeat supported, bit1 = partial
//              accepted. Device echoes its negotiated maxima (min-rule applies).
// @errors:   [0xFF][0x80][OD_ERR_PIPE_START_*][0x00]  (namespace scoped to the
//            0x80 START, DISTINCT from the 0x76 OD_ERR_PARTIAL_* set):
//              0x01 OD_ERR_PIPE_START_BAD_HEADER   (bad length or version),
//              0x02 OD_ERR_PIPE_START_UNKNOWN_FLAG,
//              0x03 OD_ERR_PIPE_START_SIZE_MISMATCH,
//              0x05 OD_ERR_PIPE_START_ETAG_MISMATCH        (partial),
//              0x06 OD_ERR_PIPE_START_PARTIAL_UNSUPPORTED,
//              0x07 OD_ERR_PIPE_START_RECT_INVALID          (partial).
//            (0x04 unused.) See SECTION 4; do NOT emit OD_ERR_PARTIAL_* here --
//            0x03/0x05/0x06/0x07 mean different things in the two namespaces.
// @state:    a new START aborts any in-flight transfer; seq resets to 0.
// @limits:   window/ack_every 1..32; frame <= PIPE_MAX_FRAME (244).
// @targets:  Firmware      (NOT NRF54, NOT Silabs, NOT NRF52811)
export const CMD_PIPE_WRITE_START = 0x0080;

// @opcode: 0x0081   @name: CMD_PIPE_WRITE_DATA   @dir: host->device (and the
//          device->host ACK/NACK opcode)
// @request:  [0x00][0x81][seq:1][data...]
//              seq = chunk index mod 256 (reset to 0 by each 0x80 START).
//              When encrypted, [seq][data] is the inner plaintext payload.
// @response: SACK ACK (7 bytes): [0x00][0x81][highest_seen:1][ack_mask:4 LE]
//              mask bit i (LSB first) = chunk (highest_seen-1-i) received;
//              highest_seen is implicitly acked. ACK cadence = negotiated N.
//            NACK (8 bytes, FATAL): [0xFF][0x81][err:1][highest_seen:1][ack_mask:4 LE]
//              err: 0x02 decompress error, 0x03 write/size error, 0x04 protocol.
// @errors:   see NACK above; after a NACK, further 0x81 frames are discarded
//            until the next 0x80 START or disconnect.
// @state:    out-of-order frames buffered in a 33-slot reorder queue; window W.
// @limits:   data <= frame_eff - PIPE_FRAME_OVERHEAD (3); frame_eff <= 244.
// @targets:  Firmware      (NOT NRF54, NOT Silabs, NOT NRF52811)
export const CMD_PIPE_WRITE_DATA = 0x0081;

// @opcode: 0x0082   @name: CMD_PIPE_WRITE_END   @dir: host->device
// @request:  [0x00][0x82][refresh:1]  (+ optional [new_etag:4 BE]; presence by
//            length). Full-frame: refresh 0=FULL,1=FAST. Partial-negotiated:
//            0=FULL,1=FAST,2/absent=PARTIAL.
// @response: a tail-flush SACK [0x00][0x81]... first, then
//              [0x00][0x82] end-ACK, then the refresh notification
//              [0x00][0x73] success or [0x00][0x74] timeout.
//            [0xFF][0x82] if incomplete (a hole remains / byte count short).
// @errors:   NACK [0xFF][0x82] on incompleteness; refresh via 0x73/0x74.
// @state:    client must not send END until every chunk is acked.
// @limits:   -
// @targets:  Firmware      (NOT NRF54, NOT Silabs, NOT NRF52811)
// @collision: 0x0082 is PIPE_WRITE_END here. NFC moved OFF 0x0082 to 0x0083 in
//            protocol v2 precisely to end the historical opcode clash.
export const CMD_PIPE_WRITE_END = 0x0082;

// @opcode: 0x0083   @name: CMD_NFC_ENDPOINT   @dir: host->device
// @request:  [0x00][0x83][sub:1][sub-specific payload...]  where sub =
//              NFC_SUB_READ        0x00 : (no more payload) read the tag.
//              NFC_SUB_WRITE       0x01 : [rec_type:1][len:2 BE][payload:len]
//                                          single-shot write (<= ~120 B app data).
//              NFC_SUB_WRITE_START 0x10 : [rec_type:1][total_len:2 BE]
//                                          begin a chunked write (buffer <= 512 B).
//              NFC_SUB_WRITE_DATA  0x11 : [chunk...]  (append; needs active START)
//              NFC_SUB_WRITE_END   0x12 : (no payload) commit; received==total.
//            rec_type is one of OD_NFC_REC_* (below).
// @response: NOTE the 3rd byte is an NFC SUB-STATUS, a DIFFERENT field from the
//            opcode echo -- it happens to reuse values 0x80/0x81/0x82:
//              READ ok : [0x00][0x83][NFC_STATUS_READ_DATA 0x80][rec_type:1][len:2 BE][data:len]
//              WRITE ok (single / chunk END): [0x00][0x83][NFC_STATUS_WRITE_COMMITTED 0x81]
//              WRITE_START / WRITE_DATA ok  : [0x00][0x83][NFC_STATUS_CHUNK_ACCEPTED 0x82]
// @errors:   [0xFF][0x83][0xFF][NFC_ERR_*] (4-byte NACK; 4th byte is the code):
//              0x01 malformed/short, 0x02 read failed, 0x03 tag write failed,
//              0x04 unknown sub-command, 0x05 invalid rec_type,
//              0x06 bad total_len (0 or >512), 0x07 chunk without active START
//              (or wrong connection), 0x08 chunk overflow past total_len,
//              0x09 END with received != total_len.
// @state:    chunked write is per-connection: START binds the connection; DATA
//            from another connection -> 0x07. Buffer size 512 bytes.
// @limits:   single-write app data threshold ~120 B; chunk buffer 512 B.
// @targets:  NRF54 | Silabs      (NOT Firmware, NOT NRF52811)
// @since:    v2
// @changed:  moved 0x0082 -> 0x0083 in protocol v2 to resolve the collision
//            with CMD_PIPE_WRITE_END. Old 0x0082 NFC frames are now rejected
//            (clean cutover, no alias). The NFC sub-status value 0x82
//            ("chunk accepted") is UNRELATED to the retired 0x0082 opcode --
//            do not confuse the two.
export const CMD_NFC_ENDPOINT = 0x0083;

// ===== Section 2: RESPONSE / STATUS BYTES (8-bit) =====
// A response frame is [status][cmd_echo][data]. The status byte is one of the
// three shared values; cmd_echo is the low byte of the command, and the RESP_*
// echo constants below mirror that low byte.

// Shared status byte (frame position 0).
export const RESP_ACK = 0x00;  // success
export const RESP_NACK = 0xFF;  // failure; data[0] often an error code
export const RESP_AUTH_REQUIRED = 0xFE;  // gated command sent without a live session

// Command-echo bytes (frame position 1) = low byte of the matching CMD_*.
export const RESP_CONFIG_READ = 0x40;
export const RESP_CONFIG_WRITE = 0x41;
export const RESP_CONFIG_CHUNK = 0x42;
export const RESP_FIRMWARE_VERSION = 0x43;
export const RESP_MSD_READ = 0x44;
export const RESP_CONFIG_CLEAR = 0x45;
export const RESP_AUTHENTICATE = 0x50;
export const RESP_ENTER_DFU = 0x51;
export const RESP_POWER_OFF = 0x52;
export const RESP_DEEP_SLEEP = 0x53;

// Direct-write family (Firmware / NRF52811 + shared).
export const RESP_DIRECT_WRITE_START_ACK = 0x70;
export const RESP_DIRECT_WRITE_DATA_ACK = 0x71;
export const RESP_DIRECT_WRITE_END_ACK = 0x72;
export const RESP_DIRECT_WRITE_REFRESH_SUCCESS = 0x73;  // unsolicited device->host: panel refreshed OK
export const RESP_DIRECT_WRITE_REFRESH_TIMEOUT = 0x74;  // unsolicited device->host: refresh timed out
export const RESP_DIRECT_WRITE_ERROR = 0xFF;  // direct-write NACK status (== RESP_NACK)

// LED / buzzer acks.
export const RESP_LED_ACTIVATE_ACK = 0x73;
export const RESP_LED_STOP_ACK = 0x75;
export const RESP_BUZZER_ACK = 0x77;

// NFC endpoint echo byte (was 0x82u in protocol v1; see CMD_NFC_ENDPOINT).
export const RESP_NFC_ENDPOINT = 0x83;

// @collision: RESPONSE byte 0x73 has two meanings, disambiguated by direction
//   and context:
//     RESP_LED_ACTIVATE_ACK             -- a REPLY to CMD_LED_ACTIVATE, framed
//                                          [status][0x73][...]; solicited.
//     RESP_DIRECT_WRITE_REFRESH_SUCCESS -- an UNSOLICITED device->host refresh
//                                          notification following a 0x72/0x82 END.
//   Same byte value, distinct semantics; a client keys off which command it
//   just issued (LED activate vs image END) to interpret the 0x73.

// ===== Section 3: AUTHENTICATE STATUS (3rd byte of a 0x50 response) =====

export const AUTH_STATUS_CHALLENGE = 0x00;
export const AUTH_STATUS_SUCCESS = AUTH_STATUS_CHALLENGE;  // alias: step-2 success == challenge value
export const AUTH_STATUS_FAILED = 0x01;  // wrong key
export const AUTH_STATUS_ALREADY = 0x02;  // already authenticated
export const AUTH_STATUS_NOT_CONFIG = 0x03;  // encryption not configured
export const AUTH_STATUS_RATE_LIMIT = 0x04;  // >=10 attempts / 60 s
export const AUTH_STATUS_ERROR = 0xFF;  // generic error

// ===== Section 4: OPCODE-SCOPED NACK ERROR NAMESPACES =====
// NACK error bytes are opcode-SCOPED, never global: data[0] of a NACK is only
// meaningful once you know the echoed opcode (byte 1). This section holds the
// distinct, PREFIXED error namespaces -- one per handler -- so a byte value can
// be reused with different meanings and stay unambiguous on the wire. The NFC
// namespace lives in SECTION 5 (NFC_ERR_*, the 4th byte of
// [0xFF][0x83][0xFF][err]); it is cross-referenced but NOT redefined here.
//
// SCOPING RULE
//   The 0x76 (OD_ERR_PARTIAL_*) and 0x80-START (OD_ERR_PIPE_START_*) sets below
//   DELIBERATELY REUSE byte values 0x03, 0x05, 0x06 and 0x07 with DIFFERENT
//   meanings. They must NEVER be cross-applied: the echoed opcode is the only
//   thing that disambiguates them. E.g. byte 0x03 == OD_ERR_PARTIAL_RECT_OOB
//   under a 0x76 NACK but OD_ERR_PIPE_START_SIZE_MISMATCH under a 0x80 NACK.
//
// IMPLEMENTATION GUIDANCE (for firmware handlers adopting these constants)
//   - A handler for CMD_PARTIAL_WRITE_START (0x76), and the 0x71/0x72 frames of
//     that partial session, MUST emit ONLY OD_ERR_PARTIAL_* codes.
//   - A handler for CMD_PIPE_WRITE_START (0x80) MUST emit ONLY
//     OD_ERR_PIPE_START_* codes.
//   - The NFC handler (CMD_NFC_ENDPOINT 0x83) MUST emit ONLY NFC_ERR_* codes
//     (SECTION 5).
//   - The CMD_POWER_OFF handler (0x52) MUST emit ONLY OD_ERR_POWER_OFF_*
//     codes (SECTION 4d); the CMD_DEEP_SLEEP handler (0x53) ONLY
//     OD_ERR_DEEP_SLEEP_* codes (SECTION 4c).
//   A code from one namespace must NEVER appear in another handler's NACK. The
//   overlapping raw byte values are intentional and safe ONLY because the echoed
//   opcode scopes them -- pick the constant by which opcode you are answering.
// 4a. PARTIAL-WRITE errors -- scope: CMD_PARTIAL_WRITE_START (0x76) and its
//     0x71 DATA / 0x72 END frames.  NACK frame: [0xFF][0x76][err][0x00].
//     (0x02 is intentionally unused in this set.)

export const OD_ERR_PARTIAL_ETAG_MISMATCH = 0x01;  // old_etag != displayed etag
export const OD_ERR_PARTIAL_RECT_OOB = 0x03;  // rectangle out of panel bounds
export const OD_ERR_PARTIAL_RECT_ALIGN = 0x04;  // x / width not a multiple of 8
export const OD_ERR_PARTIAL_FLAGS = 0x05;  // bad / unsupported flags
export const OD_ERR_PARTIAL_STREAM = 0x06;  // stream / length error
export const OD_ERR_PARTIAL_UNSUPPORTED = 0x07;  // partial write unsupported (e.g. not 1bpp)

// 4b. PIPE-START errors -- scope: CMD_PIPE_WRITE_START (0x80) ONLY.
//     NACK frame: [0xFF][0x80][err][0x00].  DISTINCT namespace from 4a: the
//     shared byte values (0x03/0x05/0x06/0x07) mean different things here.
//     (0x04 is unused in this set.)  Note: the in-flight 0x81 PIPE_WRITE_DATA
//     NACK carries its OWN handler-local err byte (see CMD_PIPE_WRITE_DATA
//     @response) and is not part of this START namespace.
export const OD_ERR_PIPE_START_BAD_HEADER = 0x01;  // bad length or version
export const OD_ERR_PIPE_START_UNKNOWN_FLAG = 0x02;  // unknown flags bit set
export const OD_ERR_PIPE_START_SIZE_MISMATCH = 0x03;  // total_size inconsistent
export const OD_ERR_PIPE_START_ETAG_MISMATCH = 0x05;  // partial: old_etag mismatch
export const OD_ERR_PIPE_START_PARTIAL_UNSUPPORTED = 0x06;  // partial mode not supported
export const OD_ERR_PIPE_START_RECT_INVALID = 0x07;  // partial: invalid rectangle

// 4c. DEEP-SLEEP errors -- scope: CMD_DEEP_SLEEP (0x0053) ONLY.
//     NACK frame: [0xFF][0x53][err][0x00].  Byte values 0x00..0x02 are reused
//     from other namespaces -- scoped by the echoed opcode, as always. Note
//     0x00 IS a valid error code here (a NACK's data[0], never a success
//     marker). CLIENT RULE: 0x01/0x02 mean "rejected, device still AWAKE and
//     reachable"; ONLY 0x00 means deep sleep is unsupported on the target.
//     Never conflate the two classes.
export const OD_ERR_DEEP_SLEEP_UNSUPPORTED = 0x00;  // target has no deep sleep (nRF)
export const OD_ERR_DEEP_SLEEP_DISABLED = 0x01;  // deep_sleep_time_seconds == 0 in config
export const OD_ERR_DEEP_SLEEP_NOT_BATTERY = 0x02;  // power_mode != 1 (mains-powered)

// 4d. POWER-OFF errors -- scope: CMD_POWER_OFF (0x0052) ONLY.
//     NACK frame: [0xFF][0x52][err][0x00].
export const OD_ERR_POWER_OFF_UNSUPPORTED = 0x00;  // no D-FF power latch on this target

// ===== Section 5: NFC SUB-PROTOCOL (rides CMD_NFC_ENDPOINT 0x0083) =====

// NFC sub-command (request payload byte 0).
export const NFC_SUB_READ = 0x00;
export const NFC_SUB_WRITE = 0x01;  // single-shot write
export const NFC_SUB_WRITE_START = 0x10;  // begin chunked write
export const NFC_SUB_WRITE_DATA = 0x11;  // append chunk
export const NFC_SUB_WRITE_END = 0x12;  // commit chunked write

// NFC record types (rec_type field). Wire bytes an agent must ground on --
// kept here (not in per-repo constants) for that reason.
export const OD_NFC_REC_TEXT = 0;
export const OD_NFC_REC_URI = 1;
export const OD_NFC_REC_WELL_KNOWN_RAW = 2;
export const OD_NFC_REC_MIME = 3;
export const OD_NFC_REC_RAW_NDEF = 4;

// NFC IC (tag chip) selector.
export const OD_NFC_IC_AUTO = 0;
export const OD_NFC_IC_TNB132M = 1;

// NFC response SUB-STATUS (3rd byte of a 0x83 response, AFTER the
// [status][echo] pair). This is a DIFFERENT field from the opcode echo; the
// value 0x82 here means "chunk accepted" and is UNRELATED to the retired
// 0x0082 NFC opcode.
export const NFC_STATUS_READ_DATA = 0x80;  // [.. 0x80][rec_type][len:2 BE][data]
export const NFC_STATUS_WRITE_COMMITTED = 0x81;  // single write / chunk END committed
export const NFC_STATUS_CHUNK_ACCEPTED = 0x82;  // WRITE_START or WRITE_DATA accepted

// NFC NACK error codes (4th byte of [0xFF][0x83][0xFF][err]).
export const NFC_ERR_MALFORMED = 0x01;  // malformed / short frame
export const NFC_ERR_READ_FAILED = 0x02;  // tag read failed
export const NFC_ERR_TAG_WRITE_FAILED = 0x03;  // tag write failed
export const NFC_ERR_UNKNOWN_SUBCMD = 0x04;  // unknown sub-command byte
export const NFC_ERR_INVALID_REC_TYPE = 0x05;  // rec_type not in OD_NFC_REC_*
export const NFC_ERR_BAD_TOTAL_LEN = 0x06;  // total_len == 0 or > 512
export const NFC_ERR_CHUNK_NO_START = 0x07;  // DATA/END without active START (or wrong connection)
export const NFC_ERR_CHUNK_OVERFLOW = 0x08;  // chunk would exceed total_len
export const NFC_ERR_END_LEN_MISMATCH = 0x09;  // END with received != total_len

// ===== Section 6: PIPE SLIDING-WINDOW WIRE CONSTANTS (0x0080..0x0082) =====

export const PIPE_VERSION = 0x01;  // carried in 0x80 request/response ver field
export const PIPE_FLAG_COMPRESSED = 0x01;  // flags bit0: streamed bytes are zlib-compressed
export const PIPE_FLAG_PARTIAL = 0x02;  // flags bit1: partial-region refresh
export const PIPE_MAX_FRAME = 244;  // max on-wire frame size (GATT write ceiling)
export const PIPE_FRAME_OVERHEAD = 3;  // plaintext 0x81 header: cmd(2) + seq(1)
export const PIPE_ACK_MASK_BITS = 32;  // SACK ack_mask width in bits
export const OD_PIPE_MAX_PAYLOAD = 244;  // max payload buffer used by pipe/NFC responses

// ===== Section 7: CHUNK / SIZE BUDGETS =====

export const OD_BLE_MAX_FRAME = 256;  // max BLE ATT MTU: opcode(1) + handle(2) + value, inclusive; usable single-write value is OD_BLE_MAX_FRAME - 3 = 253 (BLE peer of OD_LAN_MAX_FRAME)
export const CONFIG_CHUNK_SIZE = 200;  // max config data bytes per chunk
export const CONFIG_CHUNK_SIZE_WITH_PREFIX = 202;  // first chunked CONFIG_WRITE payload: total(2) + 200
export const MAX_CONFIG_CHUNKS = 20;  // upper bound on config chunks in a write
export const MAX_RESPONSE_DATA_SIZE = 100;  // max bytes in a single notification frame

// ===== Section 8: ENCRYPTION ENVELOPE (wire-visible sizes) =====
// Envelope: [cmd:2 BE][nonce:16][ciphertext][tag:12]; inner plaintext is
// [len:1][payload]; AAD = the 2 opcode bytes; AEAD = AES-128-CCM.
// NOTE: this AES-CCM envelope applies to the BLE transport (and plaintext LAN).
// On the TLS-PSK LAN channel it MUST NOT be applied -- see SECTION 9 rule 4
// (origin-gated decrypt: the dispatcher decides by the frame's ORIGIN transport,
// not the global isEncryptionEnabled() flag).

export const BLE_CMD_HEADER_SIZE = 2;  // opcode bytes (also the AAD length)
export const ENCRYPTION_NONCE_SIZE = 16;  // envelope nonce (CCM nonce = bytes 3..15)
export const ENCRYPTION_TAG_SIZE = 12;  // CCM authentication tag length

// ===== Section 9: NETWORK TRANSPORT (LAN) =====
// The OpenDisplay command set can also ride a LAN (WiFi) TCP transport, in
// addition to BLE. This section is the implement-from-this-file-alone contract
// for that transport. It is ADDITIVE: it introduces no new opcodes and no
// struct fields -- the same SECTION 1 commands / SECTION 2 responses travel
// inside a framed TCP stream. BLE-only peers are unaffected.
//
// FRAME FORMAT
//   Each application message is length-prefixed on the TCP byte stream:
//       [len:2 LE][payload]
//     - len     : 16-bit LITTLE-ENDIAN byte count of the payload that follows.
//     - payload : one command/response frame, EXACTLY as on BLE but WITHOUT the
//                 GATT MTU segmentation -- i.e. [cmd_hi][cmd_lo][payload...] for
//                 a request, [status][cmd_echo][data...] for a response.
//     - The complete WIRE frame (2-byte prefix + payload) MUST NOT exceed
//       OD_LAN_MAX_FRAME (4096); equivalently, valid payload length is
//       1..OD_LAN_MAX_PAYLOAD (= OD_LAN_MAX_FRAME - 2 = 4094). len == 0 is
//       invalid; len > OD_LAN_MAX_PAYLOAD MUST be rejected and the connection
//       dropped. Capping the WIRE frame (not the payload) at a power of two is
//       deliberate: receiver buffers sized in wire bytes divide evenly.
//   A reader MUST handle partial and coalesced TCP reads: read exactly 2 bytes
//   for len, then exactly len bytes for the payload.
//
// NORMATIVE RULES
//   (1) MODE / PORT SELECTION -- one channel, chosen by the firmware predicate
//       isEncryptionEnabled() (SecurityConfig.encryption_enabled == 1 AND a
//       non-zero 16-byte master key):
//         - false -> PLAINTEXT framed TCP on the configured WifiConfig.server_port
//                    (default OD_LAN_TCP_PORT if server_port == 0) ONLY.
//         - true  -> TLS-PSK on the DERIVED port server_port + 1
//                    (default OD_LAN_TLS_PORT == OD_LAN_TCP_PORT + 1) ONLY.
//       A flag == 1 with a blank/all-zero key is NOT "encrypted" -- it falls back
//       to plaintext. The two modes are MUTUALLY EXCLUSIVE: exactly one port is
//       served at a time. Clients learn the live port from the mDNS SRV record
//       (see rule 6) or authoritatively via CONFIG_READ (0x26): read server_port,
//       add 1 for the TLS port.
//   (2) NO PIPE ON LAN -- the sliding-window image PIPE (0x0080 / 0x0081 / 0x0082,
//       SECTION 6) MUST NOT be used on this transport; TCP already provides
//       ordered, reliable, flow-controlled delivery. Stream image data via
//       DIRECT_WRITE with chunks of at most OD_LAN_MAX_PAYLOAD - 2 data bytes.
//   (3) ONE CLIENT AT A TIME -- the device serves a single network client; a new
//       connection EVICTS the prior one. Clients MAY stay persistently connected;
//       the server drops a client only after OD_LAN_READ_TIMEOUT_S with no
//       traffic. Any valid command resets the idle timer.
//   (4) TLS-PSK / NO DOUBLE ENCRYPTION -- on the encrypted channel the PSK is
//       DERIVED from the SecurityConfig master key via the existing CMAC KDF
//       (the same key derivation used elsewhere); prefer an ECDHE-PSK
//       ciphersuite. The TLS handshake IS the authentication: the app-layer
//       AUTHENTICATE (0x50) exchange is NOT used on this port. There is NO double
//       encryption -- INSIDE the TLS tunnel, frames are PLAINTEXT opcode frames
//       and the app-layer AES-CCM envelope (SECTION 8) MUST NOT be applied. The
//       dispatcher MUST gate app-layer decrypt/encrypt on the frame's ORIGIN
//       transport (TLS-origin bypasses the AEAD envelope; BLE-origin keeps it),
//       NOT on the global isEncryptionEnabled() flag.
//   (5) IDENTITY -- the BLE MAC is the cross-transport identity anchor. The BLE
//       manufacturer-specific data (MSD) is VOLATILE telemetry, NOT identity.
//       Correlate a discovered LAN device to its BLE identity via the `mac` mDNS
//       TXT key (rule 6); the IP address is only a locator, never an identity.
//   (6) DISCOVERY -- mDNS / DNS-SD. Service OD_LAN_MDNS_SERVICE
//       ("_opendisplay._tcp"; FQDN "_opendisplay._tcp.local."). TXT record keys:
//         mac : REQUIRED. The advertised BLE address, lowercase colon-separated
//               (e.g. "aa:bb:cc:dd:ee:ff") -- this is the ADVERTISED BLE address,
//               NOT the eFuse / WiFi MAC.
//         tls : REQUIRED. "0" or "1"; mirrors isEncryptionEnabled() (1 = the
//               served channel is TLS-PSK on server_port + 1).
//         fw  : RECOMMENDED. Firmware version "major.minor".
//         cm  : RECOMMENDED. communication_modes, 2 lowercase hex digits.
//         id  : OPTIONAL. device_id, 8 hex digits.
//         pv  : OPTIONAL. protocol version (e.g. "2.2").
//         msd : EXISTING. 28 lowercase hex digits of volatile telemetry; throttle
//               republish to >= 400 ms.
//       The SRV record port MUST equal the ACTIVE mode's port: server_port when
//       tls == 0, server_port + 1 when tls == 1. On a config change that flips
//       isEncryptionEnabled(), the device MUST re-register the service on the new
//       port (and update the `tls` TXT) so clients converge on the live channel.

export const OD_LAN_TCP_PORT = 2446;  // DEFAULT plaintext port; live port = WifiConfig.server_port (this default if 0)
export const OD_LAN_TLS_PORT = 2447;  // DEFAULT TLS-PSK port; DERIVED live = server_port + 1 (== OD_LAN_TCP_PORT + 1)
export const OD_LAN_MAX_FRAME = 4096;  // max WIRE frame: [len:2 LE] prefix + payload, inclusive
export const OD_LAN_MAX_PAYLOAD = 4094;  // max payload bytes after the prefix; == OD_LAN_MAX_FRAME - 2
export const OD_LAN_MDNS_SERVICE = "_opendisplay._tcp";  // DNS-SD service; FQDN "_opendisplay._tcp.local."
export const OD_LAN_READ_TIMEOUT_S = 30;  // idle timeout: drop a client after this many seconds of no traffic

