// @generated by tools/gen_js_structs.py -- DO NOT EDIT BY HAND.
// Source: opendisplay_structs.h (OD_STRUCTS_VERSION 2.0)
// Source SHA-256: 238ada72ffc12ea242428547884d141f94e048cb6d6e01ceeb937dbdea50cfe7
// Regenerate: tools/gen_js_structs.py --write   (CI drift gate: --check)
//
// TypeScript declarations for opendisplay_structs.js. Value enums are frozen
// name->value objects (exact literal member types); bitfield flags are literal-typed
// consts; packed structs are classes with a DataView-backed pack()/unpack().

// ===== Loose wire constants =====
export declare const OD_STRUCTS_VERSION_MAJOR: 2;
export declare const OD_STRUCTS_VERSION_MINOR: 0;
export declare const OD_STRUCTS_VERSION_STR: "2.0";
export declare const OD_CONFIG_VERSION: 1;
export declare const OD_CONFIG_MINOR_VERSION: 4;
export declare const OD_CONFIG_CRC_POLY: 0x1021;
export declare const OD_CONFIG_CRC_INIT: 0xFFFF;
export declare const OD_PIN_UNUSED: 0xFF;

// ===== Packed-struct runtime =====

/** Input accepted by every struct's static unpack(). */
export type WireBytes = Uint8Array | ArrayLike<number> | ArrayBuffer;

/** Base for every packed wire struct: DataView-backed pack()/unpack(). */
export declare class _PackedStruct {
  /** Serialize to exactly SIZE wire bytes (arrays zero-padded; over-long arrays throw). */
  pack(): Uint8Array;
  /** Deserialize SIZE wire bytes into an instance (extra trailing bytes ignored). */
  static unpack<T extends _PackedStruct>(this: new (fields?: any) => T, data: WireBytes): T;
  static readonly SIZE: number;
}

// ===== Value enums =====

export declare const ConfigPacketType: Readonly<{
  OD_PKT_SYSTEM: 1;
  OD_PKT_MANUFACTURER: 2;
  OD_PKT_POWER: 4;
  OD_PKT_DISPLAY: 32;
  OD_PKT_LED: 33;
  OD_PKT_SENSOR: 35;
  OD_PKT_DATA_BUS: 36;
  OD_PKT_BINARY_INPUT: 37;
  OD_PKT_WIFI: 38;
  OD_PKT_SECURITY: 39;
  OD_PKT_TOUCH: 40;
  OD_PKT_BUZZER: 41;
  OD_PKT_NFC: 42;
  OD_PKT_FLASH: 43;
  OD_PKT_DATA_EXTENDED: 44;
}>;

export declare const ActiveLevel: Readonly<{
  OD_ACTIVE_LOW: 0;
  OD_ACTIVE_HIGH: 1;
}>;

export declare const ICType: Readonly<{
  OD_IC_TYPE_NRF52840: 1;
  OD_IC_TYPE_ESP32S3: 2;
  OD_IC_TYPE_ESP32C3: 3;
  OD_IC_TYPE_ESP32C6: 4;
  OD_IC_TYPE_NRF52811: 5;
  OD_IC_TYPE_EFR32BG22C222F352GM40: 6;
  OD_IC_TYPE_NRF54L15: 7;
  OD_IC_TYPE_NRF54LM20: 8;
}>;

export declare const ManufacturerId: Readonly<{
  OD_MANUFACTURER_DIY: 0;
  OD_MANUFACTURER_SEEED: 1;
  OD_MANUFACTURER_WAVESHARE: 2;
  OD_MANUFACTURER_SOL: 3;
  OD_MANUFACTURER_OPENDISPLAY: 4;
}>;

export declare const PowerMode: Readonly<{
  OD_POWER_MODE_BATTERY: 1;
  OD_POWER_MODE_USB: 2;
  OD_POWER_MODE_SOLAR: 3;
}>;

export declare const CapacityEstimator: Readonly<{
  OD_CAPACITY_EST_LI_ION: 1;
  OD_CAPACITY_EST_LIFEPO4: 2;
  OD_CAPACITY_EST_SUPERCAP: 3;
  OD_CAPACITY_EST_LITHIUM_PRIMARY: 4;
  OD_CAPACITY_EST_SEEED_LI_ION: 5;
}>;

export declare const DisplayTechnology: Readonly<{
  OD_DISPLAY_TECH_UNDEFINED: 0;
  OD_DISPLAY_TECH_E_PAPER: 1;
  OD_DISPLAY_TECH_LCD: 2;
  OD_DISPLAY_TECH_LED_MATRIX: 3;
}>;

export declare const Rotation: Readonly<{
  OD_ROTATION_0: 0;
  OD_ROTATION_90: 1;
  OD_ROTATION_180: 2;
  OD_ROTATION_270: 3;
}>;

export declare const PartialUpdateSupport: Readonly<{
  OD_PARTIAL_UPDATE_NONE: 0;
  OD_PARTIAL_UPDATE_SUPPORTED: 1;
  OD_PARTIAL_UPDATE_FULL_FRAME: 2;
}>;

export declare const ColorScheme: Readonly<{
  OD_COLOR_SCHEME_MONO: 0;
  OD_COLOR_SCHEME_BWR: 1;
  OD_COLOR_SCHEME_BWY: 2;
  OD_COLOR_SCHEME_BWRY: 3;
  OD_COLOR_SCHEME_BWGBRY: 4;
  OD_COLOR_SCHEME_GRAY4: 5;
  OD_COLOR_SCHEME_GRAY16: 6;
  OD_COLOR_SCHEME_SEVEN_COLOR: 7;
  OD_COLOR_SCHEME_BWGBRY_SPLIT: 8;
  OD_COLOR_SCHEME_RGB565: 100;
  OD_COLOR_SCHEME_RGB888: 101;
  OD_COLOR_SCHEME_RGB16BPC: 102;
}>;

export declare const PanelIC: Readonly<{
  OD_PANEL_IC_EP_PANEL_UNDEFINED: 0;
  OD_PANEL_IC_EP42_400X300: 1;
  OD_PANEL_IC_EP42B_400X300: 2;
  OD_PANEL_IC_EP213_122X250: 3;
  OD_PANEL_IC_EP213B_122X250: 4;
  OD_PANEL_IC_EP293_128X296: 5;
  OD_PANEL_IC_EP294_128X296: 6;
  OD_PANEL_IC_EP295_128X296: 7;
  OD_PANEL_IC_EP295_128X296_4GRAY: 8;
  OD_PANEL_IC_EP266_152X296: 9;
  OD_PANEL_IC_EP102_80X128: 10;
  OD_PANEL_IC_EP27B_176X264: 11;
  OD_PANEL_IC_EP29R_128X296: 12;
  OD_PANEL_IC_EP122_192X176: 13;
  OD_PANEL_IC_EP154R_152X152: 14;
  OD_PANEL_IC_EP42R_400X300: 15;
  OD_PANEL_IC_EP42R2_400X300: 16;
  OD_PANEL_IC_EP37_240X416: 17;
  OD_PANEL_IC_EP37B_240X416: 18;
  OD_PANEL_IC_EP213_104X212: 19;
  OD_PANEL_IC_EP75_800X480: 20;
  OD_PANEL_IC_EP75_800X480_4GRAY: 21;
  OD_PANEL_IC_EP75_800X480_4GRAY_V2: 22;
  OD_PANEL_IC_EP29_128X296: 23;
  OD_PANEL_IC_EP29_128X296_4GRAY: 24;
  OD_PANEL_IC_EP213R_122X250: 25;
  OD_PANEL_IC_EP154_200X200: 26;
  OD_PANEL_IC_EP154B_200X200: 27;
  OD_PANEL_IC_EP266YR_184X360: 28;
  OD_PANEL_IC_EP29YR_128X296: 29;
  OD_PANEL_IC_EP29YR_168X384: 30;
  OD_PANEL_IC_EP583_648X480: 31;
  OD_PANEL_IC_EP296_128X296: 32;
  OD_PANEL_IC_EP26R_152X296: 33;
  OD_PANEL_IC_EP73_800X480: 34;
  OD_PANEL_IC_EP73_SPECTRA_800X480: 35;
  OD_PANEL_IC_EP74R_640X384: 36;
  OD_PANEL_IC_EP583R_600X448: 37;
  OD_PANEL_IC_EP75R_800X480: 38;
  OD_PANEL_IC_EP426_800X480: 39;
  OD_PANEL_IC_EP426_800X480_4GRAY: 40;
  OD_PANEL_IC_EP29R2_128X296: 41;
  OD_PANEL_IC_EP41_640X400: 42;
  OD_PANEL_IC_EP81_SPECTRA_1024X576: 43;
  OD_PANEL_IC_EP7_960X640: 44;
  OD_PANEL_IC_EP213R2_122X250: 45;
  OD_PANEL_IC_EP29Z_128X296: 46;
  OD_PANEL_IC_EP29Z_128X296_4GRAY: 47;
  OD_PANEL_IC_EP213Z_122X250: 48;
  OD_PANEL_IC_EP213Z_122X250_4GRAY: 49;
  OD_PANEL_IC_EP154Z_152X152: 50;
  OD_PANEL_IC_EP579_792X272: 51;
  OD_PANEL_IC_EP213YR_122X250: 52;
  OD_PANEL_IC_EP37YR_240X416: 53;
  OD_PANEL_IC_EP35YR_184X384: 54;
  OD_PANEL_IC_EP397YR_800X480: 55;
  OD_PANEL_IC_EP154YR_200X200: 56;
  OD_PANEL_IC_EP266YR2_184X360: 57;
  OD_PANEL_IC_EP42YR_400X300: 58;
  OD_PANEL_IC_EP75_800X480_GEN2: 59;
  OD_PANEL_IC_EP75_800X480_4GRAY_GEN2: 60;
  OD_PANEL_IC_EP215YR_160X296: 61;
  OD_PANEL_IC_EP1085_1360X480: 62;
  OD_PANEL_IC_EP31_240X320: 63;
  OD_PANEL_IC_EP75YR_800X480: 64;
  OD_PANEL_IC_EP133A_SPECTRA_1200X1600: 66;
  OD_PANEL_IC_EP154_200X200_4GRAY: 67;
  OD_PANEL_IC_EP42B_400X300_4GRAY: 68;
  OD_PANEL_IC_EP397_800X480: 69;
  OD_PANEL_IC_EP397_800X480_4GRAY: 70;
  OD_PANEL_IC_EP368_792X528: 71;
  OD_PANEL_IC_EP368_792X528_4GRAY: 72;
  OD_PANEL_IC_EP213ZZ_122X250: 73;
  OD_PANEL_IC_EP40_SPECTRA_400X600: 74;
  OD_PANEL_IC_EP27_176X264: 75;
  OD_PANEL_IC_EP27_176X264_4GRAY: 76;
  OD_PANEL_IC_UC8176_420_BW: 1000;
  OD_PANEL_IC_SSD1619_420_BWR: 1001;
  OD_PANEL_IC_UC8176_420_BWR: 1002;
  OD_PANEL_IC_SSD1619_420_BW: 1003;
  OD_PANEL_IC_JD79668_420_BWRY: 1004;
  OD_PANEL_IC_UC8179_750_BW: 1005;
  OD_PANEL_IC_UC8179_750_BWR: 1006;
  OD_PANEL_IC_UC8159_750_LOW_BW: 1007;
  OD_PANEL_IC_UC8159_750_LOW_BWR: 1008;
  OD_PANEL_IC_SSD1677_750_HD_BW: 1009;
  OD_PANEL_IC_SSD1677_750_HD_BWR: 1010;
  OD_PANEL_IC_JD79665_750_BWRY: 1011;
  OD_PANEL_IC_JD79665_583_BWRY: 1012;
  OD_PANEL_IC_UC8151_029_BW: 1013;
  OD_PANEL_IC_UC8151_029_BWR: 1014;
  OD_PANEL_IC_SSD1619_029_BW: 1015;
  OD_PANEL_IC_SSD1619_029_BWR: 1016;
  OD_PANEL_IC_SSD1619_016_BW: 1017;
  OD_PANEL_IC_SSD1619_016_BWR: 1018;
  OD_PANEL_IC_SSD1619_022_BW: 1019;
  OD_PANEL_IC_SSD1619_022_BWR: 1020;
  OD_PANEL_IC_SSD1619_026_BW: 1021;
  OD_PANEL_IC_SSD1619_026_BWR: 1022;
  OD_PANEL_IC_UC8151_027_BW: 1023;
  OD_PANEL_IC_UC8151_027_BWR: 1024;
  OD_PANEL_IC_UC43_430_BW: 1025;
  OD_PANEL_IC_UC43_430_BWR: 1026;
  OD_PANEL_IC_SSD1619_013_BW: 1027;
  OD_PANEL_IC_SSD1619_013_BWR: 1028;
  OD_PANEL_IC_SSD1619_022_LITE_BW: 1029;
  OD_PANEL_IC_SSD1619_022_LITE_BWR: 1030;
  OD_PANEL_IC_ED103TC2_1872X1404: 3000;
  OD_PANEL_IC_ED103TC2_1872X1404_4GRAY: 3001;
}>;

export declare const LedType: Readonly<{
  OD_LED_TYPE_RGB: 0;
  OD_LED_TYPE_SINGLE: 1;
  OD_LED_TYPE_RY: 2;
  OD_LED_TYPE_FOUR_SEPARATE: 3;
}>;

export declare const SensorType: Readonly<{
  OD_SENSOR_TYPE_TEMPERATURE: 1;
  OD_SENSOR_TYPE_HUMIDITY: 2;
  OD_SENSOR_TYPE_AXP2101: 3;
  OD_SENSOR_TYPE_SHT40: 4;
  OD_SENSOR_TYPE_BQ27220: 5;
}>;

export declare const BusType: Readonly<{
  OD_BUS_TYPE_I2C: 1;
  OD_BUS_TYPE_SPI: 2;
}>;

export declare const InputType: Readonly<{
  OD_INPUT_TYPE_BUTTON: 1;
  OD_INPUT_TYPE_SWITCH: 2;
}>;

export declare const InputDisplayAs: Readonly<{
  OD_INPUT_DISPLAY_AS_BUTTON: 1;
  OD_INPUT_DISPLAY_AS_SWITCH: 2;
}>;

export declare const WifiEncryptionType: Readonly<{
  OD_WIFI_ENC_NONE: 0;
  OD_WIFI_ENC_WEP: 1;
  OD_WIFI_ENC_WPA: 2;
  OD_WIFI_ENC_WPA2: 3;
  OD_WIFI_ENC_WPA3: 4;
}>;

export declare const TouchIcType: Readonly<{
  OD_TOUCH_IC_NONE: 0;
  OD_TOUCH_IC_GT911: 1;
}>;

export declare const NfcFieldDetectMode: Readonly<{
  OD_NFC_FIELD_DETECT_DISABLED: 0;
  OD_NFC_FIELD_DETECT_GPIO_LEVEL: 1;
  OD_NFC_FIELD_DETECT_IRQ_LATCHED: 2;
}>;

export declare const FlashIcType: Readonly<{
  OD_FLASH_IC_AUTO: 0;
}>;

// ===== Bitfield groups =====
export declare const OD_COMM_MODE_BLE: 1;
export declare const OD_COMM_MODE_OEPL: 2;
export declare const OD_COMM_MODE_WIFI: 4;
export declare const OD_DEVICE_FLAG_PWR_PIN: 1;
export declare const OD_DEVICE_FLAG_XIAO_INIT: 2;
export declare const OD_DEVICE_FLAG_WS_PP_INIT: 4;
export declare const OD_DEVICE_FLAG_PWR_LATCH: 8;
export declare const OD_DEVICE_FLAG_PWR_LATCH_DFF: 16;
export declare const OD_SLEEP_FLAG_BUTTON_WAKE_DISABLE: 1;
export declare const OD_BATTERY_SENSE_FLAG_ENABLE_INVERTED: 1;
export declare const OD_CHARGER_FLAG_ENABLE_ACTIVE_LOW: 1;
export declare const OD_CHARGER_FLAG_STATE_ACTIVE_LOW: 2;
export declare const OD_TRANSMISSION_MODE_STREAMING_DECOMPRESSION: 1;
export declare const OD_TRANSMISSION_MODE_ZIP: 2;
export declare const OD_TRANSMISSION_MODE_G5: 4;
export declare const OD_TRANSMISSION_MODE_DIRECT_WRITE: 8;
export declare const OD_TRANSMISSION_MODE_PIPE_WRITE: 16;
export declare const OD_TRANSMISSION_MODE_RESERVED_5: 32;
export declare const OD_TRANSMISSION_MODE_RESERVED_6: 64;
export declare const OD_TRANSMISSION_MODE_CLEAR_ON_BOOT: 128;
export declare const OD_LED_FLAG_LED1_INVERT: 1;
export declare const OD_LED_FLAG_LED2_INVERT: 2;
export declare const OD_LED_FLAG_LED3_INVERT: 4;
export declare const OD_LED_FLAG_LED4_INVERT: 8;
export declare const OD_SECURITY_FLAG_REWRITE_ALLOWED: 1;
export declare const OD_SECURITY_FLAG_SHOW_KEY_ON_SCREEN: 2;
export declare const OD_SECURITY_FLAG_RESET_PIN_ENABLED: 4;
export declare const OD_SECURITY_FLAG_RESET_PIN_POLARITY: 8;
export declare const OD_SECURITY_FLAG_RESET_PIN_PULLUP: 16;
export declare const OD_SECURITY_FLAG_RESET_PIN_PULLDOWN: 32;
export declare const OD_TOUCH_FLAG_INVERT_X: 1;
export declare const OD_TOUCH_FLAG_INVERT_Y: 2;
export declare const OD_TOUCH_FLAG_SWAP_XY: 4;
export declare const OD_BUZZER_FLAG_ENABLE_ACTIVE_HIGH: 1;
export declare const OD_NFC_FLAG_ENABLED: 1;
export declare const OD_FLASH_FLAG_ENABLED: 1;
export declare const OD_MSD_STATUS_BATTERY_VOLTAGE_BIT8: 1;
export declare const OD_MSD_STATUS_REBOOT_FLAG: 2;
export declare const OD_MSD_STATUS_CONNECTION_REQUESTED: 4;
export declare const OD_MSD_STATUS_RESERVED_3: 8;
export declare const OD_MSD_STATUS_MAIN_LOOP_COUNTER_SHIFT: 4;
export declare const OD_MSD_STATUS_MAIN_LOOP_COUNTER_MASK: 0xF0;

// ===== Cross-header bindings (defined in opendisplay_protocol.js) =====
// @enum OD_NFC_IC_*: OD_NFC_IC_AUTO=0, OD_NFC_IC_TNB132M=1
// @bits PIPE_FLAG_*: PIPE_FLAG_COMPRESSED=1, PIPE_FLAG_PARTIAL=2

// ===== Packed structs =====

export declare class OuterPacketHeader extends _PackedStruct {
  length: number;
  version: number;
  static readonly SIZE: 3;
  constructor(fields?: Partial<OuterPacketHeader>);
}

export declare class SinglePacketHeader extends _PackedStruct {
  number: number;
  id: number;
  static readonly SIZE: 2;
  constructor(fields?: Partial<SinglePacketHeader>);
}

export declare class SystemConfig extends _PackedStruct {
  ic_type: number;
  communication_modes: number;
  device_flags: number;
  pwr_pin: number;
  reserved: Uint8Array;
  pwr_pin_2: number;
  pwr_pin_3: number;
  static readonly SIZE: 22;
  static readonly PACKET_ID: 0x01;
  constructor(fields?: Partial<SystemConfig>);
}

export declare class ManufacturerData extends _PackedStruct {
  manufacturer_id: number;
  board_type: number;
  board_revision: number;
  simple_config_driver_index: number;
  simple_config_display_index: number;
  simple_config_power_index: number;
  simple_config_configured_at: Uint8Array;
  reserved: Uint8Array;
  static readonly SIZE: 22;
  static readonly PACKET_ID: 0x02;
  constructor(fields?: Partial<ManufacturerData>);
}

export declare class PowerOption extends _PackedStruct {
  power_mode: number;
  battery_capacity_mah: Uint8Array;
  sleep_timeout_ms: number;
  tx_power: number;
  sleep_flags: number;
  battery_sense_pin: number;
  battery_sense_enable_pin: number;
  battery_sense_flags: number;
  capacity_estimator: number;
  voltage_scaling_factor: number;
  deep_sleep_current_ua: number;
  deep_sleep_time_seconds: number;
  charge_enable_pin: number;
  charge_state_pin: number;
  charger_flags: number;
  min_wake_time_seconds: number;
  screen_timeout_seconds: number;
  reserved: Uint8Array;
  static readonly SIZE: 30;
  static readonly PACKET_ID: 0x04;
  constructor(fields?: Partial<PowerOption>);
}

export declare class DisplayConfig extends _PackedStruct {
  instance_number: number;
  display_technology: number;
  panel_ic_type: number;
  pixel_width: number;
  pixel_height: number;
  active_width_mm: number;
  active_height_mm: number;
  legacy_tag_type: number;
  rotation: number;
  reset_pin: number;
  busy_pin: number;
  dc_pin: number;
  cs_pin: number;
  data_pin: number;
  partial_update_support: number;
  color_scheme: number;
  transmission_modes: number;
  clk_pin: number;
  cs_pin_2: number;
  reserved_pin_3: number;
  reserved_pin_4: number;
  reserved_pin_5: number;
  reserved_pin_6: number;
  reserved_pin_7: number;
  reserved_pin_8: number;
  full_update_mC: number;
  reserved: Uint8Array;
  static readonly SIZE: 46;
  static readonly PACKET_ID: 0x20;
  constructor(fields?: Partial<DisplayConfig>);
}

export declare class LedConfig extends _PackedStruct {
  instance_number: number;
  led_type: number;
  led_1_r: number;
  led_2_g: number;
  led_3_b: number;
  led_4: number;
  led_flags: number;
  reserved: Uint8Array;
  static readonly SIZE: 22;
  static readonly PACKET_ID: 0x21;
  constructor(fields?: Partial<LedConfig>);
}

export declare class SensorData extends _PackedStruct {
  instance_number: number;
  sensor_type: number;
  bus_id: number;
  i2c_addr_7bit: number;
  msd_data_start_byte: number;
  reserved: Uint8Array;
  static readonly SIZE: 30;
  static readonly PACKET_ID: 0x23;
  constructor(fields?: Partial<SensorData>);
}

export declare class DataBus extends _PackedStruct {
  instance_number: number;
  bus_type: number;
  pin_1: number;
  pin_2: number;
  pin_3: number;
  pin_4: number;
  pin_5: number;
  pin_6: number;
  pin_7: number;
  bus_speed_hz: number;
  bus_flags: number;
  pullups: number;
  pulldowns: number;
  reserved: Uint8Array;
  static readonly SIZE: 30;
  static readonly PACKET_ID: 0x24;
  constructor(fields?: Partial<DataBus>);
}

export declare class BinaryInputs extends _PackedStruct {
  instance_number: number;
  input_type: number;
  display_as: number;
  input_pin_1: number;
  input_pin_2: number;
  input_pin_3: number;
  input_pin_4: number;
  input_pin_5: number;
  input_pin_6: number;
  input_pin_7: number;
  input_pin_8: number;
  pins_used: number;
  invert: number;
  pullups: number;
  pulldowns: number;
  button_data_byte_index: number;
  power_off_flags: number;
  power_off_hold_sec: number;
  reserved: Uint8Array;
  static readonly SIZE: 30;
  static readonly PACKET_ID: 0x25;
  constructor(fields?: Partial<BinaryInputs>);
}

export declare class WifiConfig extends _PackedStruct {
  ssid: Uint8Array;
  password: Uint8Array;
  encryption_type: number;
  server_host: Uint8Array;
  server_port: number;
  reserved: Uint8Array;
  static readonly SIZE: 160;
  static readonly PACKET_ID: 0x26;
  constructor(fields?: Partial<WifiConfig>);
}

export declare class SecurityConfig extends _PackedStruct {
  encryption_enabled: number;
  encryption_key: Uint8Array;
  session_timeout_seconds: number;
  flags: number;
  reset_pin: number;
  reserved: Uint8Array;
  static readonly SIZE: 64;
  static readonly PACKET_ID: 0x27;
  constructor(fields?: Partial<SecurityConfig>);
}

export declare class TouchController extends _PackedStruct {
  instance_number: number;
  touch_ic_type: number;
  bus_id: number;
  i2c_addr_7bit: number;
  int_pin: number;
  rst_pin: number;
  display_instance: number;
  flags: number;
  poll_interval_ms: number;
  touch_data_start_byte: number;
  enable_pin: number;
  reserved: Uint8Array;
  static readonly SIZE: 32;
  static readonly PACKET_ID: 0x28;
  constructor(fields?: Partial<TouchController>);
}

export declare class BuzzerConfig extends _PackedStruct {
  instance_number: number;
  drive_pin: number;
  enable_pin: number;
  flags: number;
  duty_percent: number;
  reserved: Uint8Array;
  static readonly SIZE: 32;
  static readonly PACKET_ID: 0x29;
  constructor(fields?: Partial<BuzzerConfig>);
}

export declare class NfcConfig extends _PackedStruct {
  instance_number: number;
  nfc_ic_type: number;
  bus_instance: number;
  flags: number;
  field_detect_pin: number;
  field_detect_mode: number;
  field_detect_active: number;
  field_detect_debounce_ms: number;
  power_pin: number;
  power_active: number;
  power_on_delay_ms: number;
  power_off_delay_ms: number;
  adv_button_byte_index: number;
  adv_button_button_id: number;
  reserved_pin_1: number;
  reserved_pin_2: number;
  reserved: Uint8Array;
  static readonly SIZE: 32;
  static readonly PACKET_ID: 0x2A;
  constructor(fields?: Partial<NfcConfig>);
}

export declare class FlashConfig extends _PackedStruct {
  instance_number: number;
  flash_ic_type: number;
  bus_instance: number;
  flags: number;
  mosi_pin: number;
  sck_pin: number;
  cs_pin: number;
  power_pin: number;
  power_active: number;
  power_on_delay_ms: number;
  power_off_delay_ms: number;
  mode: number;
  reserved: Uint8Array;
  static readonly SIZE: 32;
  static readonly PACKET_ID: 0x2B;
  constructor(fields?: Partial<FlashConfig>);
}

export declare class DataExtended extends _PackedStruct {
  manufacturer_name: Uint8Array;
  model_name: Uint8Array;
  serial_number: Uint8Array;
  friendly_name: Uint8Array;
  device_location: Uint8Array;
  device_id: Uint8Array;
  custom_string_1: Uint8Array;
  custom_string_2: Uint8Array;
  custom_string_3: Uint8Array;
  static readonly SIZE: 288;
  static readonly PACKET_ID: 0x2C;
  constructor(fields?: Partial<DataExtended>);
}

export declare class LedFlashPattern extends _PackedStruct {
  mode_brightness: number;
  color1: number;
  loop1_delay_count: number;
  inter_loop_delay1: number;
  color2: number;
  loop2_delay_count: number;
  inter_loop_delay2: number;
  color3: number;
  loop3_delay_count: number;
  inter_loop_delay3: number;
  group_repeats: number;
  reserved: number;
  static readonly SIZE: 12;
  static readonly MESSAGE: "CMD_LED_ACTIVATE";
  constructor(fields?: Partial<LedFlashPattern>);
}

export declare class PipeStartRequest extends _PackedStruct {
  version: number;
  flags: number;
  req_window: number;
  req_ack_every: number;
  client_max_frame: number;
  total_size: number;
  static readonly SIZE: 10;
  static readonly MESSAGE: "CMD_PIPE_WRITE_START";
  constructor(fields?: Partial<PipeStartRequest>);
}

export declare class PipePartialExt extends _PackedStruct {
  old_etag: number;
  x: number;
  y: number;
  w: number;
  h: number;
  static readonly SIZE: 12;
  static readonly MESSAGE: "CMD_PIPE_WRITE_START";
  constructor(fields?: Partial<PipePartialExt>);
}

export declare class PipeStartResponse extends _PackedStruct {
  version: number;
  max_window: number;
  max_ack_every: number;
  max_frame: number;
  resp_flags: number;
  static readonly SIZE: 6;
  static readonly MESSAGE: "CMD_PIPE_WRITE_START";
  constructor(fields?: Partial<PipeStartResponse>);
}

export declare class PipeSack extends _PackedStruct {
  highest_seen: number;
  ack_mask: number;
  static readonly SIZE: 5;
  static readonly MESSAGE: "CMD_PIPE_WRITE_DATA";
  constructor(fields?: Partial<PipeSack>);
}

export declare class PartialWriteStartHeader extends _PackedStruct {
  flags: number;
  old_etag: number;
  new_etag: number;
  x: number;
  y: number;
  width: number;
  height: number;
  static readonly SIZE: 17;
  static readonly MESSAGE: "CMD_PARTIAL_WRITE_START";
  constructor(fields?: Partial<PartialWriteStartHeader>);
}

export declare class AuthChallenge extends _PackedStruct {
  status: number;
  server_nonce: Uint8Array;
  device_id: number;
  static readonly SIZE: 21;
  static readonly MESSAGE: "CMD_AUTHENTICATE";
  constructor(fields?: Partial<AuthChallenge>);
}

export declare class AuthProof extends _PackedStruct {
  client_nonce: Uint8Array;
  mac: Uint8Array;
  static readonly SIZE: 32;
  static readonly MESSAGE: "CMD_AUTHENTICATE";
  constructor(fields?: Partial<AuthProof>);
}

export declare class MsdAdvertisement extends _PackedStruct {
  company_id: number;
  dynamic: Uint8Array;
  chip_temperature: number;
  battery_voltage_low: number;
  status: number;
  static readonly SIZE: 16;
  static readonly MESSAGE: "CMD_READ_MSD";
  constructor(fields?: Partial<MsdAdvertisement>);
}
