// @generated by tools/gen_js_protocol.py -- DO NOT EDIT BY HAND.
// Source: opendisplay_protocol.h (OD_PROTOCOL_VERSION 2.2)
// Source SHA-256: 34410af281541c2e578bd9e23714a683ce5ddfb6c803a0c0d735fdba6af5b0e9
// Regenerate: tools/gen_js_protocol.py --write   (CI drift gate: --check)
//
// OpenDisplay BLE wire-protocol constants. Every value here travels on the wire.
// Flat `export const` (not a TS enum) because the wire reuses byte values across
// distinct names. NACK error codes are opcode-SCOPED: decode data[0] only in the
// scope of the echoed opcode (see the header for the full contract).

// ===== Protocol version =====
export declare const OD_PROTOCOL_VERSION_MAJOR: 2;
export declare const OD_PROTOCOL_VERSION_MINOR: 2;
export declare const OD_PROTOCOL_VERSION_STR: "2.2";

// ===== Section 1: COMMAND OPCODES (16-bit, big-endian on the wire) =====
export declare const CMD_REBOOT: 0x000F;
export declare const CMD_CONFIG_READ: 0x0040;
export declare const CMD_CONFIG_WRITE: 0x0041;
export declare const CMD_CONFIG_CHUNK: 0x0042;
export declare const CMD_FIRMWARE_VERSION: 0x0043;
export declare const CMD_READ_MSD: 0x0044;
export declare const CMD_CONFIG_CLEAR: 0x0045;
export declare const CMD_AUTHENTICATE: 0x0050;
export declare const CMD_ENTER_DFU: 0x0051;
export declare const CMD_POWER_OFF: 0x0052;
export declare const CMD_DEEP_SLEEP: 0x0053;
export declare const CMD_DIRECT_WRITE_START: 0x0070;
export declare const CMD_DIRECT_WRITE_DATA: 0x0071;
export declare const CMD_DIRECT_WRITE_END: 0x0072;
export declare const CMD_LED_ACTIVATE: 0x0073;
export declare const CMD_LED_STOP: 0x0075;
export declare const CMD_PARTIAL_WRITE_START: 0x0076;
export declare const CMD_BUZZER: 0x0077;
export declare const CMD_PIPE_WRITE_START: 0x0080;
export declare const CMD_PIPE_WRITE_DATA: 0x0081;
export declare const CMD_PIPE_WRITE_END: 0x0082;
export declare const CMD_NFC_ENDPOINT: 0x0083;

// ===== Section 2: RESPONSE / STATUS BYTES (8-bit) =====
export declare const RESP_ACK: 0x00;
export declare const RESP_NACK: 0xFF;
export declare const RESP_AUTH_REQUIRED: 0xFE;
export declare const RESP_CONFIG_READ: 0x40;
export declare const RESP_CONFIG_WRITE: 0x41;
export declare const RESP_CONFIG_CHUNK: 0x42;
export declare const RESP_FIRMWARE_VERSION: 0x43;
export declare const RESP_MSD_READ: 0x44;
export declare const RESP_CONFIG_CLEAR: 0x45;
export declare const RESP_AUTHENTICATE: 0x50;
export declare const RESP_ENTER_DFU: 0x51;
export declare const RESP_POWER_OFF: 0x52;
export declare const RESP_DEEP_SLEEP: 0x53;
export declare const RESP_DIRECT_WRITE_START_ACK: 0x70;
export declare const RESP_DIRECT_WRITE_DATA_ACK: 0x71;
export declare const RESP_DIRECT_WRITE_END_ACK: 0x72;
export declare const RESP_DIRECT_WRITE_REFRESH_SUCCESS: 0x73;
export declare const RESP_DIRECT_WRITE_REFRESH_TIMEOUT: 0x74;
export declare const RESP_DIRECT_WRITE_ERROR: 0xFF;
export declare const RESP_LED_ACTIVATE_ACK: 0x73;
export declare const RESP_LED_STOP_ACK: 0x75;
export declare const RESP_BUZZER_ACK: 0x77;
export declare const RESP_NFC_ENDPOINT: 0x83;

// ===== Section 3: AUTHENTICATE STATUS (3rd byte of a 0x50 response) =====
export declare const AUTH_STATUS_CHALLENGE: 0x00;
export declare const AUTH_STATUS_SUCCESS: typeof AUTH_STATUS_CHALLENGE;
export declare const AUTH_STATUS_FAILED: 0x01;
export declare const AUTH_STATUS_ALREADY: 0x02;
export declare const AUTH_STATUS_NOT_CONFIG: 0x03;
export declare const AUTH_STATUS_RATE_LIMIT: 0x04;
export declare const AUTH_STATUS_ERROR: 0xFF;

// ===== Section 4: OPCODE-SCOPED NACK ERROR NAMESPACES =====
export declare const OD_ERR_PARTIAL_ETAG_MISMATCH: 0x01;
export declare const OD_ERR_PARTIAL_RECT_OOB: 0x03;
export declare const OD_ERR_PARTIAL_RECT_ALIGN: 0x04;
export declare const OD_ERR_PARTIAL_FLAGS: 0x05;
export declare const OD_ERR_PARTIAL_STREAM: 0x06;
export declare const OD_ERR_PARTIAL_UNSUPPORTED: 0x07;
export declare const OD_ERR_PIPE_START_BAD_HEADER: 0x01;
export declare const OD_ERR_PIPE_START_UNKNOWN_FLAG: 0x02;
export declare const OD_ERR_PIPE_START_SIZE_MISMATCH: 0x03;
export declare const OD_ERR_PIPE_START_ETAG_MISMATCH: 0x05;
export declare const OD_ERR_PIPE_START_PARTIAL_UNSUPPORTED: 0x06;
export declare const OD_ERR_PIPE_START_RECT_INVALID: 0x07;
export declare const OD_ERR_DEEP_SLEEP_UNSUPPORTED: 0x00;
export declare const OD_ERR_DEEP_SLEEP_DISABLED: 0x01;
export declare const OD_ERR_DEEP_SLEEP_NOT_BATTERY: 0x02;
export declare const OD_ERR_POWER_OFF_UNSUPPORTED: 0x00;

// ===== Section 5: NFC SUB-PROTOCOL (rides CMD_NFC_ENDPOINT 0x0083) =====
export declare const NFC_SUB_READ: 0x00;
export declare const NFC_SUB_WRITE: 0x01;
export declare const NFC_SUB_WRITE_START: 0x10;
export declare const NFC_SUB_WRITE_DATA: 0x11;
export declare const NFC_SUB_WRITE_END: 0x12;
export declare const OD_NFC_REC_TEXT: 0;
export declare const OD_NFC_REC_URI: 1;
export declare const OD_NFC_REC_WELL_KNOWN_RAW: 2;
export declare const OD_NFC_REC_MIME: 3;
export declare const OD_NFC_REC_RAW_NDEF: 4;
export declare const OD_NFC_IC_AUTO: 0;
export declare const OD_NFC_IC_TNB132M: 1;
export declare const NFC_STATUS_READ_DATA: 0x80;
export declare const NFC_STATUS_WRITE_COMMITTED: 0x81;
export declare const NFC_STATUS_CHUNK_ACCEPTED: 0x82;
export declare const NFC_ERR_MALFORMED: 0x01;
export declare const NFC_ERR_READ_FAILED: 0x02;
export declare const NFC_ERR_TAG_WRITE_FAILED: 0x03;
export declare const NFC_ERR_UNKNOWN_SUBCMD: 0x04;
export declare const NFC_ERR_INVALID_REC_TYPE: 0x05;
export declare const NFC_ERR_BAD_TOTAL_LEN: 0x06;
export declare const NFC_ERR_CHUNK_NO_START: 0x07;
export declare const NFC_ERR_CHUNK_OVERFLOW: 0x08;
export declare const NFC_ERR_END_LEN_MISMATCH: 0x09;

// ===== Section 6: PIPE SLIDING-WINDOW WIRE CONSTANTS (0x0080..0x0082) =====
export declare const PIPE_VERSION: 0x01;
export declare const PIPE_FLAG_COMPRESSED: 0x01;
export declare const PIPE_FLAG_PARTIAL: 0x02;
export declare const PIPE_MAX_FRAME: 244;
export declare const PIPE_FRAME_OVERHEAD: 3;
export declare const PIPE_ACK_MASK_BITS: 32;
export declare const OD_PIPE_MAX_PAYLOAD: 244;

// ===== Section 7: CHUNK / SIZE BUDGETS =====
export declare const CONFIG_CHUNK_SIZE: 200;
export declare const CONFIG_CHUNK_SIZE_WITH_PREFIX: 202;
export declare const MAX_CONFIG_CHUNKS: 20;
export declare const MAX_RESPONSE_DATA_SIZE: 100;

// ===== Section 8: ENCRYPTION ENVELOPE (wire-visible sizes) =====
export declare const BLE_CMD_HEADER_SIZE: 2;
export declare const ENCRYPTION_NONCE_SIZE: 16;
export declare const ENCRYPTION_TAG_SIZE: 12;

// ===== Section 9: NETWORK TRANSPORT (LAN) =====
export declare const OD_LAN_TCP_PORT: 2446;
export declare const OD_LAN_TLS_PORT: 2447;
export declare const OD_LAN_MAX_PAYLOAD: 4096;
export declare const OD_LAN_MDNS_SERVICE: "_opendisplay._tcp";
export declare const OD_LAN_READ_TIMEOUT_S: 30;

