# @generated by tools/gen_python_structs.py -- DO NOT EDIT BY HAND.
# Source: opendisplay_structs.h (OD_STRUCTS_VERSION 2.0)
# Source SHA-256: be1be042914047e9ac0e17f4a9143efffa370f5b83aff6f64cb9a15223d9095b
# Regenerate: tools/gen_python_structs.py --write   (CI drift gate: --check)
"""OpenDisplay BLE payload structs, enums, and bitfields.

Generated from the canonical opendisplay_structs.h (OD_STRUCTS_VERSION 2.0).
Every layout here describes bytes that travel on the OpenDisplay BLE wire. Do not
hand-edit; edit the header and regenerate. Byte order is LITTLE-ENDIAN by default;
the big-endian exceptions (WifiConfig.server_port and all of
PartialWriteStartHeader) are honored per-field by each struct's pack()/unpack().
Cross-header names (OD_NFC_IC_*, PIPE_FLAG_*) live in opendisplay_protocol.py and
are referenced, never redefined here."""

from dataclasses import dataclass
from enum import IntEnum, IntFlag
from typing import ClassVar, Final, NamedTuple, Tuple

# ===== Loose wire constants =====

OD_STRUCTS_VERSION_MAJOR: Final = 2
OD_STRUCTS_VERSION_MINOR: Final = 0
OD_STRUCTS_VERSION_STR: Final = "2.0"
# outer-packet major version byte
OD_CONFIG_VERSION: Final = 1
# config-format minor; backward-compatible additions
OD_CONFIG_MINOR_VERSION: Final = 4
# CRC16-CCITT polynomial
OD_CONFIG_CRC_POLY: Final = 0x1021
# CRC16-CCITT initial value
OD_CONFIG_CRC_INIT: Final = 0xFFFF
# pin field value meaning 'no pin'
OD_PIN_UNUSED: Final = 0xFF

# ===== Packed-struct runtime (generic wire (de)serialization) =====

class _Spec(NamedTuple):
    """One field's wire geometry, driving generic pack/unpack."""

    name: str
    width: int      # total bytes on the wire
    array: bool     # True => raw `bytes`; False => int scalar
    endian: str     # "little" | "big" (only meaningful for int scalars)


class _PackedStruct:
    """Mixin: pack()/unpack() driven by the subclass's SIZE + _FIELDS table."""

    SIZE: ClassVar[int]
    _FIELDS: ClassVar[Tuple[_Spec, ...]]

    def pack(self) -> bytes:
        """Serialize to exactly SIZE wire bytes (arrays zero-padded/truncated)."""
        out = bytearray()
        for spec in self._FIELDS:
            value = getattr(self, spec.name)
            if spec.array:
                raw = bytes(value)
                if len(raw) > spec.width:
                    raise ValueError(
                        f"{type(self).__name__}.{spec.name}: {len(raw)} bytes > {spec.width}")
                out += raw.ljust(spec.width, b"\x00")
            else:
                out += int(value).to_bytes(spec.width, spec.endian)
        if len(out) != self.SIZE:
            raise ValueError(f"{type(self).__name__}: packed {len(out)} bytes, expected {self.SIZE}")
        return bytes(out)

    @classmethod
    def unpack(cls, data: bytes) -> "_PackedStruct":
        """Deserialize SIZE wire bytes into an instance (extra trailing bytes ignored)."""
        if len(data) < cls.SIZE:
            raise ValueError(f"{cls.__name__}: need {cls.SIZE} bytes, got {len(data)}")
        kwargs = {}
        offset = 0
        for spec in cls._FIELDS:
            chunk = data[offset:offset + spec.width]
            offset += spec.width
            kwargs[spec.name] = bytes(chunk) if spec.array else int.from_bytes(chunk, spec.endian)
        return cls(**kwargs)


# ===== Value enums =====

class ConfigPacketType(IntEnum):
    """Config TLV packet-type identifiers (SinglePacketHeader.id).  (on-wire width: 1 byte)"""

    OD_PKT_SYSTEM = 1  # system_config (required, singleton)
    OD_PKT_MANUFACTURER = 2  # manufacturer_data (required, singleton)
    OD_PKT_POWER = 4  # power_option (required, singleton)
    OD_PKT_DISPLAY = 32  # display (repeatable, max 4)
    OD_PKT_LED = 33  # led (repeatable, max 4)
    OD_PKT_SENSOR = 35  # sensor_data (repeatable, max 4)
    OD_PKT_DATA_BUS = 36  # data_bus (repeatable, max 4)
    OD_PKT_BINARY_INPUT = 37  # binary_inputs (repeatable, max 4)
    OD_PKT_WIFI = 38  # wifi_config (singleton)
    OD_PKT_SECURITY = 39  # security_config (singleton)
    OD_PKT_TOUCH = 40  # touch_controller (repeatable, max 4)
    OD_PKT_BUZZER = 41  # buzzer (repeatable, max 4). Canonical name is BUZZER (matches Silabs), resolving the Silabs BUZZER vs NRF54/yaml PASSIVE_BUZZER split; config.yaml's packet name (passive_buzzer) is regenerated to buzzer.
    OD_PKT_NFC = 42  # nfc_config (repeatable, max 2)
    OD_PKT_FLASH = 43  # flash_config (repeatable, max 2)
    OD_PKT_DATA_EXTENDED = 44  # data_extended (singleton)


class ActiveLevel(IntEnum):
    """GPIO active-level polarity. Bound from NfcConfig.field_detect_active,
    NfcConfig.power_active, FlashConfig.power_active.  (on-wire width: 1 byte)
    """

    OD_ACTIVE_LOW = 0  # signal asserted / present when the pin is LOW
    OD_ACTIVE_HIGH = 1  # signal asserted / present when the pin is HIGH


class ICType(IntEnum):
    """Host MCU/IC of the device (SystemConfig.ic_type).  (on-wire width: 2 bytes)"""

    OD_IC_TYPE_NRF52840 = 1  # nRF52840-based boards
    OD_IC_TYPE_ESP32S3 = 2  # ESP32-S3-based boards
    OD_IC_TYPE_ESP32C3 = 3  # ESP32-C3-based boards
    OD_IC_TYPE_ESP32C6 = 4  # ESP32-C6-based boards
    OD_IC_TYPE_NRF52811 = 5  # nRF52811-based boards
    OD_IC_TYPE_EFR32BG22C222F352GM40 = 6  # Silicon Labs EFR32BG22 boards
    OD_IC_TYPE_NRF54L15 = 7  # Seeed XIAO nRF54L15 (Zephyr)
    OD_IC_TYPE_NRF54LM20 = 8  # Seeed XIAO nRF54LM20A (Zephyr)


class ManufacturerId(IntEnum):
    """Device manufacturer (ManufacturerData.manufacturer_id). Board-name tables (board_type)
    are intentionally NOT enumerated here -- they live only in config.yaml; board_type stays
    a raw u8 field.  (on-wire width: 2 bytes)
    """

    OD_MANUFACTURER_DIY = 0  # self-built / DIY devices
    OD_MANUFACTURER_SEEED = 1  # Seeed Studio
    OD_MANUFACTURER_WAVESHARE = 2  # Waveshare Electronics
    OD_MANUFACTURER_SOL = 3  # SOL
    OD_MANUFACTURER_OPENDISPLAY = 4  # OpenDisplay (free giveaways only)


class PowerMode(IntEnum):
    """Power source (PowerOption.power_mode).  (on-wire width: 1 byte)"""

    OD_POWER_MODE_BATTERY = 1  # battery powered
    OD_POWER_MODE_USB = 2  # USB powered
    OD_POWER_MODE_SOLAR = 3  # solar powered


class CapacityEstimator(IntEnum):
    """Battery chemistry model for state-of-charge estimation (PowerOption.capacity_estimator).
    (on-wire width: 1 byte)
    """

    OD_CAPACITY_EST_LI_ION = 1  # 1S Li-ion
    OD_CAPACITY_EST_LIFEPO4 = 2  # 1S LiFePO4
    OD_CAPACITY_EST_SUPERCAP = 3  # 2S supercapacitor (4.5 V max, 3.6 V cutoff)
    OD_CAPACITY_EST_LITHIUM_PRIMARY = 4  # lithium primary (non-rechargeable)
    OD_CAPACITY_EST_SEEED_LI_ION = 5  # 1S Li-ion, Seeed reTerminal E-series discharge curve


class DisplayTechnology(IntEnum):
    """Display technology (DisplayConfig.display_technology).  (on-wire width: 1 byte)"""

    OD_DISPLAY_TECH_UNDEFINED = 0  # undefined / unspecified
    OD_DISPLAY_TECH_E_PAPER = 1  # e-paper / ESL
    OD_DISPLAY_TECH_LCD = 2  # LCD
    OD_DISPLAY_TECH_LED_MATRIX = 3  # LED-matrix display


class Rotation(IntEnum):
    """Physical panel rotation (DisplayConfig.rotation).  (on-wire width: 1 byte)"""

    OD_ROTATION_0 = 0  # 0 degrees
    OD_ROTATION_90 = 1  # 90 degrees
    OD_ROTATION_180 = 2  # 180 degrees
    OD_ROTATION_270 = 3  # 270 degrees


class PartialUpdateSupport(IntEnum):
    """Panel partial-update capability (DisplayConfig.partial_update_support).  (on-wire width:
    1 byte)
    """

    OD_PARTIAL_UPDATE_NONE = 0  # only full updates supported
    OD_PARTIAL_UPDATE_SUPPORTED = 1  # partial updates supported
    OD_PARTIAL_UPDATE_FULL_FRAME = 2  # partial supported but a full-frame stream is required


class ColorScheme(IntEnum):
    """display color/plane scheme (DisplayConfig.color_scheme); drives plane count and pixel
    packing.  (on-wire width: 1 byte)
    """
    # @external mirror: epaper-dithering packages/rust/core/src/palettes.rs (integer values MUST match; the crate declares itself a firmware mirror). informed-by: bb_epaper. The value->plane/packing meaning is OpenDisplay-owned here.

    OD_COLOR_SCHEME_MONO = 0  # 1bpp black/white
    OD_COLOR_SCHEME_BWR = 1  # black/white/red
    OD_COLOR_SCHEME_BWY = 2  # black/white/yellow
    OD_COLOR_SCHEME_BWRY = 3  # black/white/red/yellow
    OD_COLOR_SCHEME_BWGBRY = 4  # Spectra 6-color (black/white/green/blue/red/yellow)
    OD_COLOR_SCHEME_GRAY4 = 5  # 2bpp 4-level gray
    OD_COLOR_SCHEME_GRAY16 = 6  # 4bpp 16-level gray
    OD_COLOR_SCHEME_SEVEN_COLOR = 7  # 7-color (Spectra/ACeP 7, config.yaml '7color')
    # changed: 2.0: value 7 is SEVEN_COLOR; the former COLOR_SCHEME_GRAY8=7 was a mistake
    # (gray8 is not a real scheme) and is removed -- not renumbered.
    OD_COLOR_SCHEME_BWGBRY_SPLIT = 8  # Spectra 6 nibbles, left-half plane then right-half plane (dual-CS panels, no device framebuffer)
    OD_COLOR_SCHEME_RGB565 = 100  # RGB565 (non-epaper)
    OD_COLOR_SCHEME_RGB888 = 101  # RGB888 (non-epaper)
    OD_COLOR_SCHEME_RGB16BPC = 102  # 16 bits per channel (non-epaper)


class PanelIC(IntEnum):
    """display controller / panel type (DisplayConfig.panel_ic_type). Only representative
    values are named here; the full list lives in config.yaml.  (on-wire width: 2 bytes)
    """
    # @external bb_epaper (0-76 names track bb_epaper EP* panel identifiers); the 1000-1030 range comes from the M3 / EPD-nRF5 driver line; 3000+ from the Seeed_GFX / OpenDisplay runtime. Wire values are OpenDisplay-OWNED; each firmware maps value -> its bb_epaper EP* constant via a repo-local opendisplay_epd_map.c (NOT part of this header; bb_epaper never dictates the wire values).

    OD_PANEL_IC_EP_PANEL_UNDEFINED = 0  # undefined / unknown panel
    OD_PANEL_IC_EP42_400X300 = 1  # WFT0420CZ15 4.2" B/W
    OD_PANEL_IC_EP42B_400X300 = 2  # DEPG0420BN / GDEY042T81 4.2" B/W
    OD_PANEL_IC_EP213_122X250 = 3  # Waveshare 2.13"
    OD_PANEL_IC_EP213B_122X250 = 4  # GDEY0213B74 (Inky pHAT 2.13" B/W newer)
    OD_PANEL_IC_EP293_128X296 = 5  # 128x296 panel
    OD_PANEL_IC_EP294_128X296 = 6  # Waveshare newer 2.9" 1-bit 128x296
    OD_PANEL_IC_EP295_128X296 = 7  # harvested Solum 2.9" BW ESLs
    OD_PANEL_IC_EP295_128X296_4GRAY = 8  # 4-gray variant of EP295
    OD_PANEL_IC_EP266_152X296 = 9  # GDEY0266T90
    OD_PANEL_IC_EP102_80X128 = 10  # GDEW0102T4
    OD_PANEL_IC_EP27B_176X264 = 11  # GDEY027T91
    OD_PANEL_IC_EP29R_128X296 = 12  # tricolor 2.9 panel
    OD_PANEL_IC_EP122_192X176 = 13  # GDEM0122T61
    OD_PANEL_IC_EP154R_152X152 = 14  # 1.54" B/W/R
    OD_PANEL_IC_EP42R_400X300 = 15  # 400x300 tricolor
    OD_PANEL_IC_EP42R2_400X300 = 16  # GDEQ042Z21
    OD_PANEL_IC_EP37_240X416 = 17  # GDEY037T03
    OD_PANEL_IC_EP37B_240X416 = 18  # CROWPANEL 3.7"
    OD_PANEL_IC_EP213_104X212 = 19  # InkyPHAT 2.13 B/W
    OD_PANEL_IC_EP75_800X480 = 20  # GDEY075T7 (older version)
    OD_PANEL_IC_EP75_800X480_4GRAY = 21  # GDEW075T7 (older) 4-gray mode
    OD_PANEL_IC_EP75_800X480_4GRAY_V2 = 22  # GDEY075T7 older panel, darker grays
    OD_PANEL_IC_EP29_128X296 = 23  # Pimoroni Badger2040
    OD_PANEL_IC_EP29_128X296_4GRAY = 24  # Pimoroni Badger2040 4-gray
    OD_PANEL_IC_EP213R_122X250 = 25  # Inky pHAT 2.13 B/W/R
    OD_PANEL_IC_EP154_200X200 = 26  # Waveshare 2.0" B/W
    OD_PANEL_IC_EP154B_200X200 = 27  # DEPG01540BN
    OD_PANEL_IC_EP266YR_184X360 = 28  # GDEY0266F51
    OD_PANEL_IC_EP29YR_128X296 = 29  # GDEY029F51
    OD_PANEL_IC_EP29YR_168X384 = 30  # GDEY029F51H
    OD_PANEL_IC_EP583_648X480 = 31  # DEPG0583BN
    OD_PANEL_IC_EP296_128X296 = 32  # Waveshare 2.9" 128x296 B/W V2
    OD_PANEL_IC_EP26R_152X296 = 33  # Solum 2.6" B/W/R
    OD_PANEL_IC_EP73_800X480 = 34  # GEDY073D46 (slower, EOL 7-color)
    OD_PANEL_IC_EP73_SPECTRA_800X480 = 35  # Spectra 6/7-color 800x480
    OD_PANEL_IC_EP74R_640X384 = 36  # 640x384 panel
    OD_PANEL_IC_EP583R_600X448 = 37  # 4-bits-per-pixel 5.83" panel
    OD_PANEL_IC_EP75R_800X480 = 38  # Waveshare 800x480 3-color
    OD_PANEL_IC_EP426_800X480 = 39  # Waveshare 4.26" B/W 800x480
    OD_PANEL_IC_EP426_800X480_4GRAY = 40  # 4.26" 2-bit grayscale mode
    OD_PANEL_IC_EP29R2_128X296 = 41  # Adafruit 2.9" Tricolor FeatherWing
    OD_PANEL_IC_EP41_640X400 = 42  # EInk ED040TC1 SPI UC81xx
    OD_PANEL_IC_EP81_SPECTRA_1024X576 = 43  # Spectra 8.1" 1024x576 6-color
    OD_PANEL_IC_EP7_960X640 = 44  # ED070EC1
    OD_PANEL_IC_EP213R2_122X250 = 45  # UC8151 3-color 2.13"
    OD_PANEL_IC_EP29Z_128X296 = 46  # SSD1680 (CrowPanel 2.9")
    OD_PANEL_IC_EP29Z_128X296_4GRAY = 47  # SSD1680 4-gray
    OD_PANEL_IC_EP213Z_122X250 = 48  # SSD1680 CrowPanel 2.13"
    OD_PANEL_IC_EP213Z_122X250_4GRAY = 49  # CrowPanel 2.13" 4-gray mode
    OD_PANEL_IC_EP154Z_152X152 = 50  # CrowPanel 1.54"
    OD_PANEL_IC_EP579_792X272 = 51  # CrowPanel 5.79"
    OD_PANEL_IC_EP213YR_122X250 = 52  # GDEY0213F52
    OD_PANEL_IC_EP37YR_240X416 = 53  # GDEM037F51
    OD_PANEL_IC_EP35YR_184X384 = 54  # GDEM035F51
    OD_PANEL_IC_EP397YR_800X480 = 55  # GDEM0397F81
    OD_PANEL_IC_EP154YR_200X200 = 56  # GDEM0154F51H
    OD_PANEL_IC_EP266YR2_184X360 = 57  # GDEY0266F52H
    OD_PANEL_IC_EP42YR_400X300 = 58  # GDEM042F52
    OD_PANEL_IC_EP75_800X480_GEN2 = 59  # GEDY075-D2 (Waveshare/Xiao V2 panels)
    OD_PANEL_IC_EP75_800X480_4GRAY_GEN2 = 60  # GDEY075T7-D2 (newer) 4-gray mode
    OD_PANEL_IC_EP215YR_160X296 = 61  # Waveshare 2.15" 4-color
    OD_PANEL_IC_EP1085_1360X480 = 62  # GDEM1085T51
    OD_PANEL_IC_EP31_240X320 = 63  # GDEQ031T10 LilyGo T-Deck Pro
    OD_PANEL_IC_EP75YR_800X480 = 64  # EP75YR 800x480 7-color
    OD_PANEL_IC_EP133A_SPECTRA_1200X1600 = 66  # T133A01 Spectra 6 13.3" dual-controller (Seeed reTerminal E1004). config.yaml catches up (it skips 65-66 today); value 65 stays reserved.
    OD_PANEL_IC_EP154_200X200_4GRAY = 67  # Waveshare 1.54" 4-gray
    OD_PANEL_IC_EP42B_400X300_4GRAY = 68  # DEPG0420BN / GDEY042T81 4-gray
    OD_PANEL_IC_EP397_800X480 = 69  # GDEM0397T81P
    OD_PANEL_IC_EP397_800X480_4GRAY = 70  # GDEM0397T81P 4-gray
    OD_PANEL_IC_EP368_792X528 = 71  # xteink X3 3.68" B/W
    OD_PANEL_IC_EP368_792X528_4GRAY = 72  # xteink X3 3.68" 4-gray
    OD_PANEL_IC_EP213ZZ_122X250 = 73  # LilyGo T3S3 2.13"
    OD_PANEL_IC_EP40_SPECTRA_400X600 = 74  # GDEP040E01 Spectra 6 4" 400x600
    OD_PANEL_IC_EP27_176X264 = 75  # Badger2350 B/W 2.7"
    OD_PANEL_IC_EP27_176X264_4GRAY = 76  # Badger2350 4-gray 2.7"
    OD_PANEL_IC_UC8176_420_BW = 1000  # UC8176 4.2" B/W (M3 / EPD-nRF5 driver line, values 1000-1030)
    OD_PANEL_IC_SSD1619_420_BWR = 1001  # SSD1619 4.2" B/W/R
    OD_PANEL_IC_UC8176_420_BWR = 1002  # UC8176 4.2" B/W/R
    OD_PANEL_IC_SSD1619_420_BW = 1003  # SSD1619 4.2" B/W
    OD_PANEL_IC_JD79668_420_BWRY = 1004  # JD79668 4.2" B/W/R/Y
    OD_PANEL_IC_UC8179_750_BW = 1005  # UC8179 7.5" B/W
    OD_PANEL_IC_UC8179_750_BWR = 1006  # UC8179 7.5" B/W/R
    OD_PANEL_IC_UC8159_750_LOW_BW = 1007  # UC8159 7.5" Low Power B/W
    OD_PANEL_IC_UC8159_750_LOW_BWR = 1008  # UC8159 7.5" Low Power B/W/R
    OD_PANEL_IC_SSD1677_750_HD_BW = 1009  # SSD1677 7.5" HD B/W
    OD_PANEL_IC_SSD1677_750_HD_BWR = 1010  # SSD1677 7.5" HD B/W/R
    OD_PANEL_IC_JD79665_750_BWRY = 1011  # JD79665 7.5" B/W/R/Y
    OD_PANEL_IC_JD79665_583_BWRY = 1012  # JD79665 5.83" B/W/R/Y
    OD_PANEL_IC_UC8151_029_BW = 1013  # UC8151 2.9" 168x384 B/W
    OD_PANEL_IC_UC8151_029_BWR = 1014  # UC8151 2.9" 168x384 B/W/R
    OD_PANEL_IC_SSD1619_029_BW = 1015  # SSD1619 2.9" 168x384 B/W
    OD_PANEL_IC_SSD1619_029_BWR = 1016  # SSD1619 2.9" 168x384 B/W/R
    OD_PANEL_IC_SSD1619_016_BW = 1017  # SSD1619 1.6" 200x200 B/W
    OD_PANEL_IC_SSD1619_016_BWR = 1018  # SSD1619 1.6" 200x200 B/W/R
    OD_PANEL_IC_SSD1619_022_BW = 1019  # SSD1619 2.2" 240x320 B/W
    OD_PANEL_IC_SSD1619_022_BWR = 1020  # SSD1619 2.2" 240x320 B/W/R
    OD_PANEL_IC_SSD1619_026_BW = 1021  # SSD1619 2.6" 296x152 B/W
    OD_PANEL_IC_SSD1619_026_BWR = 1022  # SSD1619 2.6" 296x152 B/W/R
    OD_PANEL_IC_UC8151_027_BW = 1023  # UC8151 2.7" 200x300 B/W
    OD_PANEL_IC_UC8151_027_BWR = 1024  # UC8151 2.7" 200x300 B/W/R
    OD_PANEL_IC_UC43_430_BW = 1025  # UC variant 4.3" 152x522 B/W
    OD_PANEL_IC_UC43_430_BWR = 1026  # UC variant 4.3" 152x522 B/W/R
    OD_PANEL_IC_SSD1619_013_BW = 1027  # SSD1619 1.3" 144x200 B/W
    OD_PANEL_IC_SSD1619_013_BWR = 1028  # SSD1619 1.3" 144x200 B/W/R
    OD_PANEL_IC_SSD1619_022_LITE_BW = 1029  # SSD1619 M3 Lite 2.2" 250x128 B/W
    OD_PANEL_IC_SSD1619_022_LITE_BWR = 1030  # SSD1619 M3 Lite 2.2" 250x128 B/W/R
    OD_PANEL_IC_ED103TC2_1872X1404 = 3000  # E Ink ED103TC2 + IT8951 (Seeed 10.3", 1872x1404, 1bpp; Seeed_GFX/OpenDisplay runtime, values 3000+)
    OD_PANEL_IC_ED103TC2_1872X1404_4GRAY = 3001  # same panel as 3000; 4bpp (16-level)


class LedType(IntEnum):
    """LED wiring type (LedConfig.led_type).  (on-wire width: 1 byte)"""

    OD_LED_TYPE_RGB = 0  # RGB LED (3 channels)
    OD_LED_TYPE_SINGLE = 1  # single LED
    OD_LED_TYPE_RY = 2  # red/yellow pair
    OD_LED_TYPE_FOUR_SEPARATE = 3  # four separate LEDs


class SensorType(IntEnum):
    """Sensor / PMIC type (SensorData.sensor_type).  (on-wire width: 2 bytes)"""

    OD_SENSOR_TYPE_TEMPERATURE = 1  # generic temperature sensor
    OD_SENSOR_TYPE_HUMIDITY = 2  # generic humidity sensor
    OD_SENSOR_TYPE_AXP2101 = 3  # AXP2101 power-management IC
    OD_SENSOR_TYPE_SHT40 = 4  # Sensirion SHT40 (I2C); writes 3 LE bytes into MSD dynamic data (21 bits: 0.1C, 0.1% RH)
    OD_SENSOR_TYPE_BQ27220 = 5  # TI BQ27220 fuel gauge (I2C 0x55); voltage in MSD bytes 14-15, one packed dynamic byte (bits 0-6 SOC%, bit7 charging)


class BusType(IntEnum):
    """Bus protocol (DataBus.bus_type). Canonical replacement for the per-repo OD_BUS_TYPE_I2C
    macro.  (on-wire width: 1 byte)
    """

    OD_BUS_TYPE_I2C = 1  # I2C bus
    OD_BUS_TYPE_SPI = 2  # SPI bus


class InputType(IntEnum):
    """Binary input hardware type (BinaryInputs.input_type).  (on-wire width: 1 byte)"""

    OD_INPUT_TYPE_BUTTON = 1  # momentary button
    OD_INPUT_TYPE_SWITCH = 2  # toggle switch


class InputDisplayAs(IntEnum):
    """How a UI should render the input (BinaryInputs.display_as).  (on-wire width: 1 byte)"""

    OD_INPUT_DISPLAY_AS_BUTTON = 1  # present as a button
    OD_INPUT_DISPLAY_AS_SWITCH = 2  # present as a switch


class WifiEncryptionType(IntEnum):
    """WiFi security (WifiConfig.encryption_type).  (on-wire width: 1 byte)"""

    OD_WIFI_ENC_NONE = 0  # open network (no encryption)
    OD_WIFI_ENC_WEP = 1  # WEP
    OD_WIFI_ENC_WPA = 2  # WPA
    OD_WIFI_ENC_WPA2 = 3  # WPA2
    OD_WIFI_ENC_WPA3 = 4  # WPA3


class TouchIcType(IntEnum):
    """Touch controller IC (TouchController.touch_ic_type). Canonical replacement for the per-
    repo TOUCH_IC_* macros.  (on-wire width: 2 bytes)
    """

    OD_TOUCH_IC_NONE = 0  # disabled / no touch
    OD_TOUCH_IC_GT911 = 1  # Goodix GT911 (I2C)


class NfcFieldDetectMode(IntEnum):
    """How NFC field presence is sensed (NfcConfig.field_detect_mode).  (on-wire width: 1 byte)"""

    OD_NFC_FIELD_DETECT_DISABLED = 0  # field-detect logic disabled
    OD_NFC_FIELD_DETECT_GPIO_LEVEL = 1  # GPIO level sampled / polled
    OD_NFC_FIELD_DETECT_IRQ_LATCHED = 2  # interrupt-latched (reserved for future use)


class FlashIcType(IntEnum):
    """External-flash IC type (FlashConfig.flash_ic_type).  (on-wire width: 1 byte)"""

    OD_FLASH_IC_AUTO = 0  # generic SPI-flash deep-sleep command flow


# ===== Bitfield groups =====

class CommunicationModes(IntFlag):
    """SystemConfig.communication_modes @bits CommunicationModes (bits 3-7 reserved)."""

    OD_COMM_MODE_BLE = 1 << 0  # BLE transfer supported
    OD_COMM_MODE_OEPL = 1 << 1  # OEPL (OpenEPaperLink) transfer supported
    OD_COMM_MODE_WIFI = 1 << 2  # WiFi transfer supported


class DeviceFlags(IntFlag):
    """SystemConfig.device_flags @bits DeviceFlags (bits 5-7 reserved)."""

    OD_DEVICE_FLAG_PWR_PIN = 1 << 0  # device has external power management for the display etc.
    OD_DEVICE_FLAG_XIAO_INIT = 1 << 1  # apply Seeed XIAO low-power init
    OD_DEVICE_FLAG_WS_PP_INIT = 1 << 2  # apply Waveshare PhotoPainter low-power init
    OD_DEVICE_FLAG_PWR_LATCH = 1 << 3  # self-holding MOSFET latch on pwr_pin_2; optional long-press shutdown button on pwr_pin_3
    OD_DEVICE_FLAG_PWR_LATCH_DFF = 1 << 4  # 74AHC1G79 D-FF latch: pwr_pin_2=D (hold), pwr_pin_3=CP (clock); command 0x0052 releases latch


class SleepFlags(IntFlag):
    """PowerOption.sleep_flags @bits SleepFlags (bits 1-7 reserved). Firmware ships bit0;
    config.yaml still lists it reserved_0 (yaml is behind).
    """

    OD_SLEEP_FLAG_BUTTON_WAKE_DISABLE = 1 << 0  # opt out of button wake from timer deep sleep (buttons sharing wake-hostile pads)


class BatterySenseFlags(IntFlag):
    """PowerOption.battery_sense_flags @bits BatterySenseFlags (bits 1-7 reserved). Firmware
    ships bit0; config.yaml still lists it reserved_0 (yaml is behind).
    """

    OD_BATTERY_SENSE_FLAG_ENABLE_INVERTED = 1 << 0  # battery-sense enable is active-low (e.g. XIAO ~READ_BAT on P0.14)


class ChargerFlags(IntFlag):
    """PowerOption.charger_flags @bits ChargerFlags (bits 2-7 reserved)."""

    OD_CHARGER_FLAG_ENABLE_ACTIVE_LOW = 1 << 0  # charge-enable (/CE) is active-low
    OD_CHARGER_FLAG_STATE_ACTIVE_LOW = 1 << 1  # charge-state (BQ25616 STAT) is active-low: charging when LOW


class TransmissionModes(IntFlag):
    """DisplayConfig.transmission_modes @bits TransmissionModes (bits 5-6 reserved -- named as
    placeholders below; bit7 is defined above the gap).
    """

    OD_TRANSMISSION_MODE_STREAMING_DECOMPRESSION = 1 << 0  # streaming zlib inflate, 512-byte DEFLATE window (requires zip). Canonical name resolves the Firmware/Silabs ZIPXL vs NRF54/yaml streaming_decompression split.
    OD_TRANSMISSION_MODE_ZIP = 1 << 1  # zip-compressed transfer (full window)
    OD_TRANSMISSION_MODE_G5 = 1 << 2  # Group 5 compression (not yet implemented)
    OD_TRANSMISSION_MODE_DIRECT_WRITE = 1 << 3  # direct-write mode (bufferless)
    OD_TRANSMISSION_MODE_PIPE_WRITE = 1 << 4  # PIPE-write mode: faster transfer via sliding-window pipeline
    OD_TRANSMISSION_MODE_RESERVED_5 = 1 << 5  # reserved; must be 0 (placeholder name for a future transmission mode)
    OD_TRANSMISSION_MODE_RESERVED_6 = 1 << 6  # reserved; must be 0 (placeholder name for a future transmission mode)
    OD_TRANSMISSION_MODE_CLEAR_ON_BOOT = 1 << 7  # Clear screen on boot. Synonymous with config.yaml's no_boot_text / NO_BOOT_TEXT -- same bit, same behavior (clearing on boot is why no boot text shows).


class LedFlags(IntFlag):
    """LedConfig.led_flags @bits LedFlags (bits 4-7 reserved)."""

    OD_LED_FLAG_LED1_INVERT = 1 << 0  # invert LED channel 1 polarity
    OD_LED_FLAG_LED2_INVERT = 1 << 1  # invert LED channel 2 polarity
    OD_LED_FLAG_LED3_INVERT = 1 << 2  # invert LED channel 3 polarity
    OD_LED_FLAG_LED4_INVERT = 1 << 3  # invert LED channel 4 polarity


# Bitfield group BusFlags: DataBus.bus_flags @bits BusFlags -- all bits reserved today (must
# be 0). DataBus.pullups / .pulldowns @bits PinBitmap: bit N-1 = pin N (pin_1..pin_7); bit 7
# reserved. See the PinBitmap convention note above BinaryInputs.

# Bitfield group PinBitmap: DataBus.bus_flags @bits BusFlags -- all bits reserved today
# (must be 0). DataBus.pullups / .pulldowns @bits PinBitmap: bit N-1 = pin N (pin_1..pin_7);
# bit 7 reserved. See the PinBitmap convention note above BinaryInputs.

class SecurityFlags(IntFlag):
    """SecurityConfig.flags @bits SecurityFlags (bits 6-7 reserved)."""

    OD_SECURITY_FLAG_REWRITE_ALLOWED = 1 << 0  # allow unauthenticated config writes while encryption is enabled
    OD_SECURITY_FLAG_SHOW_KEY_ON_SCREEN = 1 << 1  # show the encryption key on screen (future feature)
    OD_SECURITY_FLAG_RESET_PIN_ENABLED = 1 << 2  # reset pin enabled (must be set for the reset pin to work)
    OD_SECURITY_FLAG_RESET_PIN_POLARITY = 1 << 3  # reset-pin polarity: 0 = LOW triggers, 1 = HIGH triggers
    OD_SECURITY_FLAG_RESET_PIN_PULLUP = 1 << 4  # enable pull-up on the reset pin
    OD_SECURITY_FLAG_RESET_PIN_PULLDOWN = 1 << 5  # enable pull-down on the reset pin


class TouchFlags(IntFlag):
    """TouchController.flags @bits TouchFlags (bits 3-7 reserved)."""

    OD_TOUCH_FLAG_INVERT_X = 1 << 0  # invert X using panel width
    OD_TOUCH_FLAG_INVERT_Y = 1 << 1  # invert Y using panel height
    OD_TOUCH_FLAG_SWAP_XY = 1 << 2  # swap X and Y before invert/clip


class BuzzerFlags(IntFlag):
    """BuzzerConfig.flags @bits BuzzerFlags (bits 1-7 reserved)."""

    OD_BUZZER_FLAG_ENABLE_ACTIVE_HIGH = 1 << 0  # enable pin is active-high when set; otherwise active-low


class NfcFlags(IntFlag):
    """NfcConfig.flags @bits NfcFlags (bits 1-7 reserved)."""

    OD_NFC_FLAG_ENABLED = 1 << 0  # must be set to enable NFC init (no fallback init if clear)


class FlashFlags(IntFlag):
    """FlashConfig.flags @bits FlashFlags (bits 1-7 reserved)."""

    OD_FLASH_FLAG_ENABLED = 1 << 0  # must be set to enable flash pin config / deep-sleep sequencing


class MsdStatusBits(IntFlag):
    """MsdAdvertisement.status @bits MsdStatusBits. bit0 is the 9th (MSB) bit of the 10-bit
    battery voltage; bits 4-7 are a free-running main-loop nibble counter.
    """

    OD_MSD_STATUS_BATTERY_VOLTAGE_BIT8 = 1 << 0  # high bit of the 10-bit battery voltage (units of 10 mV); combine with battery_voltage_low
    OD_MSD_STATUS_REBOOT_FLAG = 1 << 1  # device rebooted since last read
    OD_MSD_STATUS_CONNECTION_REQUESTED = 1 << 2  # device is requesting a connection
    OD_MSD_STATUS_RESERVED_3 = 1 << 3  # reserved; must be 0 (placeholder name for a future status flag; sits between the flags and the bits 4-7 counter)

OD_MSD_STATUS_MAIN_LOOP_COUNTER_SHIFT: Final = 4  # bits 4-7: free-running main-loop nibble counter (liveness)
OD_MSD_STATUS_MAIN_LOOP_COUNTER_MASK: Final = 0xF0  # mask for the bits 4-7 main-loop counter nibble


# ===== Cross-header bindings (defined in opendisplay_protocol.py) =====
# @enum OD_NFC_IC_*: OD_NFC_IC_AUTO=0, OD_NFC_IC_TNB132M=1
# @bits PIPE_FLAG_*: PIPE_FLAG_COMPRESSED=1, PIPE_FLAG_PARTIAL=2

# ===== Packed structs =====

@dataclass
class OuterPacketHeader(_PackedStruct):
    """Wraps the whole transfer: a length+version header, then a sequence of single_packet
    entries, then a trailing CRC (NOT part of this struct -- it is the last 2 bytes of the
    outer packet).  [config packet outer]  (3 wire bytes.)
    """

    # total outer-packet length INCLUDING the trailing CRC. Inconsistently populated -- may
    # be a real total or a zero pad; the CRC is computed as if this were 0x0000 either way.
    length: int = 0
    # config-format MAJOR version = OD_CONFIG_VERSION (1). The minor is not carried in the
    # header.  [enum OD_CONFIG_VERSION]
    version: int = 0

    SIZE: ClassVar[int] = 3
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("length", 2, False, "little"),
        _Spec("version", 1, False, "little"),
    )


@dataclass
class SinglePacketHeader(_PackedStruct):
    """Header preceding each config payload inside the outer packet. The payload that follows
    is a fixed-size struct whose size and layout are determined entirely by `id` (see
    ConfigPacketType); there is no per-packet length field -- sizeof the selected struct IS
    the payload length.  [config packet single]  (2 wire bytes.)
    """

    # 0-based sequential packet index within the outer packet.
    number: int = 0
    # packet-type id selecting the payload struct.  [enum ConfigPacketType]
    id: int = 0

    SIZE: ClassVar[int] = 2
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("number", 1, False, "little"),
        _Spec("id", 1, False, "little"),
    )


@dataclass
class SystemConfig(_PackedStruct):
    """Host IC identity, communication capabilities, and power-management pins. Required
    singleton. 22 bytes.  [config packet 0x01; required]  (22 wire bytes.)
    """

    # host MCU/IC of this device.  [enum ICType]
    ic_type: int = 0
    # supported transfer modes (bitfield).  [bits CommunicationModes]
    communication_modes: int = 0
    # misc device / power-latch flags (bitfield).  [bits DeviceFlags]
    device_flags: int = 0
    # primary power-management pin; 0xFF = not present.  [default 0xFF]
    pwr_pin: int = 0
    # future use; must be 0.  [reserved]
    reserved: bytes = b""
    # aux enable / battery-latch hold / pwr_latch_dff D input; 0 or 0xFF = firmware default.
    pwr_pin_2: int = 0
    # aux enable / battery-latch shutdown button / pwr_latch_dff CP clock; 0 or 0xFF =
    # none/default.
    pwr_pin_3: int = 0

    SIZE: ClassVar[int] = 22
    PACKET_ID: ClassVar[int] = 0x01
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("ic_type", 2, False, "little"),
        _Spec("communication_modes", 1, False, "little"),
        _Spec("device_flags", 1, False, "little"),
        _Spec("pwr_pin", 1, False, "little"),
        _Spec("reserved", 15, True, "little"),
        _Spec("pwr_pin_2", 1, False, "little"),
        _Spec("pwr_pin_3", 1, False, "little"),
    )


@dataclass
class ManufacturerData(_PackedStruct):
    """Manufacturer id, board identity, and the 'simple config' preset indices the website UI
    applied. Required singleton. 22 bytes.  [config packet 0x02; required]  (22 wire bytes.)
    """

    # device manufacturer.  [enum ManufacturerId]
    manufacturer_id: int = 0
    # board identifier; meaning depends on manufacturer_id. Value table lives in config.yaml
    # only (NOT enumerated here) -- raw u8.
    board_type: int = 0
    # board revision number.
    board_revision: int = 0
    # simple-config driver preset index (1-based; 0 = not set).
    simple_config_driver_index: int = 0
    # simple-config display preset index (1-based; 0 = not set).
    simple_config_display_index: int = 0
    # simple-config power preset index (1-based; 0 = not set).
    simple_config_power_index: int = 0
    # 48-bit little-endian Unix time (seconds) when simple config was last applied.  [unit
    # s]
    simple_config_configured_at: bytes = b""
    # future use; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 22
    PACKET_ID: ClassVar[int] = 0x02
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("manufacturer_id", 2, False, "little"),
        _Spec("board_type", 1, False, "little"),
        _Spec("board_revision", 1, False, "little"),
        _Spec("simple_config_driver_index", 2, False, "little"),
        _Spec("simple_config_display_index", 2, False, "little"),
        _Spec("simple_config_power_index", 2, False, "little"),
        _Spec("simple_config_configured_at", 6, True, "little"),
        _Spec("reserved", 6, True, "little"),
    )


@dataclass
class PowerOption(_PackedStruct):
    """Power source, battery model, sleep/advertising timing, battery-sense and charger pins,
    and EPD keep-alive. Required singleton. 30 bytes.  [config packet 0x04; required]  (30
    wire bytes.)
    """

    # power source type.  [enum PowerMode]
    power_mode: int = 0
    # battery capacity, 24-bit LE; 0 = unknown.  [unit mAh]
    battery_capacity_mah: bytes = b""
    # nominal awake/advertising time before sleep (actual may be shorter).  [unit ms]
    sleep_timeout_ms: int = 0
    # BLE transmit-power setting (platform-specific units).
    tx_power: int = 0
    # sleep-related flags (bitfield).  [bits SleepFlags]
    sleep_flags: int = 0
    # ADC pin measuring battery voltage; 0xFF = none.  [default 0xFF]
    battery_sense_pin: int = 0
    # pin enabling the battery-sense divider; 0xFF = none.  [default 0xFF]
    battery_sense_enable_pin: int = 0
    # battery-sense flags (bitfield).  [bits BatterySenseFlags]
    battery_sense_flags: int = 0
    # battery chemistry model.  [enum CapacityEstimator]
    capacity_estimator: int = 0
    # ADC voltage scaling / divider factor (implementation-specific).
    voltage_scaling_factor: int = 0
    # board deep-sleep current excl. MCU; 0 = unknown.  [unit uA]
    deep_sleep_current_ua: int = 0
    # timer deep-sleep duration (ESP32 on battery); 0 = disabled.  [unit s]
    deep_sleep_time_seconds: int = 0
    # BQ25616 charge-enable GPIO; 0 or 0xFF = unused.  [default 0xFF]
    charge_enable_pin: int = 0
    # BQ25616 charge-state input GPIO; 0 or 0xFF = unused.  [default 0xFF]
    charge_state_pin: int = 0
    # charger polarity flags (bitfield).  [bits ChargerFlags]
    charger_flags: int = 0
    # min awake window after first boot / button wake; 0 = default 120 s.  [unit s]
    min_wake_time_seconds: int = 0
    # EPD keep-alive: seconds the panel stays powered after a refresh before shutdown
    # (values >30 clamped; 0 = power off immediately; forced 0 when an AXP2101 PMIC is
    # present).  [unit s, min 0, max 30]
    screen_timeout_seconds: int = 0
    # future use; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 30
    PACKET_ID: ClassVar[int] = 0x04
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("power_mode", 1, False, "little"),
        _Spec("battery_capacity_mah", 3, True, "little"),
        _Spec("sleep_timeout_ms", 2, False, "little"),
        _Spec("tx_power", 1, False, "little"),
        _Spec("sleep_flags", 1, False, "little"),
        _Spec("battery_sense_pin", 1, False, "little"),
        _Spec("battery_sense_enable_pin", 1, False, "little"),
        _Spec("battery_sense_flags", 1, False, "little"),
        _Spec("capacity_estimator", 1, False, "little"),
        _Spec("voltage_scaling_factor", 2, False, "little"),
        _Spec("deep_sleep_current_ua", 4, False, "little"),
        _Spec("deep_sleep_time_seconds", 2, False, "little"),
        _Spec("charge_enable_pin", 1, False, "little"),
        _Spec("charge_state_pin", 1, False, "little"),
        _Spec("charger_flags", 1, False, "little"),
        _Spec("min_wake_time_seconds", 2, False, "little"),
        _Spec("screen_timeout_seconds", 1, False, "little"),
        _Spec("reserved", 4, True, "little"),
    )


@dataclass
class DisplayConfig(_PackedStruct):
    """Per-panel configuration: geometry, controller, SPI pins, color scheme, and supported
    transmission modes. Up to 4 instances. 46 bytes.  [config packet 0x20; repeatable (max
    4)]  (46 wire bytes.)
    """

    # 0-based display index (unique per display block).
    instance_number: int = 0
    # panel technology.  [enum DisplayTechnology]
    display_technology: int = 0
    # display controller / panel type.  [enum PanelIC]
    panel_ic_type: int = 0
    # panel pixel width.  [unit px]
    pixel_width: int = 0
    # panel pixel height.  [unit px]
    pixel_height: int = 0
    # active area width.  [unit mm]
    active_width_mm: int = 0
    # active area height.  [unit mm]
    active_height_mm: int = 0
    # OEPL legacy tag type (optional; 0 if unused). Canonical snake_case of config.yaml
    # legacy_tagtype / firmware tag_type.
    legacy_tag_type: int = 0
    # physical rotation.  [enum Rotation]
    rotation: int = 0
    # panel reset GPIO; 0xFF = none.  [default 0xFF]
    reset_pin: int = 0
    # panel busy-status GPIO; 0xFF = none.  [default 0xFF]
    busy_pin: int = 0
    # data/command select; doubles as SPI MISO on OpenDisplay-runtime IT8951 / Seeed ED103
    # panels.
    dc_pin: int = 0
    # SPI chip-select; 0xFF = none.  [default 0xFF]
    cs_pin: int = 0
    # data-out pin (SPI MOSI / data line).
    data_pin: int = 0
    # partial-update capability.  [enum PartialUpdateSupport]
    partial_update_support: int = 0
    # color/plane scheme.  [enum ColorScheme]
    color_scheme: int = 0
    # supported image/data transmission modes (bitfield).  [bits TransmissionModes]
    transmission_modes: int = 0
    # SPI SCLK pin.
    clk_pin: int = 0
    # second CS for panels split over 2 drivers (dual-controller Spectra); 0xFF = none.
    # Canonical name (firmware called it reserved_pin_2).  [default 0xFF, since 1.4]
    cs_pin_2: int = 0
    # spare pin; must be 0.  [reserved]
    reserved_pin_3: int = 0
    # spare pin; must be 0.  [reserved]
    reserved_pin_4: int = 0
    # spare pin; must be 0.  [reserved]
    reserved_pin_5: int = 0
    # spare pin; must be 0.  [reserved]
    reserved_pin_6: int = 0
    # spare pin; must be 0.  [reserved]
    reserved_pin_7: int = 0
    # spare pin; must be 0.  [reserved]
    reserved_pin_8: int = 0
    # energy consumed by a full refresh; 0 = unknown.  [unit mC]
    full_update_mC: int = 0
    # future use; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 46
    PACKET_ID: ClassVar[int] = 0x20
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("instance_number", 1, False, "little"),
        _Spec("display_technology", 1, False, "little"),
        _Spec("panel_ic_type", 2, False, "little"),
        _Spec("pixel_width", 2, False, "little"),
        _Spec("pixel_height", 2, False, "little"),
        _Spec("active_width_mm", 2, False, "little"),
        _Spec("active_height_mm", 2, False, "little"),
        _Spec("legacy_tag_type", 2, False, "little"),
        _Spec("rotation", 1, False, "little"),
        _Spec("reset_pin", 1, False, "little"),
        _Spec("busy_pin", 1, False, "little"),
        _Spec("dc_pin", 1, False, "little"),
        _Spec("cs_pin", 1, False, "little"),
        _Spec("data_pin", 1, False, "little"),
        _Spec("partial_update_support", 1, False, "little"),
        _Spec("color_scheme", 1, False, "little"),
        _Spec("transmission_modes", 1, False, "little"),
        _Spec("clk_pin", 1, False, "little"),
        _Spec("cs_pin_2", 1, False, "little"),
        _Spec("reserved_pin_3", 1, False, "little"),
        _Spec("reserved_pin_4", 1, False, "little"),
        _Spec("reserved_pin_5", 1, False, "little"),
        _Spec("reserved_pin_6", 1, False, "little"),
        _Spec("reserved_pin_7", 1, False, "little"),
        _Spec("reserved_pin_8", 1, False, "little"),
        _Spec("full_update_mC", 2, False, "little"),
        _Spec("reserved", 13, True, "little"),
    )


@dataclass
class LedConfig(_PackedStruct):
    """LED channel pins + invert flags. Up to 4 instances. 22 bytes. NOTE: the 15-byte
    reserved[] tail also carries the runtime LED flash pattern (bytes 0..11) written by
    CMD_LED_ACTIVATE 0x0073 -- see struct LedFlashPattern.  [config packet 0x21; repeatable
    (max 4)]  (22 wire bytes.)
    """

    # 0-based LED-block index.
    instance_number: int = 0
    # LED wiring type.  [enum LedType]
    led_type: int = 0
    # channel 1 (red) pin; 0xFF = unused.
    led_1_r: int = 0
    # channel 2 (green) pin; 0xFF = unused.
    led_2_g: int = 0
    # channel 3 (blue) pin; 0xFF = unused.
    led_3_b: int = 0
    # channel 4 pin (if present); 0xFF = unused.
    led_4: int = 0
    # per-channel invert flags (bitfield).  [bits LedFlags]
    led_flags: int = 0
    # future use; bytes 0..11 hold the runtime LedFlashPattern (see 0x0073). Must be 0 in a
    # fresh config.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 22
    PACKET_ID: ClassVar[int] = 0x21
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("instance_number", 1, False, "little"),
        _Spec("led_type", 1, False, "little"),
        _Spec("led_1_r", 1, False, "little"),
        _Spec("led_2_g", 1, False, "little"),
        _Spec("led_3_b", 1, False, "little"),
        _Spec("led_4", 1, False, "little"),
        _Spec("led_flags", 1, False, "little"),
        _Spec("reserved", 15, True, "little"),
    )


@dataclass
class SensorData(_PackedStruct):
    """A sensor bound to a data bus, with its MSD publish slot. Up to 4 instances. 30 bytes.
    [config packet 0x23; repeatable (max 4)]  (30 wire bytes.)
    """

    # 0-based sensor-block index.
    instance_number: int = 0
    # sensor type.  [enum SensorType]
    sensor_type: int = 0
    # data_bus instance this sensor lives on.
    bus_id: int = 0
    # I2C 7-bit address; 0 or 0xFF = per-sensor default (SHT40 0x44, BQ27220 0x55).
    # [default 0xFF]
    i2c_addr_7bit: int = 0
    # first dynamicreturndata index this sensor publishes into. SHT40 uses 3 bytes (0/0xFF =
    # default 7); BQ27220 uses 1 packed byte (0xFF = do not publish).  [default 0xFF]
    msd_data_start_byte: int = 0
    # future use; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 30
    PACKET_ID: ClassVar[int] = 0x23
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("instance_number", 1, False, "little"),
        _Spec("sensor_type", 2, False, "little"),
        _Spec("bus_id", 1, False, "little"),
        _Spec("i2c_addr_7bit", 1, False, "little"),
        _Spec("msd_data_start_byte", 1, False, "little"),
        _Spec("reserved", 24, True, "little"),
    )


@dataclass
class DataBus(_PackedStruct):
    """A shared I2C/SPI bus definition (pins, speed, pull config) other packets reference by
    instance. Up to 4 instances. 30 bytes.  [config packet 0x24; repeatable (max 4)]  (30
    wire bytes.)
    """

    # 0-based bus-block index; referenced by SensorData.bus_id, TouchController.bus_id, etc.
    instance_number: int = 0
    # bus protocol.  [enum BusType]
    bus_type: int = 0
    # pin 1 (SCL for I2C).
    pin_1: int = 0
    # pin 2 (SDA for I2C).
    pin_2: int = 0
    # pin 3 (aux / SPI).
    pin_3: int = 0
    # pin 4 (aux).
    pin_4: int = 0
    # pin 5 (aux).
    pin_5: int = 0
    # pin 6 (aux).
    pin_6: int = 0
    # pin 7 (aux).
    pin_7: int = 0
    # bus clock speed.  [unit Hz]
    bus_speed_hz: int = 0
    # bus flags (all reserved today; must be 0).  [bits BusFlags]
    bus_flags: int = 0
    # internal pull-ups, bit N-1 = pin N (pin_1..pin_7); bit 7 reserved.  [bits PinBitmap]
    pullups: int = 0
    # internal pull-downs, bit N-1 = pin N (pin_1..pin_7); bit 7 reserved.  [bits PinBitmap]
    pulldowns: int = 0
    # future use; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 30
    PACKET_ID: ClassVar[int] = 0x24
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("instance_number", 1, False, "little"),
        _Spec("bus_type", 1, False, "little"),
        _Spec("pin_1", 1, False, "little"),
        _Spec("pin_2", 1, False, "little"),
        _Spec("pin_3", 1, False, "little"),
        _Spec("pin_4", 1, False, "little"),
        _Spec("pin_5", 1, False, "little"),
        _Spec("pin_6", 1, False, "little"),
        _Spec("pin_7", 1, False, "little"),
        _Spec("bus_speed_hz", 4, False, "little"),
        _Spec("bus_flags", 1, False, "little"),
        _Spec("pullups", 1, False, "little"),
        _Spec("pulldowns", 1, False, "little"),
        _Spec("reserved", 14, True, "little"),
    )


@dataclass
class BinaryInputs(_PackedStruct):
    """Up to 8 button/switch pins per block, with per-pin used/invert/pull and long-press
    power-off config. Up to 4 instances. 30 bytes. Field names are the canonical snake_case
    (config.yaml inputpinN -> input_pin_N, isused -> pins_used; firmware called pins
    reserved_pin_N).  [config packet 0x25; repeatable (max 4)]  (30 wire bytes.)
    """

    # 0-based input-block index.
    instance_number: int = 0
    # input hardware type.  [enum InputType]
    input_type: int = 0
    # how to render the input.  [enum InputDisplayAs]
    display_as: int = 0
    # input pin 1 GPIO; 0xFF = not configured.  [default 0xFF]
    input_pin_1: int = 0
    # input pin 2 GPIO; 0xFF = not configured.  [default 0xFF]
    input_pin_2: int = 0
    # input pin 3 GPIO; 0xFF = not configured.  [default 0xFF]
    input_pin_3: int = 0
    # input pin 4 GPIO; 0xFF = not configured.  [default 0xFF]
    input_pin_4: int = 0
    # input pin 5 GPIO; 0xFF = not configured.  [default 0xFF]
    input_pin_5: int = 0
    # input pin 6 GPIO; 0xFF = not configured.  [default 0xFF]
    input_pin_6: int = 0
    # input pin 7 GPIO; 0xFF = not configured.  [default 0xFF]
    input_pin_7: int = 0
    # input pin 8 GPIO; 0xFF = not configured.  [default 0xFF]
    input_pin_8: int = 0
    # which pins are active (bit N-1 = input_pin_N).  [bits PinBitmap]
    pins_used: int = 0
    # per-pin logic invert (bit N-1 = input_pin_N).  [bits PinBitmap]
    invert: int = 0
    # per-pin internal pull-up (bit N-1 = input_pin_N).  [bits PinBitmap]
    pullups: int = 0
    # per-pin internal pull-down (bit N-1 = input_pin_N).  [bits PinBitmap]
    pulldowns: int = 0
    # dynamicreturndata index this block reports button state into (bounded integer, not an
    # enum). 0xFF = not published.  [min 0, max 10, default 0xFF]
    button_data_byte_index: int = 0
    # bit N-1 = input_pin_N triggers long-press power-off (latched devices only; ignored
    # otherwise).  [bits PinBitmap]
    power_off_flags: int = 0
    # hold time before power-off; 0 = default 3 s (latched devices only).  [unit s]
    power_off_hold_sec: int = 0
    # future use; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 30
    PACKET_ID: ClassVar[int] = 0x25
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("instance_number", 1, False, "little"),
        _Spec("input_type", 1, False, "little"),
        _Spec("display_as", 1, False, "little"),
        _Spec("input_pin_1", 1, False, "little"),
        _Spec("input_pin_2", 1, False, "little"),
        _Spec("input_pin_3", 1, False, "little"),
        _Spec("input_pin_4", 1, False, "little"),
        _Spec("input_pin_5", 1, False, "little"),
        _Spec("input_pin_6", 1, False, "little"),
        _Spec("input_pin_7", 1, False, "little"),
        _Spec("input_pin_8", 1, False, "little"),
        _Spec("pins_used", 1, False, "little"),
        _Spec("invert", 1, False, "little"),
        _Spec("pullups", 1, False, "little"),
        _Spec("pulldowns", 1, False, "little"),
        _Spec("button_data_byte_index", 1, False, "little"),
        _Spec("power_off_flags", 1, False, "little"),
        _Spec("power_off_hold_sec", 1, False, "little"),
        _Spec("reserved", 12, True, "little"),
    )


@dataclass
class WifiConfig(_PackedStruct):
    """WiFi credentials plus optional upload server host/port. Singleton. 160 bytes. This
    header is AHEAD of current firmware: server_host + server_port are promoted out of the
    former reserved[95] (a backward-compatible carve -- the bytes were must-be-zero, so old
    peers still interop; only a peer that writes a real port must honor the big-endian
    server_port). NOTE server_port is the ONE big-endian field in this otherwise little-
    endian struct.  [config packet 0x26]  (160 wire bytes.)
    """

    # WiFi SSID, null-terminated and zero-padded to 32 bytes.
    ssid: bytes = b""
    # WiFi password, null-terminated and zero-padded (empty for open networks).
    password: bytes = b""
    # network security type.  [enum WifiEncryptionType]
    encryption_type: int = 0
    # upload server URL/hostname, null-terminated and zero-padded to 64 bytes; empty = none.
    # Promoted out of reserved[].  [since 1.4]
    server_host: bytes = b""
    # upload server TCP port, BIG-ENDIAN (the single BE field here). 0 = default/none.
    # Promoted out of reserved[] at former indices 64-65.  [BIG-ENDIAN, since 1.4]
    server_port: int = 0
    # future use; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 160
    PACKET_ID: ClassVar[int] = 0x26
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("ssid", 32, True, "little"),
        _Spec("password", 32, True, "little"),
        _Spec("encryption_type", 1, False, "little"),
        _Spec("server_host", 64, True, "little"),
        _Spec("server_port", 2, False, "big"),
        _Spec("reserved", 29, True, "little"),
    )


@dataclass
class SecurityConfig(_PackedStruct):
    """Application-layer encryption master key and reset-pin config. Singleton. 64 bytes. The
    AEAD envelope and auth handshake are specified in opendisplay_protocol.h; this packet
    only stores the pre-shared key + policy.  [config packet 0x27]  (64 wire bytes.)
    """

    # 0 = disabled (all commands work unauthenticated); 1 = enabled (sensitive commands
    # require a session). If encryption_key is all-zero, encryption is off regardless.
    encryption_enabled: int = 0
    # AES-128 master key (16 bytes).
    encryption_key: bytes = b""
    # session timeout; 0 = no timeout (persists until disconnect).  [unit s]
    session_timeout_seconds: int = 0
    # security policy flags (bitfield).  [bits SecurityFlags]
    flags: int = 0
    # reset GPIO; when enabled and triggered, securely erases config and reboots.  [default
    # 0xFF]
    reset_pin: int = 0
    # future use; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 64
    PACKET_ID: ClassVar[int] = 0x27
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("encryption_enabled", 1, False, "little"),
        _Spec("encryption_key", 16, True, "little"),
        _Spec("session_timeout_seconds", 2, False, "little"),
        _Spec("flags", 1, False, "little"),
        _Spec("reset_pin", 1, False, "little"),
        _Spec("reserved", 43, True, "little"),
    )


@dataclass
class TouchController(_PackedStruct):
    """Capacitive touch controller on I2C (e.g. GT911). Publishes the first contact (5 bytes)
    into MSD dynamic data. Up to 4 instances. 32 bytes.  [config packet 0x28; repeatable
    (max 4)]  (32 wire bytes.)
    """

    # 0-based touch-block index.
    instance_number: int = 0
    # touch controller IC.  [enum TouchIcType]
    touch_ic_type: int = 0
    # data_bus instance for I2C; 0xFF means bus 0.
    bus_id: int = 0
    # I2C 7-bit address (GT911 0x5D or 0x14); 0 or 0xFF = auto-detect.  [default 0xFF]
    i2c_addr_7bit: int = 0
    # interrupt GPIO (active low); 0xFF = poll only.  [default 0xFF]
    int_pin: int = 0
    # reset GPIO; 0xFF = skip hardware reset (probe only).  [default 0xFF]
    rst_pin: int = 0
    # DisplayConfig index used for coordinate clip / invert reference.
    display_instance: int = 0
    # coordinate mapping flags (bitfield).  [bits TouchFlags]
    flags: int = 0
    # minimum time between polls; 0 = default 25 ms.  [unit ms]
    poll_interval_ms: int = 0
    # start index in dynamicreturndata for the 5-byte touch block (avoid overlap with
    # binary_inputs).  [min 0, max 6]
    touch_data_start_byte: int = 0
    # optional touch-panel power-enable GPIO (active high); 0 or 0xFF = unused.  [default
    # 0xFF]
    enable_pin: int = 0
    # future use (e.g. GT911 register profile); must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 32
    PACKET_ID: ClassVar[int] = 0x28
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("instance_number", 1, False, "little"),
        _Spec("touch_ic_type", 2, False, "little"),
        _Spec("bus_id", 1, False, "little"),
        _Spec("i2c_addr_7bit", 1, False, "little"),
        _Spec("int_pin", 1, False, "little"),
        _Spec("rst_pin", 1, False, "little"),
        _Spec("display_instance", 1, False, "little"),
        _Spec("flags", 1, False, "little"),
        _Spec("poll_interval_ms", 1, False, "little"),
        _Spec("touch_data_start_byte", 1, False, "little"),
        _Spec("enable_pin", 1, False, "little"),
        _Spec("reserved", 20, True, "little"),
    )


@dataclass
class BuzzerConfig(_PackedStruct):
    """Buzzer (passive piezo, PWM-driven). Up to 4 instances. 32 bytes. The tone PATTERN is not
    stored here -- it is carried variable-length by CMD_BUZZER 0x0077
    ([instance][outer_repeats][n_patterns] then per-pattern n_steps x (freq:u8,
    duration:u8)); that payload stays prose-documented in opendisplay_protocol.h (it is
    variable-length, so not modeled as a struct).  [config packet 0x29; repeatable (max 4)]
    (32 wire bytes.)
    """

    # 0-based buzzer-block index.
    instance_number: int = 0
    # GPIO driving the PWM / square wave into the buzzer (via transistor). Pin encoding is
    # target-defined (e.g. nRF54 (port<<4)|pin).
    drive_pin: int = 0
    # optional enable (e.g. FET); 0xFF = unused.  [default 0xFF]
    enable_pin: int = 0
    # buzzer flags (bitfield).  [bits BuzzerFlags]
    flags: int = 0
    # PWM duty cycle; 0 = default 50.  [min 1, max 100]
    duty_percent: int = 0
    # future use (incl. internal frequency/time scaling); must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 32
    PACKET_ID: ClassVar[int] = 0x29
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("instance_number", 1, False, "little"),
        _Spec("drive_pin", 1, False, "little"),
        _Spec("enable_pin", 1, False, "little"),
        _Spec("flags", 1, False, "little"),
        _Spec("duty_percent", 1, False, "little"),
        _Spec("reserved", 27, True, "little"),
    )


@dataclass
class NfcConfig(_PackedStruct):
    """NFC IC selection, data bus, and optional field-detect GPIO that maps a button-like state
    into the BLE advertisement. Up to 2 instances. 32 bytes.  [config packet 0x2A;
    repeatable (max 2)]  (32 wire bytes.)
    """

    # 0-based NFC-block index.
    instance_number: int = 0
    # NFC IC / flow selector.  [enum OD_NFC_IC]
    nfc_ic_type: int = 0
    # data_bus instance (I2C) to use.
    bus_instance: int = 0
    # NFC flags (bitfield); bit0 must be set to enable.  [bits NfcFlags]
    flags: int = 0
    # field-detect input GPIO; 0xFF = disabled.  [default 0xFF]
    field_detect_pin: int = 0
    # field-detect sensing mode.  [enum NfcFieldDetectMode]
    field_detect_mode: int = 0
    # active level of field_detect_pin.  [enum ActiveLevel]
    field_detect_active: int = 0
    # debounce time; 0 = no debounce.  [unit ms]
    field_detect_debounce_ms: int = 0
    # NFC rail enable pin; 0xFF = use data_bus pin_3 if present, else none.  [default 0xFF]
    power_pin: int = 0
    # power-pin polarity (reserved in current firmware).  [enum ActiveLevel]
    power_active: int = 0
    # delay after enabling power before NFC access.  [unit ms]
    power_on_delay_ms: int = 0
    # delay before power-off/park (reserved in current firmware).  [unit ms]
    power_off_delay_ms: int = 0
    # dynamicreturndata index for the field-detect button-like state.  [min 0, max 10]
    adv_button_byte_index: int = 0
    # 3-bit button id (stored in the lower bits) for the advertised state.
    adv_button_button_id: int = 0
    # spare pin; must be 0.  [reserved]
    reserved_pin_1: int = 0
    # spare pin; must be 0.  [reserved]
    reserved_pin_2: int = 0
    # future NFC IC-specific extensions; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 32
    PACKET_ID: ClassVar[int] = 0x2A
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("instance_number", 1, False, "little"),
        _Spec("nfc_ic_type", 1, False, "little"),
        _Spec("bus_instance", 1, False, "little"),
        _Spec("flags", 1, False, "little"),
        _Spec("field_detect_pin", 1, False, "little"),
        _Spec("field_detect_mode", 1, False, "little"),
        _Spec("field_detect_active", 1, False, "little"),
        _Spec("field_detect_debounce_ms", 1, False, "little"),
        _Spec("power_pin", 1, False, "little"),
        _Spec("power_active", 1, False, "little"),
        _Spec("power_on_delay_ms", 1, False, "little"),
        _Spec("power_off_delay_ms", 1, False, "little"),
        _Spec("adv_button_byte_index", 1, False, "little"),
        _Spec("adv_button_button_id", 1, False, "little"),
        _Spec("reserved_pin_1", 1, False, "little"),
        _Spec("reserved_pin_2", 1, False, "little"),
        _Spec("reserved", 16, True, "little"),
    )


@dataclass
class FlashConfig(_PackedStruct):
    """External SPI flash deep-sleep pin sequencing. Up to 2 instances. 32 bytes. Ignored when
    the enabled flag is clear.  [config packet 0x2B; repeatable (max 2)]  (32 wire bytes.)
    """

    # 0-based flash-block index.
    instance_number: int = 0
    # flash IC type (reserved for future).  [enum FlashIcType]
    flash_ic_type: int = 0
    # reserved for future bus binding.
    bus_instance: int = 0
    # flash flags (bitfield); bit0 must be set to enable.  [bits FlashFlags]
    flags: int = 0
    # SPI MOSI pin (encoding target-defined, e.g. 0xPN).
    mosi_pin: int = 0
    # SPI SCK pin.
    sck_pin: int = 0
    # SPI CS pin.
    cs_pin: int = 0
    # optional power-enable pin (reserved in current firmware).  [default 0xFF]
    power_pin: int = 0
    # power-pin polarity (reserved in current firmware).  [enum ActiveLevel]
    power_active: int = 0
    # power-on delay before first command (reserved).  [unit ms]
    power_on_delay_ms: int = 0
    # power-off delay after command (reserved).  [unit ms]
    power_off_delay_ms: int = 0
    # flash mode selector (reserved for future).
    mode: int = 0
    # future flash extensions; must be 0.  [reserved]
    reserved: bytes = b""

    SIZE: ClassVar[int] = 32
    PACKET_ID: ClassVar[int] = 0x2B
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("instance_number", 1, False, "little"),
        _Spec("flash_ic_type", 1, False, "little"),
        _Spec("bus_instance", 1, False, "little"),
        _Spec("flags", 1, False, "little"),
        _Spec("mosi_pin", 1, False, "little"),
        _Spec("sck_pin", 1, False, "little"),
        _Spec("cs_pin", 1, False, "little"),
        _Spec("power_pin", 1, False, "little"),
        _Spec("power_active", 1, False, "little"),
        _Spec("power_on_delay_ms", 1, False, "little"),
        _Spec("power_off_delay_ms", 1, False, "little"),
        _Spec("mode", 1, False, "little"),
        _Spec("reserved", 20, True, "little"),
    )


@dataclass
class DataExtended(_PackedStruct):
    """Extended device-identity strings. Singleton. 288 bytes = 9 fixed 32-byte fields. Each
    field is a null-terminated, zero-padded UTF-8 string; default is the empty string (all
    zeros).  [config packet 0x2C]  (288 wire bytes.)
    """

    # manufacturer name (32-byte UTF-8, null-terminated, zero-padded).
    manufacturer_name: bytes = b""
    # model name.
    model_name: bytes = b""
    # serial number.
    serial_number: bytes = b""
    # human-friendly device name.
    friendly_name: bytes = b""
    # physical / logical location.
    device_location: bytes = b""
    # unique device identifier string.
    device_id: bytes = b""
    # user-defined string 1.
    custom_string_1: bytes = b""
    # user-defined string 2.
    custom_string_2: bytes = b""
    # user-defined string 3.
    custom_string_3: bytes = b""

    SIZE: ClassVar[int] = 288
    PACKET_ID: ClassVar[int] = 0x2C
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("manufacturer_name", 32, True, "little"),
        _Spec("model_name", 32, True, "little"),
        _Spec("serial_number", 32, True, "little"),
        _Spec("friendly_name", 32, True, "little"),
        _Spec("device_location", 32, True, "little"),
        _Spec("device_id", 32, True, "little"),
        _Spec("custom_string_1", 32, True, "little"),
        _Spec("custom_string_2", 32, True, "little"),
        _Spec("custom_string_3", 32, True, "little"),
    )


@dataclass
class LedFlashPattern(_PackedStruct):
    """12-byte LED flash program carried in CMD_LED_ACTIVATE 0x0073 after the led_instance
    byte; firmware persists it into LedConfig.reserved[0..11]. Odd nibble packing is OEPL-
    compatible -- do not 'fix' it. Three color/loop stages (1,2,3) each contribute a color
    byte, a packed loop-delay/count byte, and an inter-loop delay byte.  [payload of
    CMD_LED_ACTIVATE]  (12 wire bytes.)
    """

    # low nibble = mode (1 = flash, 0 = off); high nibble = brightness minus 1 (0..15 ->
    # brightness 1..16).  [bitfield]
    mode_brightness: int = 0
    # stage-1 color/channel byte.
    color1: int = 0
    # high nibble = stage-1 loop delay (x100 ms); low nibble = stage-1 loop count.
    # [bitfield]
    loop1_delay_count: int = 0
    # stage-1 inter-loop delay (x100 ms); 0 = none.  [unit ms]
    inter_loop_delay1: int = 0
    # stage-2 color/channel byte.
    color2: int = 0
    # high nibble = stage-2 loop delay (x100 ms); low nibble = stage-2 loop count.
    # [bitfield]
    loop2_delay_count: int = 0
    # stage-2 inter-loop delay (x100 ms); 0 = none.  [unit ms]
    inter_loop_delay2: int = 0
    # stage-3 color/channel byte.
    color3: int = 0
    # high nibble = stage-3 loop delay (x100 ms); low nibble = stage-3 loop count.
    # [bitfield]
    loop3_delay_count: int = 0
    # stage-3 inter-loop delay (x100 ms); 0 = none.  [unit ms]
    inter_loop_delay3: int = 0
    # group repeat count minus 1 (value 255 = repeat forever).
    group_repeats: int = 0
    # must be 0.  [reserved]
    reserved: int = 0

    SIZE: ClassVar[int] = 12
    MESSAGE: ClassVar[str] = "CMD_LED_ACTIVATE"
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("mode_brightness", 1, False, "little"),
        _Spec("color1", 1, False, "little"),
        _Spec("loop1_delay_count", 1, False, "little"),
        _Spec("inter_loop_delay1", 1, False, "little"),
        _Spec("color2", 1, False, "little"),
        _Spec("loop2_delay_count", 1, False, "little"),
        _Spec("inter_loop_delay2", 1, False, "little"),
        _Spec("color3", 1, False, "little"),
        _Spec("loop3_delay_count", 1, False, "little"),
        _Spec("inter_loop_delay3", 1, False, "little"),
        _Spec("group_repeats", 1, False, "little"),
        _Spec("reserved", 1, False, "little"),
    )


@dataclass
class PipeStartRequest(_PackedStruct):
    """10-byte PIPE (0x0080) START header that follows the 2 opcode bytes (host->device). If
    flags bit1 (PIPE_FLAG_PARTIAL) is set, a 12-byte PipePartialExt is appended (22 bytes
    total after the opcode). NOTE: the plan inventory listed this as 8 bytes, but the field
    list and protocol.h's '10-byte header (22 when partial)' both give 10 -- 10 is correct.
    [payload of CMD_PIPE_WRITE_START]  (10 wire bytes.)
    """

    # PIPE protocol version = PIPE_VERSION (1).
    version: int = 0
    # [bits PIPE_FLAG]
    flags: int = 0
    # requested sliding-window size (frames).  [min 1, max 32]
    req_window: int = 0
    # requested ACK cadence (frames per SACK).  [min 1, max 32]
    req_ack_every: int = 0
    # largest on-wire frame the client will send.
    client_max_frame: int = 0
    # decompressed byte total to transfer (partial: plane_size x 2).
    total_size: int = 0

    SIZE: ClassVar[int] = 10
    MESSAGE: ClassVar[str] = "CMD_PIPE_WRITE_START"
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("version", 1, False, "little"),
        _Spec("flags", 1, False, "little"),
        _Spec("req_window", 1, False, "little"),
        _Spec("req_ack_every", 1, False, "little"),
        _Spec("client_max_frame", 2, False, "little"),
        _Spec("total_size", 4, False, "little"),
    )


@dataclass
class PipePartialExt(_PackedStruct):
    """12-byte partial-region extension appended to PipeStartRequest when PIPE_FLAG_PARTIAL is
    set. LITTLE-endian twin of the 0x76 PartialWriteStartHeader geometry (which is big-
    endian).  [payload of CMD_PIPE_WRITE_START]  (12 wire bytes.)
    """

    # etag currently displayed; must match or the START is NACKed.
    old_etag: int = 0
    # region left edge.  [unit px]
    x: int = 0
    # region top edge.  [unit px]
    y: int = 0
    # region width.  [unit px]
    w: int = 0
    # region height.  [unit px]
    h: int = 0

    SIZE: ClassVar[int] = 12
    MESSAGE: ClassVar[str] = "CMD_PIPE_WRITE_START"
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("old_etag", 4, False, "little"),
        _Spec("x", 2, False, "little"),
        _Spec("y", 2, False, "little"),
        _Spec("w", 2, False, "little"),
        _Spec("h", 2, False, "little"),
    )


@dataclass
class PipeStartResponse(_PackedStruct):
    """6-byte PIPE START ACK data (device->host): the device echoes its negotiated maxima (min-
    rule applies against the client's request).  [payload of CMD_PIPE_WRITE_START]  (6 wire
    bytes.)
    """

    # PIPE protocol version = PIPE_VERSION (1).
    version: int = 0
    # device-granted maximum window size.
    max_window: int = 0
    # device-granted maximum ACK cadence.
    max_ack_every: int = 0
    # device-granted maximum frame size.
    max_frame: int = 0
    # bit0 = selective-repeat supported; bit1 = partial accepted.  [bitfield]
    resp_flags: int = 0

    SIZE: ClassVar[int] = 6
    MESSAGE: ClassVar[str] = "CMD_PIPE_WRITE_START"
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("version", 1, False, "little"),
        _Spec("max_window", 1, False, "little"),
        _Spec("max_ack_every", 1, False, "little"),
        _Spec("max_frame", 2, False, "little"),
        _Spec("resp_flags", 1, False, "little"),
    )


@dataclass
class PipeSack(_PackedStruct):
    """5-byte selective-ACK data in the PIPE 0x0081 ACK frame (device->host). highest_seen is
    implicitly acked; ack_mask bit i (LSB first) acks chunk (highest_seen - 1 - i).
    [payload of CMD_PIPE_WRITE_DATA]  (5 wire bytes.)
    """

    # highest received seq (mod 256), implicitly acked.
    highest_seen: int = 0
    # selective-ACK bitmask below highest_seen (bit i = seq highest_seen-1-i).
    ack_mask: int = 0

    SIZE: ClassVar[int] = 5
    MESSAGE: ClassVar[str] = "CMD_PIPE_WRITE_DATA"
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("highest_seen", 1, False, "little"),
        _Spec("ack_mask", 4, False, "little"),
    )


@dataclass
class PartialWriteStartHeader(_PackedStruct):
    """17-byte header for CMD_PARTIAL_WRITE_START 0x0076, following the 2 opcode bytes
    (host->device). ENTIRELY BIG-ENDIAN -- the showcase for the per-message endianness
    split: the PIPE 0x80 path carries the same geometry LITTLE-endian (see PipePartialExt).
    x and width must be multiples of 8; old_etag must equal the currently displayed etag.
    [payload of CMD_PARTIAL_WRITE_START]  (17 wire bytes.)
    """

    # partial-write flags (see protocol.h 0x76 @request).
    flags: int = 0
    # etag currently displayed; must match.  [BIG-ENDIAN]
    old_etag: int = 0
    # etag to store after this write.  [BIG-ENDIAN]
    new_etag: int = 0
    # region left edge (multiple of 8).  [unit px, BIG-ENDIAN]
    x: int = 0
    # region top edge.  [unit px, BIG-ENDIAN]
    y: int = 0
    # region width (multiple of 8).  [unit px, BIG-ENDIAN]
    width: int = 0
    # region height.  [unit px, BIG-ENDIAN]
    height: int = 0

    SIZE: ClassVar[int] = 17
    MESSAGE: ClassVar[str] = "CMD_PARTIAL_WRITE_START"
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("flags", 1, False, "big"),
        _Spec("old_etag", 4, False, "big"),
        _Spec("new_etag", 4, False, "big"),
        _Spec("x", 2, False, "big"),
        _Spec("y", 2, False, "big"),
        _Spec("width", 2, False, "big"),
        _Spec("height", 2, False, "big"),
    )


@dataclass
class AuthChallenge(_PackedStruct):
    """21-byte CMD_AUTHENTICATE 0x0050 step-1 response DATA (device->host), after the
    [status][echo] framing: the device's nonce + id the client signs. This handshake is
    ALWAYS plaintext (bootstraps the session).  [payload of CMD_AUTHENTICATE]  (21 wire
    bytes.)
    """

    # auth status = AUTH_STATUS_CHALLENGE (0x00) on success (see protocol.h).
    status: int = 0
    # device nonce; part of the CMAC input.
    server_nonce: bytes = b""
    # device id; part of the CMAC input.
    device_id: int = 0

    SIZE: ClassVar[int] = 21
    MESSAGE: ClassVar[str] = "CMD_AUTHENTICATE"
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("status", 1, False, "little"),
        _Spec("server_nonce", 16, True, "little"),
        _Spec("device_id", 4, False, "little"),
    )


@dataclass
class AuthProof(_PackedStruct):
    """32-byte CMD_AUTHENTICATE 0x0050 step-2 request payload (host->device): the client nonce
    and the AES-CMAC over (server_nonce || client_nonce || device_id).  [payload of
    CMD_AUTHENTICATE]  (32 wire bytes.)
    """

    # client nonce; part of the CMAC input.
    client_nonce: bytes = b""
    # AES-CMAC(master_key, server_nonce || client_nonce || device_id).
    mac: bytes = b""

    SIZE: ClassVar[int] = 32
    MESSAGE: ClassVar[str] = "CMD_AUTHENTICATE"
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("client_nonce", 16, True, "little"),
        _Spec("mac", 16, True, "little"),
    )


@dataclass
class MsdAdvertisement(_PackedStruct):
    """16-byte OpenDisplay manufacturer-specific data. Broadcast in BLE advertisements and
    returned by CMD_READ_MSD 0x0044 (device->host). Battery voltage is 10 bits (10 mV
    units): the low 8 bits are battery_voltage_low, the 9th bit is status bit0; the 10th is
    implied 0 / reserved by firmware.  [payload of CMD_READ_MSD]  (16 wire bytes.)
    """

    # BLE company identifier.
    company_id: int = 0
    # config-driven dynamic area: button/touch/SHT40/BQ27220 slots at indices set by the
    # relevant config packets.
    dynamic: bytes = b""
    # MCU chip temperature (signed degrees C, firmware-defined offset).  [unit C]
    chip_temperature: int = 0
    # low 8 bits of the 10-bit battery voltage (10 mV units); high bit in status bit0.
    # [unit 10mV]
    battery_voltage_low: int = 0
    # status flags + battery voltage MSB + main-loop counter nibble.  [bits MsdStatusBits]
    status: int = 0

    SIZE: ClassVar[int] = 16
    MESSAGE: ClassVar[str] = "CMD_READ_MSD"
    _FIELDS: ClassVar[Tuple[_Spec, ...]] = (
        _Spec("company_id", 2, False, "little"),
        _Spec("dynamic", 11, True, "little"),
        _Spec("chip_temperature", 1, False, "little"),
        _Spec("battery_voltage_low", 1, False, "little"),
        _Spec("status", 1, False, "little"),
    )


__all__ = [
    "OD_STRUCTS_VERSION_MAJOR",
    "OD_STRUCTS_VERSION_MINOR",
    "OD_STRUCTS_VERSION_STR",
    "OD_CONFIG_VERSION",
    "OD_CONFIG_MINOR_VERSION",
    "OD_CONFIG_CRC_POLY",
    "OD_CONFIG_CRC_INIT",
    "OD_PIN_UNUSED",
    "ConfigPacketType",
    "ActiveLevel",
    "ICType",
    "ManufacturerId",
    "PowerMode",
    "CapacityEstimator",
    "DisplayTechnology",
    "Rotation",
    "PartialUpdateSupport",
    "ColorScheme",
    "PanelIC",
    "LedType",
    "SensorType",
    "BusType",
    "InputType",
    "InputDisplayAs",
    "WifiEncryptionType",
    "TouchIcType",
    "NfcFieldDetectMode",
    "FlashIcType",
    "CommunicationModes",
    "OD_COMM_MODE_BLE",
    "OD_COMM_MODE_OEPL",
    "OD_COMM_MODE_WIFI",
    "DeviceFlags",
    "OD_DEVICE_FLAG_PWR_PIN",
    "OD_DEVICE_FLAG_XIAO_INIT",
    "OD_DEVICE_FLAG_WS_PP_INIT",
    "OD_DEVICE_FLAG_PWR_LATCH",
    "OD_DEVICE_FLAG_PWR_LATCH_DFF",
    "SleepFlags",
    "OD_SLEEP_FLAG_BUTTON_WAKE_DISABLE",
    "BatterySenseFlags",
    "OD_BATTERY_SENSE_FLAG_ENABLE_INVERTED",
    "ChargerFlags",
    "OD_CHARGER_FLAG_ENABLE_ACTIVE_LOW",
    "OD_CHARGER_FLAG_STATE_ACTIVE_LOW",
    "TransmissionModes",
    "OD_TRANSMISSION_MODE_STREAMING_DECOMPRESSION",
    "OD_TRANSMISSION_MODE_ZIP",
    "OD_TRANSMISSION_MODE_G5",
    "OD_TRANSMISSION_MODE_DIRECT_WRITE",
    "OD_TRANSMISSION_MODE_PIPE_WRITE",
    "OD_TRANSMISSION_MODE_RESERVED_5",
    "OD_TRANSMISSION_MODE_RESERVED_6",
    "OD_TRANSMISSION_MODE_CLEAR_ON_BOOT",
    "LedFlags",
    "OD_LED_FLAG_LED1_INVERT",
    "OD_LED_FLAG_LED2_INVERT",
    "OD_LED_FLAG_LED3_INVERT",
    "OD_LED_FLAG_LED4_INVERT",
    "SecurityFlags",
    "OD_SECURITY_FLAG_REWRITE_ALLOWED",
    "OD_SECURITY_FLAG_SHOW_KEY_ON_SCREEN",
    "OD_SECURITY_FLAG_RESET_PIN_ENABLED",
    "OD_SECURITY_FLAG_RESET_PIN_POLARITY",
    "OD_SECURITY_FLAG_RESET_PIN_PULLUP",
    "OD_SECURITY_FLAG_RESET_PIN_PULLDOWN",
    "TouchFlags",
    "OD_TOUCH_FLAG_INVERT_X",
    "OD_TOUCH_FLAG_INVERT_Y",
    "OD_TOUCH_FLAG_SWAP_XY",
    "BuzzerFlags",
    "OD_BUZZER_FLAG_ENABLE_ACTIVE_HIGH",
    "NfcFlags",
    "OD_NFC_FLAG_ENABLED",
    "FlashFlags",
    "OD_FLASH_FLAG_ENABLED",
    "MsdStatusBits",
    "OD_MSD_STATUS_BATTERY_VOLTAGE_BIT8",
    "OD_MSD_STATUS_REBOOT_FLAG",
    "OD_MSD_STATUS_CONNECTION_REQUESTED",
    "OD_MSD_STATUS_RESERVED_3",
    "OD_MSD_STATUS_MAIN_LOOP_COUNTER_SHIFT",
    "OD_MSD_STATUS_MAIN_LOOP_COUNTER_MASK",
    "OuterPacketHeader",
    "SinglePacketHeader",
    "SystemConfig",
    "ManufacturerData",
    "PowerOption",
    "DisplayConfig",
    "LedConfig",
    "SensorData",
    "DataBus",
    "BinaryInputs",
    "WifiConfig",
    "SecurityConfig",
    "TouchController",
    "BuzzerConfig",
    "NfcConfig",
    "FlashConfig",
    "DataExtended",
    "LedFlashPattern",
    "PipeStartRequest",
    "PipePartialExt",
    "PipeStartResponse",
    "PipeSack",
    "PartialWriteStartHeader",
    "AuthChallenge",
    "AuthProof",
    "MsdAdvertisement",
]
